from gen_common import *

UNAV = [
  ("Overview", [("index.html","bi-grid-1x2-fill","Dashboard",None),("notifications.html","bi-bell-fill","Notifications","2")]),
  ("Get help", [("ask.html","bi-plus-circle-fill","Ask a question",None),("questions.html","bi-chat-square-text-fill","My questions","1"),("chat.html","bi-chat-dots-fill","Live chat","1"),("connections.html","bi-people-fill","Lawyers who replied",None)]),
  ("Saved", [("saved.html","bi-bookmark-heart-fill","Saved lawyers",None),("coupons.html","bi-ticket-perforated-fill","Coupons",None),("reviews.html","bi-star-fill","My reviews",None)]),
  ("Account", [("settings.html","bi-gear-fill","Settings",None)]),
]

def build():
    use_site(ROOT + 'user/', 'My account', UNAV, ('Tom Becker', 'TB', 'Orlando, FL', None), 'Search your questions and lawyers…', [("ask.html","bi-plus-lg","Ask a question")], public_link='../frontend/index.html')

    # ============ Dashboard ============
    q = card('Your latest question', f'<div class="card-body"><div class="d-flex gap-2 flex-wrap mb-2"><span class="tag">DUI / DWI</span><span class="tag">Orlando, FL</span>{status_pill("Answered")}<span class="tag">Posted anonymously</span></div><h3 style="font-size:17px;font-weight:700;margin-bottom:8px">Can I refuse a breathalyzer in Florida without losing my license?</h3><p class="muted" style="font-size:13.5px">3 lawyer answers · first reply in 9 minutes · 412 views</p><div class="lawyer-card mt-2">{pav("Amir A. Ladan")}<div class="grow"><h4>Amir A. Ladan {pill("ok","Verified")}</h4><div class="meta">Criminal Defense • DUI / DWI · Orlando, FL · {stars(4.9)} 4.9 (128)</div><p class="quote mt-2 mb-0">“You have 10 days from the arrest to request a formal review hearing with the DHSMV…”</p></div><div class="actions-col"><a href="question-details.html" class="btn-brand btn-sm">Read answers</a><button class="btn-outline btn-sm"><i class="bi bi-telephone"></i> Call</button><button class="btn-outline btn-sm"><i class="bi bi-chat-dots"></i> Chat</button></div></div></div>')
    steps_card = card('What happens next', '<div class="card-body">' + timeline([("bi-check-lg","ok","<strong>Question routed</strong> to 4 verified DUI lawyers in Orlando","2 hrs ago"),("bi-check-lg","ok","<strong>Amir A. Ladan replied</strong> and called you","1 hr ago"),("bi-arrow-right","","<strong>You decide</strong>: hire them, ask another lawyer, or walk away. Fees are always between you and the lawyer.","now")]) + '</div>')
    right = card('Ask another question', '<div class="card-body"><p class="muted" style="font-size:13px">Free, any time. Verified local lawyers reply, usually within minutes.</p><a href="ask.html" class="btn-brand w-100"><i class="bi bi-plus-lg"></i> Ask a free question</a><div class="or" style="display:flex;align-items:center;gap:12px;font-size:12.5px;color:var(--faint);margin:14px 0"><span style="flex:1;height:1px;background:var(--line)"></span>or<span style="flex:1;height:1px;background:var(--line)"></span></div><a href="../frontend/search.html" target="_blank" class="btn-outline w-100"><i class="bi bi-search"></i> Find a lawyer</a><button class="btn-outline w-100 mt-2"><img src="assets/images/kozi-mascot.png" alt="" style="width:22px;border-radius:50%"> Chat with Kozi</button></div>') + card('Saved lawyers', '<div class="card-body"><ul class="list">' + ''.join(f'<li>{pav(n)}<div class="grow"><strong>{n}</strong><span>{PROV[n][1]}</span></div><button class="icon-btn"><i class="bi bi-telephone"></i></button></li>' for n in ["Amir A. Ladan","John P. Morgan"]) + '</ul><a href="saved.html" class="btn-ghost btn-sm w-100 mt-2">All saved</a></div>') + card('Coupon you claimed', '<div class="card-body"><div class="coupon-card"><strong style="color:var(--ink)">Free DUI consultation</strong><div class="muted" style="font-size:12.5px">Amir A. Ladan · show this code</div><div class="d-flex justify-content-between align-items-end mt-2"><div class="price">Free<s>$150</s></div><span class="code">KOZI-DUI-FREE</span></div></div></div>')
    shell('index.html', 'Dashboard', 'index.html', 'Hi Tom', two_col(q + steps_card, right), sub='Your question was answered by 3 lawyers. Here is where things stand.', crumbs=[("Dashboard", None)], actions='<a href="ask.html" class="btn-brand"><i class="bi bi-plus-lg"></i> Ask a question</a>')

    # ============ Notifications ============
    items = [("bi-chat-square-text-fill","ok","<strong>Amir A. Ladan</strong> answered your question.","1 hr ago","question-details.html",True),("bi-telephone-fill","","<strong>Amir A. Ladan</strong> tried to call you. Call back at (407) 555-0123.","55 min ago","connections.html",True),("bi-chat-dots-fill","","<strong>John P. Morgan</strong> also answered your question.","2 hrs ago","question-details.html",False),("bi-ticket-perforated-fill","","Your coupon <strong>KOZI-DUI-FREE</strong> is ready to use.","1 hr ago","coupons.html",False)]
    lis = ''.join(f'<li{" style=\"background:#FCFCFF\"" if u else ""}><span class="t-dot {k}" style="width:36px;height:36px;border-radius:11px;display:inline-flex;align-items:center;justify-content:center;flex:0 0 auto"><i class="bi {ic}"></i></span><div class="grow"><span style="font-size:13.5px;color:var(--ink-2)">{t}</span><span>{w}</span></div><a href="{h}" class="btn-outline btn-xs">Open</a></li>' for ic, k, t, w, h, u in items)
    shell('notifications.html', 'Notifications', 'notifications.html', 'Notifications', two_col(card('', f'<div class="card-body"><ul class="list">{lis}</ul></div>'), card('Preferences', '<div class="card-body">' + switch('Lawyer replies','SMS + email') + switch('Live chat','Push') + switch('Tips from InKozi','Monthly', False) + '</div>')))

    # ============ Ask a question ============
    opts = ''.join(f'<div class="option {"selected" if i == 1 else ""}"><i class="bi {ic}"></i><strong>{a}</strong><span>{d}</span></div>' for i, (a, ic, d) in enumerate([("Criminal Defense","bi-shield","Charges, arrests, records"),("DUI / DWI","bi-cup-straw","Traffic stops, suspensions"),("Family Law","bi-people","Custody, divorce, support"),("Personal Injury","bi-bandaid","Accidents, insurance"),("Immigration","bi-globe-americas","Visas, green cards"),("Bankruptcy","bi-bank","Debt relief"),("Real Estate","bi-house","Landlords, deposits, deeds"),("Employment","bi-briefcase","Termination, wages"),("More areas","bi-three-dots","28+ practice areas")]))
    left = card('', '<div class="card-body">' + steps(["Practice area","Your location","A few quick questions","Your question"], 2) + '<div class="section-title">Practice area</div><div class="option-grid mb-4">' + opts + '</div><div class="section-title">Your location</div><div class="row g-3 mb-4"><div class="col-md-6">' + fld('City', inp('Orlando, FL')) + '</div><div class="col-md-6">' + fld('County', select(['Orange County','Osceola County','Seminole County'], 'Orange County')) + '</div></div><div class="section-title">Kozi’s quick questions <span class="muted fw-normal">· helps route you to the right lawyer</span></div><div class="row g-3 mb-4"><div class="col-md-6">' + fld('When did this happen?', inp('', '', 'date')) + '</div><div class="col-md-6">' + fld('Have you already hired a lawyer?', select(['No','Yes'])) + '</div><div class="col-md-6">' + fld('Did you take a breath, blood or urine test?', select(['Refused','Yes','No'])) + '</div><div class="col-md-6">' + fld('Is this your first offense?', select(['Yes','No'])) + '</div></div><div class="section-title">Your question</div>' + fld('Pick a common question or write your own', select(['Write my own…','What should I do after a DUI arrest in Florida?','Can a DUI charge be reduced or dismissed?','How much does a DUI lawyer cost?','Will a DUI stay on my record?'])) + fld('Describe what happened', textarea('', 5), hint='Leave out names and case numbers. Your contact details are shared only with responding lawyers.') + '<div class="form-check mb-2"><input class="form-check-input" type="checkbox" checked id="anon"><label class="form-check-label" for="anon">Post anonymously in the public forum so others can learn</label></div><div class="form-check"><input class="form-check-input" type="checkbox" checked id="call"><label class="form-check-label" for="call">A lawyer may call me at (407) 555-7734</label></div></div>', foot='<button class="btn-outline">Back</button><button class="btn-brand" data-toast="Question posted · routing to verified DUI lawyers in Orlando">Submit question <i class="bi bi-arrow-right"></i></button>')
    right = card('Free. Always.', '<div class="card-body">' + kv([('Cost','$0 · InKozi never charges you'),('Who sees it','Verified DUI lawyers in Orlando (4)'),('Typical reply','18 minutes'),('Privacy','Secure gateway · privileged once a lawyer responds')]) + '<div class="note mt-3"><i class="bi bi-robot"></i><div><strong>Kozi</strong> screens your question so only relevant lawyers see it. InKozi does not provide legal advice.</div></div></div>') + card('Prefer to pick a lawyer?', '<div class="card-body"><ul class="list">' + ''.join(f'<li>{pav(n)}<div class="grow"><strong>{n}</strong><span>{PROV[n][1]} · {PROV[n][4]} ({PROV[n][5]})</span></div><button class="btn-outline btn-xs">Ask directly</button></li>' for n in ["Amir A. Ladan","John P. Morgan","Daniel Whitaker"]) + '</ul></div>', hint='DUI · Orlando')
    shell('ask.html', 'Ask a question', 'ask.html', 'Ask a free question', two_col(left, right), sub='Verified local lawyers will reply. Usually within minutes.')

    # ============ My questions ============
    rows = [[f'<a href="question-details.html" class="strong">{QUESTIONS[0][0]}</a><div class="muted">DUI / DWI · Orlando, FL · posted anonymously</div>', '<span class="strong">3</span>', pwho('Amir A. Ladan'), status_pill('Answered'), '<span class="muted">2 hours ago</span>', '<div class="actions"><a href="question-details.html" class="btn-outline btn-xs">Open</a></div>'],['<span class="strong">Is a first-offense DUI in Florida a felony or a misdemeanor?</span><div class="muted">DUI / DWI · Orlando, FL</div>', '<span class="strong">0</span>', '<span class="muted">Routed to 4 lawyers</span>', status_pill('Awaiting answer'), '<span class="muted">10 min ago</span>', '<div class="actions"><button class="btn-outline btn-xs">Edit</button></div>']]
    body = card('', filters('Search my questions', [('Status',['Answered','Awaiting answer','Closed'])]) + table([('Question','wide'),('Answers','num'),'First reply','Status','Asked',('','')], rows, checks=False, foot=False), hint='2 questions')
    shell('questions.html', 'My questions', 'questions.html', 'My questions', body, actions='<a href="ask.html" class="btn-brand"><i class="bi bi-plus-lg"></i> Ask a question</a>')

    # ============ Question details ============
    ans = ''
    for n, sub, txt, helpful, when in [("Amir A. Ladan","Criminal Defense & DUI · Orlando, FL · 15 years · 4.9 ★ (128)","First, take a breath. A refusal is a serious problem but it is not the end of the road. Florida's implied consent law means a refusal triggers a one-year administrative suspension, separate from criminal court. The single most important thing: you have 10 days from the arrest to request a formal review hearing with the DHSMV.",41,"9 min after"),("Maria E. Gonzalez","Criminal Defense · Orlando, FL · 4.7 ★ (72)","Agree on the 10-day deadline. If this is truly a first refusal you may be eligible to waive the hearing in exchange for immediate hardship-license eligibility.",17,"41 min after"),("John P. Morgan","DUI Defense · Orlando, FL · 4.8 ★ (96)","Request the arrest report and any dash or body camera footage as soon as possible. Footage of the stop often decides whether “drifting between lanes” holds up.",9,"2 hrs after")]:
        ans += f'<div class="lawyer-card mb-3">{pav(n)}<div class="grow"><h4>{n} {pill("ok","Verified")}</h4><div class="meta">{sub}</div><p class="quote mt-2 mb-2">{txt}</p><div class="d-flex gap-2 flex-wrap"><button class="btn-outline btn-xs"><i class="bi bi-hand-thumbs-up"></i> Helpful · {helpful}</button><span class="muted" style="font-size:12px;align-self:center">{when}</span></div></div><div class="actions-col"><button class="btn-brand btn-sm"><i class="bi bi-telephone"></i> Call</button><button class="btn-outline btn-sm"><i class="bi bi-chat-dots"></i> Live chat</button><a href="../frontend/profile.html" target="_blank" class="btn-outline btn-sm">Profile</a></div></div>'
    left = card('', f'<div class="card-body"><div class="d-flex gap-2 flex-wrap mb-3"><span class="tag">DUI / DWI</span><span class="tag">Orlando, FL</span>{status_pill("Answered")}<span class="tag">Anonymous</span></div><h2 style="font-size:20px;font-weight:800;letter-spacing:-.4px;margin-bottom:12px">Can I refuse a breathalyzer in Florida without losing my license?</h2><p class="quote">I was pulled over last night on I-4 for what the officer said was drifting between lanes. I refused the roadside exercises and the breathalyzer. He took my license and handed me a paper. I have never been in trouble before. Is my license automatically gone? Is there anything I should be doing right now?</p><span class="muted" style="font-size:12.5px">Asked 2 hours ago · 412 views</span></div>', foot='<button class="btn-outline btn-sm"><i class="bi bi-pencil"></i> Edit</button><button class="btn-outline btn-sm"><i class="bi bi-eye-slash"></i> Remove from public forum</button><button class="btn-outline btn-sm"><i class="bi bi-check2-circle"></i> Mark as resolved</button>') + card('3 lawyer answers', f'<div class="card-body">{ans}<div class="note"><i class="bi bi-info-circle-fill"></i><div>Answers are general information from independent attorneys and do not create an attorney-client relationship until you hire one.</div></div></div>', hint='verified attorneys only')
    right = card('Rate the help you got', '<div class="card-body"><div class="rating" style="font-size:22px;letter-spacing:4px">★★★★★</div>' + fld('Feedback', textarea('', 3), small='private to InKozi') + '<button class="btn-brand btn-sm w-100" data-toast="Thanks for the feedback">Send</button></div>') + card('Related questions', '<div class="card-body"><ul class="list">' + ''.join(f'<li><div class="grow"><strong>{t}</strong><span>{n} answers</span></div></li>' for t, n in [("Is a first-offense DUI in Florida a felony or a misdemeanor?",4),("How much does a DUI lawyer cost in Orlando?",6),("Can I get a hardship license after a refusal?",2)]) + '</ul></div>')
    shell('question-details.html', 'My question', 'questions.html', 'My question', two_col(left, right), crumbs=[("Dashboard","index.html"),("My questions","questions.html"),("Breathalyzer refusal",None)])

    # ============ Live chat ============
    lst = ''.join(f'<div class="chat-item {"active" if i == 0 else ""}">{pav(n) if n in PROV else "<img class=\"avatar\" src=\"assets/images/kozi-mascot.png\" alt=\"\">"}<div class="grow"><strong>{n}</strong><span>{m}</span></div><time>{t}</time></div>' for i, (n, m, t) in enumerate([("Amir A. Ladan","Chat request sent · waiting for the lawyer to accept","now"),("Kozi","Not sure what you need? Ask Kozi.","2 hrs"),("John P. Morgan","Chat ended","yesterday")]))
    msgs = '<div class="msg sys">Waiting for Amir A. Ladan to accept · usually responds in under 5 minutes</div><div class="msg me">Hi Amir, quick question about the hearing next week. Do I need to bring anything?<time>just now</time></div>'
    chat = f'<div class="card"><div class="chat"><div class="chat-list">{lst}</div><div class="chat-pane"><div class="chat-head">{pwho("Amir A. Ladan")}<div style="flex:1"></div>{pill("warn","Waiting to accept")}<button class="btn-outline btn-sm"><i class="bi bi-telephone"></i> Call instead</button></div><div class="chat-body">{msgs}</div><div class="chat-foot"><button class="icon-btn"><i class="bi bi-paperclip"></i></button><input placeholder="Type a message…"><button class="btn-brand btn-sm"><i class="bi bi-send"></i></button></div></div></div></div>'
    shell('chat.html', 'Live chat', 'chat.html', 'Live chat', chat, sub='Chat with a lawyer who replied to you, or with Kozi for guidance.')

    # ============ Lawyers who replied / connections ============
    rows = [[pwho(n), f'<span class="muted">{v}</span>', status_pill(st), f'<span class="muted">{w}</span>', f'<div class="actions"><button class="btn-brand btn-xs"><i class="bi bi-telephone"></i> Call</button><button class="btn-outline btn-xs"><i class="bi bi-chat-dots"></i> Chat</button><button class="icon-btn"><i class="bi bi-bookmark"></i></button></div>'] for n, v, st, w in [("Amir A. Ladan","Answered · called you · free consultation","Connected","1 hr ago"),("Maria E. Gonzalez","Answered","Replied","2 hrs ago"),("John P. Morgan","Answered","Replied","2 hrs ago")]]
    body = card('', table(['Lawyer',('Activity','mid'),'Status','When',('','')], rows, checks=False, foot=False), hint='your contact details were shared only with these lawyers') + '<div class="note mt-3"><i class="bi bi-shield-lock-fill"></i><div>Hire them, ask another lawyer, or walk away. Fees and agreements are always directly between you and the professional.</div></div>'
    shell('connections.html', 'Lawyers who replied', 'connections.html', 'Lawyers who replied', body)

    # ============ Saved lawyers ============
    body = '<div class="grid grid-2">' + ''.join(f'<div class="lawyer-card">{pav(n)}<div class="grow"><h4>{n} {pill("ok","Verified")}</h4><div class="meta">{PROV[n][1]} · {PROV[n][2]}, {PROV[n][3]} · {stars(PROV[n][4])} {PROV[n][4]} ({PROV[n][5]})</div><div class="muted mt-1" style="font-size:12.5px">{PROV[n][6]} · usually responds in under 5 min</div></div><div class="actions-col"><button class="btn-brand btn-sm"><i class="bi bi-telephone"></i> Call</button><a href="../frontend/profile.html" target="_blank" class="btn-outline btn-sm">Profile</a><button class="btn-outline btn-sm"><i class="bi bi-bookmark-x"></i> Remove</button></div></div>' for n in ["Amir A. Ladan","John P. Morgan","Sarah J. Connor"]) + '</div>'
    shell('saved.html', 'Saved lawyers', 'saved.html', 'Saved lawyers', body, sub='Lawyers you bookmarked from search, Q&A or the Ask KOZI app.', actions='<a href="../frontend/search.html" target="_blank" class="btn-outline"><i class="bi bi-search"></i> Find more lawyers</a>')

    # ============ Coupons ============
    body = two_col(card('Claimed coupons', '<div class="card-body"><div class="grid grid-2">' + ''.join(f'<div class="coupon-card"><div class="d-flex justify-content-between gap-2"><div><strong style="color:var(--ink)">{t}</strong><div class="muted" style="font-size:12.5px">{o}</div></div>{status_pill(st)}</div><div class="d-flex justify-content-between align-items-end mt-3"><div class="price">{p}</div><span class="code">{c}</span></div><div class="muted mt-2" style="font-size:12px">Expires {e}</div></div>' for t, o, p, c, st, e in [("Free DUI consultation","Amir A. Ladan","Free<s>$150</s>","KOZI-DUI-FREE","Redeemed","31 Dec 2026"),("10% off any bond over $5,000","Sunshine State Bail Bonds","10% off","SUNSHINE10","Active","31 Dec 2026")]) + '</div></div>'), card('Deals near you', '<div class="card-body"><ul class="list">' + ''.join(f'<li>{av(n)}<div class="grow"><strong>{t}</strong><span>{n} · {c}</span></div><button class="btn-outline btn-xs" data-toast="Coupon claimed">Claim</button></li>' for t, n, c in [("First adjustment $29","Bayshore Chiropractic","Chiropractor · Orlando"),("Expungement flat fee $499","Amir A. Ladan","Criminal Defense · Orlando"),("Half-price custody consult","Sarah J. Connor","Family Law · Miami")]) + '</ul><a href="../frontend/search.html" target="_blank" class="btn-ghost btn-sm w-100 mt-2">All deals</a></div>'))
    shell('coupons.html', 'Coupons', 'coupons.html', 'Coupons', body, sub='Offers from lawyers and local businesses on InKozi.')

    # ============ My reviews ============
    body = two_col(card('Reviews you left', '<div class="card-body"><ul class="list"><li>' + pav('John P. Morgan') + '<div class="grow"><strong>John P. Morgan ' + stars(5) + '</strong><span class="quote d-block">Fast, direct and honest about my options.</span><span>Posted 2 months ago as “Tom B.”</span></div>' + status_pill('Published') + '</li></ul></div>'), card('Leave a review', '<div class="card-body"><p class="muted" style="font-size:13px">You can review a lawyer once you have connected with them through InKozi.</p><form data-demo>' + fld('Lawyer', select(['Amir A. Ladan','Maria E. Gonzalez'])) + fld('Rating', '<div class="rating" style="font-size:22px;letter-spacing:4px">★★★★★</div>') + fld('Review', textarea('', 4)) + '<button class="btn-brand w-100">Submit review</button></form></div>'))
    shell('reviews.html', 'My reviews', 'reviews.html', 'My reviews', body)

    # ============ Settings ============
    left = card('Profile', '<div class="card-body"><form data-demo><div class="row g-3"><div class="col-md-6">' + fld('First name', inp('Tom')) + '</div><div class="col-md-6">' + fld('Last name', inp('Becker')) + '</div><div class="col-md-6">' + fld('Email', inp('tom.becker@example.com')) + '</div><div class="col-md-6">' + fld('Mobile', inp('(407) 555-7734'), small='verified') + '</div><div class="col-md-6">' + fld('City', inp('Orlando, FL')) + '</div><div class="col-md-6">' + fld('Language', select(['English','Español'])) + '</div></div></form></div>', foot='<button class="btn-brand" data-toast="Saved">Save</button>') + card('Password', '<div class="card-body"><form data-demo><div class="row g-3"><div class="col-md-4">' + fld('Current', inp('', '', 'password')) + '</div><div class="col-md-4">' + fld('New', inp('', '', 'password')) + '</div><div class="col-md-4">' + fld('Confirm', inp('', '', 'password')) + '</div></div></form></div>', foot='<button class="btn-outline" data-toast="Password updated">Update password</button>')
    right = card('Privacy', '<div class="card-body">' + switch('Post questions anonymously by default','Public forum shows “Anonymous”') + switch('Lawyers may call me','Only lawyers who responded') + switch('SMS notifications','Login codes and lawyer replies') + switch('Marketing email','Tips and news from InKozi', False) + '<button class="btn-outline btn-sm w-100 mt-3"><i class="bi bi-download"></i> Download my data</button><button class="btn-danger-soft btn-sm w-100 mt-2"><i class="bi bi-trash"></i> Delete my account</button></div>') + card('Connected sign-in', '<div class="card-body"><ul class="list"><li><span class="avatar sq soft"><i class="bi bi-google"></i></span><div class="grow"><strong>Google</strong><span>Not connected</span></div><button class="btn-outline btn-xs">Connect</button></li><li><span class="avatar sq soft"><i class="bi bi-facebook"></i></span><div class="grow"><strong>Facebook</strong><span>Not connected</span></div><button class="btn-outline btn-xs">Connect</button></li><li><span class="avatar sq soft"><i class="bi bi-phone"></i></span><div class="grow"><strong>Ask KOZI app</strong><span>iPhone · signed in</span></div>' + status_pill('Active') + '</li></ul></div>')
    shell('settings.html', 'Settings', 'settings.html', 'Settings', two_col(left, right))
