from gen_common import *

def build():
    use_admin()
    # ============ Dashboard ============
    body = stats_row([('Questions today','148','+12.4%',True,'bi-chat-square-text',[20,24,22,28,30,27,34,38,36,42]),('Avg. lawyer reply','18 min','−3 min',True,'bi-stopwatch',[26,25,24,23,22,21,20,19,18,18]),('Answer rate','94%','+1.2%',True,'bi-check2-circle',[90,91,91,92,92,93,93,93,94,94]),('Territory MRR','$96,300','+6.8%',True,'bi-graph-up-arrow',[80,82,84,86,88,90,91,93,95,96],'vs last month')])
    body += '<div class="grid grid-8-4 mb-20">' + card('Questions vs. answers', '<div class="card-body"><div class="chart-box"><canvas id="chart-inquiries"></canvas></div></div>', tools='<div class="legend"><span><i style="background:#E00A70"></i> Asked</span><span><i style="background:#4a2bd6"></i> Answered</span></div><select class="form-select form-select-sm" style="width:auto;border-radius:8px"><option>Last 30 days</option><option>Last 90 days</option><option>This year</option></select>', hint='Daily') \
        + card('Questions by practice area', '<div class="card-body"><div class="chart-box sm"><canvas id="chart-areas"></canvas></div><div class="legend mt-3 justify-content-center"><span><i style="background:#E00A70"></i> DUI / DWI 26%</span><span><i style="background:#d91d75"></i> Family 22%</span><span><i style="background:#8c1fa9"></i> Criminal 18%</span><span><i style="background:#4a2bd6"></i> Injury 14%</span><span><i style="background:#A78BFA"></i> Immigration 11%</span></div></div>') + '</div>'
    vrows = [[pwho(n), status_pill('Pending' if i else 'In review'), f'<span class="muted">{w}</span>', '<div class="actions"><a href="verification-review.html" class="btn-outline btn-xs">Review</a></div>'] for i, (n, w) in enumerate([("Elena Rodriguez","2 hours ago"),("Rachel Kim","5 hours ago"),("Laura Chen","Yesterday")])]
    activity = timeline([('bi-chat-dots-fill','','<strong>Carlos Mendez</strong> asked “Rear-ended at a red light. Insurance offered $1,800.” in <strong>Personal Injury · Tampa</strong>','40 min ago'),('bi-check-lg','ok','<strong>Amir A. Ladan</strong> answered the breathalyzer question in <strong>DUI / DWI · Orlando</strong> in 9 minutes','2 hrs ago'),('bi-send-fill','','Inquiry <strong>DUI · Orlando, FL</strong> delivered to Amir A. Ladan (rotation 1 of 4)','2 hrs ago'),('bi-pen-fill','warn','<strong>Rachel Kim</strong> signed the hosting agreement (e-signature) · awaiting approval','5 hrs ago'),('bi-ticket-perforated','','New coupon <strong>“Free DUI consultation”</strong> published by Amir A. Ladan','Yesterday'),('bi-credit-card','','Hosting renewed: <strong>Sarah J. Connor</strong> · Family Law · Miami · $45.00','Today, 06:00')])
    terr = ''.join(f'<div class="bar-row"><span class="lbl">{a} · {c}</span><div class="bar thin"><span style="width:{int((f + r) / 7 * 100)}%"></span></div><span class="val">{f + r}/7</span></div>' for a, c, s, f, r in TERR[:6])
    top = ''.join(f'<li>{pav(n)}<div class="grow"><strong>{n}</strong><span>{PROV[n][1]} · {PROV[n][2]}</span></div><div class="text-end"><strong style="font-size:13.5px;color:var(--ink)">{PROV[n][8]}</strong><div class="muted" style="font-size:12px">answers</div></div></li>' for n in ["Amir A. Ladan","Sarah J. Connor","Maria E. Gonzalez","John P. Morgan","David Kim"])
    body += '<div class="grid grid-8-4 mb-20">' + card('Verification queue', table(['Provider','Status','Submitted',('','')], vrows, checks=False, foot=False), tools='<a href="verifications.html" class="btn-ghost btn-sm">View all <i class="bi bi-arrow-right"></i></a>', hint='9 waiting · 48-hour promise') + card('Live activity', f'<div class="card-body">{activity}</div>', tools='<a href="audit-log.html" class="btn-ghost btn-sm">Audit log</a>') + '</div>'
    body += '<div class="grid grid-8-4 mb-20">' + card('Hosting revenue', '<div class="card-body"><div class="chart-box sm"><canvas id="chart-revenue"></canvas></div></div>', tools='<div class="legend"><span><i style="background:#8c1fa9"></i> $45 hosting</span><span><i style="background:#F9A8D4"></i> $375 set-up fees</span></div>', hint='$ thousands') + card('Popular territories', f'<div class="card-body">{terr}<a href="territories.html" class="btn-outline btn-sm w-100 mt-2">All territories</a></div>', hint='slots filled') + '</div>'
    body += '<div class="grid grid-4-8">' + card('Top answering lawyers', f'<div class="card-body"><ul class="list">{top}</ul></div>', hint='all time') + card('Today at a glance', '<div class="card-body"><div class="mini-stats"><div class="mini-stat"><strong>5</strong><span>Open support tickets</span></div><div class="mini-stat"><strong>3</strong><span>Reviews awaiting approval</span></div><div class="mini-stat"><strong>2</strong><span>Agreements to countersign</span></div><div class="mini-stat"><strong>1,184</strong><span>Kozi-screened inquiries (30d)</span></div></div><div class="note mt-3"><i class="bi bi-info-circle-fill"></i><div><strong>Ask KOZI app 2.4</strong> is in review with Apple. Android update went live on 12 Sep.</div></div></div>') + '</div>'
    shell('index.html', 'Dashboard', 'index.html', 'Good morning, Liza', body, sub='Here is what is happening across InKozi today, 14 September 2026.', crumbs=[("Dashboard", None)], actions='<a href="reports.html" class="btn-outline"><i class="bi bi-download"></i> Export report</a><a href="verifications.html" class="btn-brand"><i class="bi bi-patch-check"></i> Review 9 licenses</a>', charts=True)

    # ============ Reports ============
    body = '<div class="tabs"><a href="#" class="active">Overview</a><a href="#">Q&amp;A</a><a href="#">Territories</a><a href="#">Revenue</a><a href="#">Providers</a><a href="#">Statistics by state</a><a href="#">Ask KOZI app</a></div>'
    body += stats_row([('Registered users','24,810','+9.2%',True,'bi-people',[17,18,19,20,21,22,22,23,24,25]),('Questions asked','12,437','+11%',True,'bi-chat-square-text',[9,9.5,10,10.4,10.9,11.3,11.7,12,12.2,12.4],'all time · 94% answered'),('Avg. lawyer reply','18 min','−3 min',True,'bi-stopwatch',[26,25,24,23,22,21,20,19,18,18]),('Territory MRR','$96.3k','+6.8%',True,'bi-cash-stack',[80,82,84,86,88,90,91,93,95,96],'2,140 slots × $45')])
    body += '<div class="grid grid-8-4 mb-20">' + card('Growth', '<div class="card-body"><div class="chart-box"><canvas id="chart-growth"></canvas></div></div>', tools='<div class="legend"><span><i style="background:#E00A70"></i> Users</span><span><i style="background:#4a2bd6"></i> Providers</span></div>', hint='Last 12 months') + card('Funnel · last 30 days', '<div class="card-body"><div class="chart-box"><canvas id="chart-funnel"></canvas></div></div>', hint='Visited → Retained') + '</div>'
    cities = ''.join(f'<div class="bar-row"><span class="lbl">{c}, {s}</span><div class="bar thin"><span style="width:{int(n / 522 * 100)}%"></span></div><span class="val">{n}</span></div>' for c, s, n in CITIES[:6])
    body += '<div class="grid grid-3">' + card('Median first reply', '<div class="card-body"><div class="chart-box sm"><canvas id="chart-response"></canvas></div></div>', hint='minutes · 14 days') + card('Territory fill · DUI / DWI', '<div class="card-body"><div class="chart-box sm"><canvas id="chart-territory"></canvas></div></div>', hint='of 7 slots') + card('Lawyers by city', f'<div class="card-body">{cities}</div>', hint='as shown on search') + '</div>'
    shell('reports.html', 'Reports', 'reports.html', 'Reports', body, sub='Marketplace health across users, questions, territories and revenue. State statistics come from the per-state spreadsheets.', actions='<button class="btn-outline"><i class="bi bi-calendar3"></i> Last 12 months</button><button class="btn-outline"><i class="bi bi-download"></i> Export PDF</button><button class="btn-brand"><i class="bi bi-envelope"></i> Schedule email</button>', charts=True)

    # ============ Notifications ============
    items = [("bi-patch-check-fill","warn","<strong>3 verifications</strong> are within 6 hours of the 48-hour approval promise.","12 min ago","verifications.html",True),("bi-chat-square-text-fill","warn","Question in <strong>Personal Injury · Tampa</strong> has had no lawyer reply for 40 minutes.","40 min ago","questions.html",True),("bi-pen-fill","","<strong>Rachel Kim</strong> signed the hosting agreement. Countersign to activate the slot.","5 hrs ago","agreements.html",True),("bi-x-octagon-fill","bad","Hosting payment failed for <strong>Omar Haddad</strong> (Bail Bonds · Fort Lauderdale), retry 2 of 3 scheduled.","3 hrs ago","payments.html",True),("bi-pin-map-fill","","<strong>Jacksonville · Criminal Defense</strong> is full. 4 providers on the waitlist.","5 hrs ago","territories.html",True),("bi-star-fill","","New 5-star review for <strong>Sarah J. Connor</strong> awaiting approval.","Yesterday","reviews.html",False),("bi-calendar2-check-fill","ok","Demo requested by <strong>Bayshore Chiropractic</strong> via the contact form.","Yesterday","demo-requests.html",True),("bi-megaphone-fill","","Weekly digest: 186 new users, 34 new providers, $96.3k MRR.","Monday","reports.html",False)]
    lis = ''.join(f'<li{" style=\"background:#FCFCFF\"" if u else ""}><span class="t-dot {k}" style="width:36px;height:36px;border-radius:11px;display:inline-flex;align-items:center;justify-content:center;flex:0 0 auto"><i class="bi {ic}"></i></span><div class="grow"><span style="font-size:13.5px;color:var(--ink-2)">{t}</span><span>{w}</span></div>{"<span style=\"width:8px;height:8px;border-radius:50%;background:var(--primary);flex:0 0 auto\"></span>" if u else ""}<a href="{h}" class="btn-outline btn-xs">Open</a></li>' for ic, k, t, w, h, u in items)
    body = two_col(card('', f'<div class="tabs" style="padding:0 20px;margin:0"><a href="#" class="active">All <span class="n">8</span></a><a href="#">Unread <span class="n">6</span></a><a href="#">Mentions</a></div><div class="card-body" style="padding-top:8px"><ul class="list">{lis}</ul></div>'), card('Preferences', '<div class="card-body">' + switch('Verification SLA','Email and in-app') + switch('Unanswered questions','In-app after 60 minutes') + switch('Billing failures','Email') + switch('Product updates','Weekly digest', False) + '</div>'))
    shell('notifications.html', 'Notifications', 'notifications.html', 'Notifications', body, actions='<button class="btn-outline" data-toast="All notifications marked as read"><i class="bi bi-check2-all"></i> Mark all read</button>')

    # ============ Users ============
    rows = []
    for n, (c, s, ph, st, q, j, la) in USERS.items():
        email = n.lower().replace("'", '').replace(' ', '.') + '@example.com'
        rows.append([f'<a href="user-details.html" style="color:inherit">{who(n, email)}</a>', f'{c}, {s}', f'<span class="strong">{q}</span>', f'<span class="muted">{ph}</span>', status_pill(st), f'<span class="muted">{la}</span>', row_actions('user-details.html')])
    body = stats_row([('Registered users','24,810','+9.2%',True,'bi-people',[17,18,19,20,21,22,22,23,24,25]),('New this week','186','+14%',True,'bi-person-plus',[12,14,13,17,19,18,22,24,23,26]),('SMS verified','97.4%','+0.6%',True,'bi-phone',[95,95,96,96,96,97,97,97,97,97]),('Ask KOZI app users','8,920','+21%',True,'bi-phone-vibrate',[5,5.5,6,6.4,7,7.4,7.9,8.3,8.7,8.9],'iOS + Android')])
    body += card('', filters('Search name, email or mobile', [('Status',['Active','Inactive','Unverified','Suspended']),('City',[f'{c}, {s}' for c, s, _ in CITIES]),('Source',['Web','Ask KOZI iOS','Ask KOZI Android','Facebook login','Google login'])], extra='<button class="btn-outline btn-sm"><i class="bi bi-funnel"></i> More filters</button>') + table(['User','City',('Questions','num'),'Mobile','Status','Last active',('','')], rows, total='24,810', shown='1–12'))
    shell('users.html', 'Users', 'users.html', 'Users', body, sub='People seeking help. Free accounts verified by a one-time SMS code; Facebook and Google sign-in supported.', actions='<button class="btn-outline"><i class="bi bi-download"></i> Export CSV</button><button class="btn-brand" data-bs-toggle="modal" data-bs-target="#addUser"><i class="bi bi-person-plus"></i> Add user</button><div class="modal fade" id="addUser" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Add user</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><form data-demo><div class="modal-body"><div class="row g-3"><div class="col-6"><div class="fld mb-0"><label>First name</label><input class="form-control" placeholder="Jane"></div></div><div class="col-6"><div class="fld mb-0"><label>Last name</label><input class="form-control" placeholder="Doe"></div></div><div class="col-12"><div class="fld mb-0"><label>Email</label><input class="form-control" type="email" placeholder="jane@example.com"></div></div><div class="col-12"><div class="fld mb-0"><label>Mobile</label><input class="form-control" placeholder="(407) 555-0123"></div></div><div class="col-12"><div class="fld mb-0"><label>City</label><input class="form-control" placeholder="Orlando, FL"></div></div><div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" checked id="au1"><label class="form-check-label" for="au1">Send SMS verification code now</label></div></div></div></div><div class="modal-footer"><button type="button" class="btn-ghost" data-bs-dismiss="modal">Cancel</button><button class="btn-brand">Create user</button></div></form></div></div></div>')

    # ============ User details ============
    hero = f'<div class="card mb-20"><div class="card-body"><div class="profile-hero">{av("Tom Becker", cls="xl")}<div><h2>Tom Becker {status_pill("Active")}</h2><div class="meta"><span><i class="bi bi-envelope"></i> tom.becker@example.com</span><span><i class="bi bi-phone"></i> +1 (407) ••• 7734 <i class="bi bi-patch-check-fill text-success"></i></span><span><i class="bi bi-geo-alt"></i> Orlando, FL</span><span><i class="bi bi-calendar3"></i> Joined 14 Sep 2026 · Ask KOZI iOS</span></div></div><div class="spacer"></div><div class="page-actions"><button class="btn-outline"><i class="bi bi-envelope"></i> Message</button><button class="btn-outline"><i class="bi bi-key"></i> Reset password</button><button class="btn-danger-soft"><i class="bi bi-slash-circle"></i> Suspend</button></div></div></div></div>'
    qrows = [[f'<a href="question-details.html" class="strong">{QUESTIONS[0][0]}</a><div class="muted">DUI / DWI · Orlando, FL · posted anonymously</div>', status_pill('Answered'), '<span class="strong">3</span>', '<span class="muted">412</span>', '<span class="muted">2 hours ago</span>']]
    left = card('Questions', table([('Question','wide'),'Status',('Answers','num'),('Views','num'),'Asked'], qrows, checks=False, foot=False), hint='1') \
        + card('Inquiries & connections', table([('Inquiry','wide'),'Routed to','Status','When'], [['<span class="strong">DUI · Orlando, FL</span><div class="muted">Kozi intake: first offense · refused breath test · Orange County</div>', pwho('Amir A. Ladan','Rotation 1 of 4'), status_pill('Connected'), '<span class="muted">2 hrs ago</span>']], checks=False, foot=False)) \
        + card('Coupon requests', table([('Coupon','wide'),'From','Status','When'], [['<span class="strong">Free DUI consultation</span><div class="muted">Code KOZI-DUI-FREE</div>', pwho('Amir A. Ladan'), status_pill('Redeemed'), '<span class="muted">1 hr ago</span>']], checks=False, foot=False)) \
        + card('Activity', f'<div class="card-body">{timeline([("bi-telephone-fill","ok","<strong>Amir A. Ladan</strong> called Tom (Call Now from profile)","1 hr ago"),("bi-chat-dots-fill","","Asked a question in <strong>DUI / DWI</strong>, posted anonymously to the public forum","2 hrs ago"),("bi-robot","","Completed the <strong>Kozi intake</strong> questionnaire in 1m 12s","2 hrs ago"),("bi-phone-fill","ok","Mobile number verified by SMS code","2 hrs ago"),("bi-person-plus-fill","","Account created from the <strong>Ask KOZI</strong> iOS app","2 hrs ago")])}</div>')
    right = card('Details', '<div class="card-body">' + kv([('User ID','<span class="mono">usr_8F3A22C1</span>'),('Account type','Person seeking help'),('Language','English'),('Sign-in','Mobile + SMS code'),('Marketing email','Opted in'),('SMS','Login codes only'),('Device','iPhone · Ask KOZI 2.3')]) + '</div>') \
        + card('Saved lawyers', '<div class="card-body"><ul class="list">' + ''.join(f'<li>{pav(n)}<div class="grow"><strong>{n}</strong><span>{PROV[n][1]}</span></div><a href="provider-details.html" class="icon-btn"><i class="bi bi-arrow-up-right"></i></a></li>' for n in ["Amir A. Ladan","John P. Morgan"]) + '</ul></div>') \
        + card('Privacy', '<div class="card-body"><div class="note"><i class="bi bi-shield-lock-fill"></i><div>Contact details are shared only with the providers who responded. Public Q&amp;A shows this user as <strong>Anonymous</strong>.</div></div><button class="btn-outline btn-sm w-100 mt-3"><i class="bi bi-download"></i> Export personal data</button><button class="btn-danger-soft btn-sm w-100 mt-2"><i class="bi bi-trash"></i> Delete account</button></div>')
    shell('user-details.html', 'Tom Becker', 'users.html', 'User profile', hero + two_col(left, right), crumbs=[("Dashboard","index.html"),("Users","users.html"),("Tom Becker",None)])

    # ============ Providers ============
    rows = []
    terrs = {"Amir A. Ladan":2,"Sarah J. Connor":2,"Maria E. Gonzalez":2,"Michael T. Ross":1,"Jessica Pearson":1,"John P. Morgan":1,"David Kim":1,"Harvey Specter":1,"Elena Rodriguez":0,"Rachel Kim":0,"Omar Haddad":1,"Laura Chen":1,"Daniel Whitaker":1}
    types = {"Omar Haddad":"Bail agent","Laura Chen":"Chiropractor"}
    for n, (img, hl, c, s, r, rv, ph, st, ans, em) in PROV.items():
        rows.append([f'<a href="provider-details.html" style="color:inherit">{who(n, em, img)}</a>', f'<span class="tag">{types.get(n, "Lawyer")}</span>', hl, f'{c}, {s}', f'<span class="strong">{terrs[n]}</span>', (stars(r) + f' <span class="muted">{r} ({rv})</span>') if rv else '<span class="muted">—</span>', status_pill(st), row_actions('provider-details.html')])
    body = stats_row([('Providers','1,842','+34',True,'bi-briefcase',[16,16.5,17,17.2,17.5,17.8,18,18.2,18.3,18.4],'lawyers, bail agents, chiropractors'),('Verified','1,796','97.5%',True,'bi-patch-check',[15.5,16,16.4,16.8,17,17.3,17.5,17.7,17.8,17.9],'license, background & standing'),('Avg. rating','4.8','+0.1',True,'bi-star',[4.6,4.6,4.7,4.7,4.7,4.8,4.8,4.8,4.8,4.8]),('Past due hosting','9','+2',False,'bi-exclamation-circle',[4,5,5,6,6,7,7,8,8,9])])
    body += card('', filters('Search provider, firm or license number', [('Type',['Lawyer','Bail agent','Chiropractor']),('Practice area',AREAS[:12]),('City',[f'{c}, {s}' for c, s, _ in CITIES]),('Status',['Verified','Pending','Past due','Suspended']),('Flags',['Featured','Show on homepage','Preferred'])], extra='<button class="btn-outline btn-sm"><i class="bi bi-sliders"></i> Columns</button>') + table(['Provider','Type',('Practice areas','mid'),'City',('Territories','num'),'Rating','Status',('','')], rows, total='1,842', shown='1–13'))
    shell('providers.html', 'Providers', 'providers.html', 'Providers', body, sub='Lawyers, bail agents and chiropractors holding territory slots. 28+ practice areas.', actions='<button class="btn-outline"><i class="bi bi-download"></i> Export</button><a href="verifications.html" class="btn-outline"><i class="bi bi-patch-check"></i> Verification queue</a><button class="btn-brand"><i class="bi bi-plus-lg"></i> Add provider</button>')

    # ============ Provider details ============
    hero = f'''<div class="card mb-20"><div class="card-body"><div class="profile-hero"><img class="avatar xl" src="assets/images/lawyer-1.jpg" alt=""><div><h2>Amir A. Ladan {pill('ok','Verified InKozi Provider')} {pill('brand','Featured')} {pill('info','On homepage')}</h2><div class="meta"><span><i class="bi bi-briefcase"></i> Criminal Defense • DUI / DWI</span><span><i class="bi bi-geo-alt"></i> 111 N Orange Ave, Ste 800, Orlando, FL 32801</span><span><i class="bi bi-telephone"></i> (407) 555-0123</span><span><i class="bi bi-award"></i> FL Bar #0123456</span><span><i class="bi bi-link-45deg"></i> inkozi.com/best-dui-lawyer/amir-a-ladan</span></div></div><div class="spacer"></div><div class="page-actions"><a href="../frontend/profile.html" class="btn-outline" target="_blank"><i class="bi bi-box-arrow-up-right"></i> Public profile</a><a href="../provider/index.html" class="btn-outline" target="_blank"><i class="bi bi-person-badge"></i> Log in as</a><button class="btn-brand"><i class="bi bi-pencil"></i> Edit profile</button></div></div><div class="mini-stats mt-4"><div class="mini-stat"><strong>4.9</strong><span>Rating · 128 reviews</span></div><div class="mini-stat"><strong>15+</strong><span>Years experience</span></div><div class="mini-stat"><strong>500+</strong><span>Cases won</span></div><div class="mini-stat"><strong>10.0</strong><span>Avvo rating · Superb</span></div></div></div></div>'''
    tabs = '<div class="tabs"><a href="#" class="active">Overview</a><a href="#">Reviews <span class="n">128</span></a><a href="#">Practice areas <span class="n">5</span></a><a href="#">Q&amp;A <span class="n">312</span></a><a href="#">Photos &amp; videos <span class="n">14</span></a><a href="#">Territories <span class="n">2</span></a><a href="#">Coupons <span class="n">2</span></a><a href="#">Billing</a><a href="#">Documents</a></div>'
    about = card('Public profile content', '<div class="card-body">' + fld('Headline', inp('Criminal Defense • DUI / DWI')) + fld('Short bio', textarea('Former prosecutor with over 15 years of experience defending clients against DUI and criminal charges.', 2), small='shown on search cards') + fld('About', textarea('Amir A. Ladan is a dedicated criminal defense attorney based in Orlando, Florida, with over 15 years of experience. He focuses his practice on DUI / DWI defense and works tirelessly to protect your rights and achieve the best possible outcome.', 4)) + '<div class="row g-3"><div class="col-md-6">' + fld('Highlights', '<div class="d-flex flex-wrap gap-2">' + ''.join(f'<span class="chip active">{x} <i class="bi bi-x"></i></span>' for x in ["Former Prosecutor","Free Initial Consultation","Aggressive Representation","Payment Plans Available","Available 24/7","Se Habla Español"]) + '<span class="chip"><i class="bi bi-plus"></i> Add</span></div>', small='feature list') + '</div><div class="col-md-6">' + fld('Practice areas', '<div class="d-flex flex-wrap gap-2">' + ''.join(f'<span class="chip active">{x} <i class="bi bi-x"></i></span>' for x in ["DUI / DWI","Criminal Defense","Traffic Violations","Drug Crimes","Expungements"]) + '<span class="chip"><i class="bi bi-plus"></i> Add</span></div>') + '</div><div class="col-md-4">' + fld('Languages', inp('English, Spanish')) + '</div><div class="col-md-4">' + fld('Payment options', inp('Credit Cards, Cash, Financing Options')) + '</div><div class="col-md-4">' + fld('Typical response', select(['Under 5 minutes','Under 15 minutes','Under 1 hour','Same day'], 'Under 5 minutes')) + '</div></div>' + switch('Featured provider','Shown first in search results for the territory') + switch('Show on homepage','Included in “Top Rated Lawyers”') + switch('Preferred lawyer','Fallback recipient when a territory has no provider', False) + '</div>', foot='<button class="btn-ghost">Discard</button><button class="btn-brand" data-toast="Profile updated">Save profile</button>')
    faq = card('Profile FAQ', '<div class="card-body"><ul class="list">' + ''.join(f'<li><span class="avatar sq soft"><i class="bi bi-question-lg"></i></span><div class="grow"><strong>{q}</strong><span>{a}</span></div><button class="icon-btn"><i class="bi bi-pencil"></i></button></li>' for q, a in [("What should I do after a DUI arrest in Florida?","Act quickly and contact a qualified DUI attorney…"),("Can a DUI charge be reduced or dismissed?","Yes, in many cases…"),("How much does a DUI lawyer cost?","Costs vary; Amir offers a free initial consultation…"),("Will a DUI stay on my record?","In Florida, DUI convictions generally cannot be expunged…")]) + '</ul></div>', tools='<a href="default-questions.html" class="btn-outline btn-sm"><i class="bi bi-list-check"></i> Default questions</a>', hint='4 shown on profile')
    reviews = card('Latest reviews', '<div class="card-body"><ul class="list">' + ''.join(f'<li>{av(n)}<div class="grow"><strong>{n} {stars(5)}</strong><span class="quote d-block">{t}</span><span>{w}</span></div>{status_pill("Published")}</li>' for n, t, w in [("Jasmine R.","Amir was amazing! He explained everything clearly and got my case dismissed. Highly recommend!","2 weeks ago"),("Michael T.","Professional, responsive, and truly cared about my case. Best DUI lawyer in Orlando.","1 month ago"),("David L.","Great communication and very knowledgeable. Case outcome was better than I expected.","2 months ago")]) + '</ul></div>', tools='<a href="reviews.html" class="btn-ghost btn-sm">All 128 reviews</a>')
    media = card('Photos & videos', '<div class="card-body"><div class="grid grid-4" style="gap:10px"><div class="cover" style="padding:26px 10px"><i class="bi bi-play-circle-fill"></i>Introduction video<div style="font-size:11.5px">1:42 · “Watch Introduction”</div></div>' + ''.join(f'<div class="cover" style="padding:26px 10px"><i class="bi bi-image"></i>{x}</div>' for x in ["Office exterior","Reception","Team"]) + '</div></div>', tools='<button class="btn-outline btn-sm"><i class="bi bi-upload"></i> Upload</button>', hint='14 items')
    right = card('Territories', '<div class="card-body"><ul class="list"><li><span class="avatar sq soft"><i class="bi bi-pin-map-fill"></i></span><div class="grow"><strong>DUI / DWI · Orlando, FL</strong><span>Slot 1 of 7 · first in territory · since Jan 2025</span></div>' + status_pill('Active') + '</li><li><span class="avatar sq soft"><i class="bi bi-pin-map-fill"></i></span><div class="grow"><strong>Criminal Defense · Orlando, FL</strong><span>Slot 2 of 7 · since Mar 2026</span></div>' + status_pill('Active') + '</li></ul></div>', tools='<a href="territory-details.html" class="btn-ghost btn-sm">Manage</a>') \
        + card('Hosting', '<div class="card-body">' + kv([('Plan','Territory Hosting · $45 / mo per territory'),('Territories','2 · $90.00 / month'),('Set-up fees','2 × $375 paid'),('Next renewal','1 Oct 2026 · 30-day cycle'),('Card','Mastercard •• 8810'),('Status',status_pill('Paid'))]) + '</div>', tools='<a href="payments.html" class="btn-ghost btn-sm">Invoices</a>') \
        + card('Verification & agreement', '<div class="card-body"><div class="doc mb-2"><span class="d-icon"><i class="bi bi-file-earmark-pdf-fill"></i></span><div class="grow"><strong>FL-bar-card.pdf</strong><span>Verified by Liza S. · 4 Jan 2025</span></div><a href="#" class="icon-btn"><i class="bi bi-download"></i></a></div><div class="doc mb-3"><span class="d-icon"><i class="bi bi-pen-fill"></i></span><div class="grow"><strong>Hosting agreement · signed</strong><span>e-signed 4 Jan 2025 · countersigned</span></div><a href="agreements.html" class="icon-btn"><i class="bi bi-eye"></i></a></div>' + kv([('License','FL Bar #0123456 · verified'),('Certifications','Board certified · verified'),('Background check','Clear · 4 Jan 2025'),('Good standing','Yes · re-checked 1 Sep 2026')]) + '</div>') \
        + card('Partner connections', '<div class="card-body"><ul class="list"><li>' + av('Bayshore Chiropractic') + '<div class="grow"><strong>Bayshore Chiropractic</strong><span>Personal-injury leads forwarded · ad on profile</span></div>' + status_pill('Active') + '</li></ul><a href="connections.html" class="btn-outline btn-sm w-100 mt-3">Manage connections</a></div>') \
        + card('Contact & office', '<div class="card-body">' + kv([('Work email','amir@ladanlaw.com'),('Phone','(407) 555-0123 · Call Now enabled'),('Live chat','Enabled · responds in under 5 min'),('Office','111 N Orange Ave, Ste 800, Orlando, FL 32801'),('Social','Facebook, Instagram, LinkedIn, YouTube')]) + '</div>')
    shell('provider-details.html', 'Amir A. Ladan', 'providers.html', 'Provider profile', hero + tabs + two_col(about + faq + reviews + media, right), crumbs=[("Dashboard","index.html"),("Providers","providers.html"),("Amir A. Ladan",None)])

    # ============ Verifications ============
    apps = [("Elena Rodriguez","Immigration · Austin, TX","TX 24098765","Pending","2 hrs ago","46h"),("Rachel Kim","DUI / DWI · Tampa, FL","0456789","In review","5 hrs ago","43h"),("Laura Chen","Chiropractic · Orlando, FL","CH 11820","Pending","Yesterday","27h"),("Daniel Whitaker","Traffic Violations · Orlando, FL","0619944","Pending","Yesterday","25h"),("Harvey Specter","Personal Injury · Miami, FL","0287765","Needs info","2 days ago","9h"),("Omar Haddad","Bail Bonds · Fort Lauderdale, FL","BA 55120","In review","2 days ago","4h"),("Jessica Pearson","Real Estate · Jacksonville, FL","0700231","Approved","Last week","—"),("David Kim","Bankruptcy · Los Angeles, CA","CA 312455","Approved","Last week","—"),("Michael T. Ross","Corporate Law · Tampa, FL","0234567","Approved","2 weeks ago","—")]
    rows = [[pwho(n, sub), f'<span class="mono">{bar}</span>', '<span class="tag"><i class="bi bi-file-earmark-pdf"></i> PDF</span>' if i % 3 else '<span class="tag"><i class="bi bi-image"></i> JPG</span>', status_pill('Signed') if i != 4 else status_pill('Unsigned'), status_pill(st) if st != 'Needs info' else pill('bad','Needs info'), f'<span class="muted">{w}</span>', f'<span class="strong">{sla}</span>', '<div class="actions"><a href="verification-review.html" class="btn-brand btn-xs">Review</a></div>'] for i, (n, sub, bar, st, w, sla) in enumerate(apps)]
    body = stats_row([('Waiting','9','+2 today',False,'bi-hourglass-split',[5,6,6,7,7,8,8,8,9,9],''),('Median time to approve','31h','−4h',True,'bi-stopwatch',[42,40,39,38,36,35,34,33,32,31],'promise: 48 hours'),('Approved this month','38','+9',True,'bi-patch-check',[20,22,24,26,28,30,32,34,36,38]),('Rejected','2','5%',True,'bi-x-circle',[3,3,3,2,2,2,2,2,2,2],'rejection rate')])
    body += '<div class="note warn mb-20"><i class="bi bi-exclamation-triangle-fill"></i><div><strong>3 applications are within 6 hours of the 48-hour approval promise.</strong> Each check covers license, certifications, background, good standing and a signed hosting agreement.</div></div>'
    body += card('', filters('Search provider or license number', [('Status',['Pending','In review','Needs info','Approved','Rejected']),('State',STATES),('Type',['Lawyer','Bail agent','Chiropractor','Affiliate'])], chips=['All 9','SLA at risk 3','Assigned to me 4']) + table(['Applicant','License #','Document','Agreement','Status','Submitted',('SLA left','num'),('','')], rows, total='9', shown='1–9'))
    shell('verifications.html', 'Verification queue', 'verifications.html', 'Verification queue', body, sub='License, certification, background and standing checks. Providers go live within 48 hours and are not billed until approved.', actions='<button class="btn-outline"><i class="bi bi-people"></i> Assign reviewers</button><a href="verification-review.html" class="btn-brand"><i class="bi bi-play-fill"></i> Start reviewing</a>')

    # ============ Verification review ============
    left = card('Submitted documents', '<div class="card-body"><div class="grid grid-2"><div class="doc"><span class="d-icon"><i class="bi bi-file-earmark-pdf-fill"></i></span><div class="grow"><strong>FL-bar-card.pdf</strong><span>412 KB · uploaded 5 hrs ago</span></div><a href="#" class="icon-btn"><i class="bi bi-eye"></i></a></div><div class="doc"><span class="d-icon img"><i class="bi bi-image-fill"></i></span><div class="grow"><strong>bar-profile-screenshot.jpg</strong><span>1.1 MB · uploaded 5 hrs ago</span></div><a href="#" class="icon-btn"><i class="bi bi-eye"></i></a></div><div class="doc"><span class="d-icon"><i class="bi bi-pen-fill"></i></span><div class="grow"><strong>hosting-agreement-signed.pdf</strong><span>e-signed 14 Sep 2026, 00:20</span></div><a href="agreements.html" class="icon-btn"><i class="bi bi-eye"></i></a></div></div><div class="mt-3" style="border:1px solid var(--line);border-radius:12px;background:var(--soft);height:320px;display:flex;align-items:center;justify-content:center;color:var(--faint);flex-direction:column;gap:8px"><i class="bi bi-file-earmark-pdf" style="font-size:40px"></i><span>Document preview · FL-bar-card.pdf</span></div></div>') \
        + card('Vetting checklist', '<div class="card-body">' + switch('License verified','The Florida Bar · #0456789 · admitted 2014') + switch('Certifications confirmed','Board certification in criminal trial law') + switch('Background check','Clear · run 14 Sep 2026') + switch('Good standing','No public discipline on record') + switch('Hosting agreement signed','e-signature captured, PDF stored') + switch('Firm email domain verified','rachel@kimdefense.com · MX records ok', False) + switch('Mobile verified by SMS','+1 (813) ••• 2210') + '</div>')
    right = card('Applicant', '<div class="card-body">' + who('Rachel Kim','Kim Defense, PLLC', cls='lg') + '<div class="mt-3">' + kv([('Provider type','Lawyer'),('Practice area','DUI / DWI'),('Territory requested','Tampa, FL · slot 4 of 7'),('Slot hold','<span class="pill warn">23h left</span>'),('License','0456789 · Florida'),('Years in practice','5 – 10'),('Work email','rachel@kimdefense.com'),('Submitted','14 Sep 2026, 00:14'),('Approval SLA','<span class="pill warn">43h left</span>')]) + '</div></div>') \
        + card('Decision', '<div class="card-body">' + fld('Internal note', textarea('', 3), small='visible to staff only') + fld('Message to applicant', select(['Approved — welcome email + custom URL live','Need a clearer copy of the bar card','License number does not match','Custom message…'])) + '<div class="note"><i class="bi bi-info-circle-fill"></i><div>Approving charges the <strong>$375 set-up fee</strong>, starts <strong>$45 / month</strong> hosting for Tampa · DUI / DWI and countersigns the agreement. Profile and SEO URL go live immediately.</div></div></div>', foot='<button class="btn-danger-soft" data-toast="Application rejected"><i class="bi bi-x-lg"></i> Reject</button><button class="btn-outline" data-toast="Request sent to applicant"><i class="bi bi-question-circle"></i> Request info</button><button class="btn-brand" data-toast="Rachel Kim approved · slot 4 activated"><i class="bi bi-check-lg"></i> Approve &amp; go live</button>') \
        + card('Reviewer', '<div class="card-body"><div class="who"><span class="avatar">LS</span><div><strong>Liza Seale</strong><span>Assigned 1 hr ago</span></div></div><button class="btn-outline btn-sm w-100 mt-3"><i class="bi bi-arrow-left-right"></i> Reassign</button></div>')
    shell('verification-review.html', 'Review · Rachel Kim', 'verifications.html', 'Review application', two_col(left, right), sub='Application #VR-2026-0412 · 2 of 9 in the queue', crumbs=[("Dashboard","index.html"),("Verifications","verifications.html"),("Rachel Kim",None)], actions='<a href="verifications.html" class="btn-outline"><i class="bi bi-arrow-left"></i> Queue</a><button class="btn-outline">Skip <i class="bi bi-arrow-right"></i></button>')

    # ============ Territories ============
    rows = []
    firsts = ["Amir A. Ladan","Harvey Specter","Sarah J. Connor","Jessica Pearson","Elena Rodriguez","David Kim","Michael T. Ross","—","Amir A. Ladan","Sarah J. Connor","Maria E. Gonzalez","Maria E. Gonzalez"]
    for i, (a, c, s, f, r) in enumerate(TERR):
        taken = f + r; left = 7 - taken
        st = pill('bad','Full') if left == 0 else (pill('warn', f'{left} left') if left <= 2 else pill('ok', f'{left} open'))
        held = ' <span class="tag"><i class="bi bi-hourglass-split"></i> 1 reserved</span>' if r else ''
        rows.append([f'<a href="territory-details.html" class="strong">{a}</a><div class="muted">{c}, {s}</div>', f'<div class="bar-row mb-0"><div class="bar thin" style="min-width:90px"><span style="width:{int(taken / 7 * 100)}%"></span></div><span class="val">{taken}/7</span></div>', st + held, f'<span class="muted">{firsts[i]}</span>', f'<span class="strong">${f * 45}</span>', f'<span class="muted">{[2,0,0,4,0,3,0,0,1,2,0,0][i]}</span>', '<div class="actions"><a href="territory-details.html" class="icon-btn"><i class="bi bi-eye"></i></a><button class="icon-btn"><i class="bi bi-pencil"></i></button></div>'])
    body = stats_row([('Territories','312','+8',True,'bi-pin-map',[280,284,288,291,295,298,302,306,309,312],'category × city'),('Slots filled','2,140','64%',True,'bi-grid-3x3-gap',[1800,1840,1880,1920,1960,2000,2040,2080,2110,2140],'of 2,184 · max 7 each'),('Full territories','41','+3',True,'bi-lock',[30,31,33,34,35,36,38,39,40,41]),('Waitlist','86','+11',True,'bi-people',[50,55,58,62,66,70,74,78,82,86])])
    body += card('Fill by city · DUI / DWI', '<div class="card-body"><div class="chart-box sm"><canvas id="chart-territory"></canvas></div></div>', tools='<div class="legend"><span><i style="background:#8c1fa9"></i> Filled</span><span><i style="background:#E2E8F0"></i> Open</span></div>', cls='mb-20')
    body += card('', filters('Search practice area, city or county', [('Practice area',AREAS[:12]),('State',STATES),('City',[f'{c}, {s}' for c, s, _ in CITIES]),('Type',['Lawyer (city)','Bail bonds (county)','Chiropractor (city)'])], chips=['All','Open slots','Full','Reserved','With waitlist']) + table([('Territory','mid'),'Fill','Availability','First provider',('MRR','num'),('Waitlist','num'),('','')], rows, checks=False, total='312', shown='1–12'))
    shell('territories.html', 'Territories', 'territories.html', 'Territories', body, sub='Each practice category × city holds a maximum of seven providers, one slot per firm. Bail-bonds territories are per county. First in receives every inquiry until slot two fills.', actions='<button class="btn-outline"><i class="bi bi-map"></i> Map view</button><button class="btn-outline"><i class="bi bi-sliders"></i> Slot defaults</button><button class="btn-brand"><i class="bi bi-plus-lg"></i> Open a territory</button>', charts=True)

    # ============ Territory details ============
    slots = ''
    for i, (n, since) in enumerate([("Amir A. Ladan","Jan 2025"),("John P. Morgan","Apr 2025"),("Maria E. Gonzalez","Sep 2025"),("Daniel Whitaker","Feb 2026")]):
        slots += f'<div class="slot">{pav(n)}<strong>{n}</strong><span>Slot {i + 1} · since {since}</span>{"<span class=\"tag\" style=\"font-size:10.5px\">First in</span>" if i == 0 else ""}</div>'
    slots += '<div class="slot held"><span class="avatar soft"><i class="bi bi-hourglass-split"></i></span><strong>Reserved</strong><span>Rachel Kim · 23h left</span></div><div class="slot open"><span class="plus"><i class="bi bi-plus-lg"></i></span><strong>Open slot</strong><span>Slot 6</span></div><div class="slot open"><span class="plus"><i class="bi bi-plus-lg"></i></span><strong>Open slot</strong><span>Slot 7</span></div>'
    hero = f'<div class="card mb-20"><div class="card-body"><div class="profile-hero"><span class="avatar xl soft"><i class="bi bi-pin-map-fill"></i></span><div><h2>DUI / DWI · Orlando, FL {pill("warn","2 left")}</h2><div class="meta"><span><i class="bi bi-people"></i> 4 of 7 filled · 1 reserved</span><span><i class="bi bi-cash-stack"></i> $180 MRR · 4 × $45</span><span><i class="bi bi-chat-square-text"></i> 412 questions this year</span><span><i class="bi bi-stopwatch"></i> 11 min median reply</span><span><i class="bi bi-arrow-repeat"></i> Rotation: even, 4 providers · last used slot 1</span></div></div><div class="spacer"></div><div class="page-actions"><a href="../frontend/search.html" target="_blank" class="btn-outline"><i class="bi bi-box-arrow-up-right"></i> Search page</a><button class="btn-outline"><i class="bi bi-pause-circle"></i> Pause new claims</button><button class="btn-brand"><i class="bi bi-person-plus"></i> Assign provider</button></div></div></div></div>'
    body = hero + card('Slots', f'<div class="card-body"><div class="slots">{slots}</div></div>', hint='7 max · one per firm', tools='<span class="muted" style="font-size:12.5px">Slot price $375 set-up + $45 / mo</span>')
    inq = table([('Inquiry','wide'),'Kozi screening','Rotation','Routed to','Status','Received'], [['<span class="strong">DUI · Orlando, FL</span><div class="muted">Tom Becker · refused breath test · Orange County</div>', pill('ok','Relevant · 92'), '<span class="muted">1 of 4</span>', pwho('Amir A. Ladan','Slot 1'), status_pill('Connected'), '<span class="muted">2 hrs ago</span>'],['<span class="strong">DUI · Orlando, FL</span><div class="muted">Lucas Nguyen · first offense · court date 22 Sep</div>', pill('ok','Relevant · 88'), '<span class="muted">2 of 4</span>', pwho('John P. Morgan','Slot 2'), status_pill('Retained'), '<span class="muted">3 days ago</span>'],['<span class="strong">DUI · Orlando, FL</span><div class="muted">Hannah Reed · cost question only</div>', pill('warn','Low intent · 41'), '<span class="muted">3 of 4</span>', pwho('Maria E. Gonzalez','Slot 3'), status_pill('Waiting'), '<span class="muted">1 week ago</span>'],['<span class="strong">DUI · Orlando, FL</span><div class="muted">Anonymous · out-of-state license</div>', pill('bad','Filtered · 12'), '<span class="muted">—</span>', '<span class="muted">Not delivered</span>', status_pill('Closed'), '<span class="muted">1 week ago</span>']], checks=False, foot=False)
    wl = '<ul class="list">' + ''.join(f'<li>{av(n)}<div class="grow"><strong>{n}</strong><span>{w}</span></div><button class="btn-outline btn-xs">Offer slot</button></li>' for n, w in [("Omar Haddad","Joined waitlist 3 days ago"),("Grace Lee","Joined waitlist 1 week ago")]) + '</ul>'
    body += '<div class="grid grid-8-4 mt-4"><div>' + card('Recent inquiries', inq, tools='<a href="inquiries.html" class="btn-ghost btn-sm">All inquiries</a>', hint='fair rotation') + '</div><div>' + card('Waitlist', f'<div class="card-body">{wl}</div>', hint='2') + card('Coverage', '<div class="card-body"><img src="assets/images/map-orlando.png" alt="Orlando coverage map" style="border-radius:12px;width:100%;display:block">' + kv([('County','Orange County'),('Radius','25 miles from downtown'),('ZIP codes','62 covered'),('Pricing','$375 set-up + $45 / month'),('Search page','DUI Lawyers in Orlando, FL · 152 results')]) + '</div>') + '</div></div>'
    shell('territory-details.html', 'DUI / DWI · Orlando', 'territories.html', 'Territory', body, crumbs=[("Dashboard","index.html"),("Territories","territories.html"),("DUI / DWI · Orlando",None)])

    # ============ Inquiries ============
    data = [("DUI · Orlando, FL","Tom Becker","refused breath test · Orange County",92,"Amir A. Ladan","Connected","2 hrs ago"),("Family Law · Tampa, FL","Aisha Khan","custody relocation · 50/50 order",89,"Sarah J. Connor","Retained","5 hrs ago"),("Personal Injury · Tampa, FL","Carlos Mendez","rear-ended · $4k damage · chiropractor visits",84,"Maria E. Gonzalez","Waiting","40 min ago"),("Immigration · Austin, TX","Priya Natarajan","H-1B layoff · 60-day grace period",90,"Elena Rodriguez","New","Yesterday"),("Bankruptcy · Los Angeles, CA","Kevin O'Neil","Chapter 7 · $38k private loans",86,"David Kim","Connected","2 days ago"),("DUI · Orlando, FL","Lucas Nguyen","first offense · court date 22 Sep",88,"John P. Morgan","Retained","3 days ago"),("Bail Bonds · Fort Lauderdale, FL","Sofia Martins","bail set at $25k · misdemeanor",77,"—","New","Yesterday")]
    rows = [[f'<span class="strong">{t}</span><div class="muted">{d}</div>', uwho(u), pill('ok' if sc >= 80 else 'warn', f'{sc}'), pwho(p) if p != '—' else '<span class="muted">No provider · sent to preferred fallback</span>', status_pill(st), f'<span class="muted">{w}</span>', '<div class="actions"><button class="icon-btn"><i class="bi bi-eye"></i></button><button class="icon-btn" data-bs-toggle="tooltip" title="Re-route"><i class="bi bi-arrow-repeat"></i></button></div>'] for t, u, d, sc, p, st, w in data]
    body = stats_row([('Inquiries this month','1,184','+18%',True,'bi-send',[70,74,80,86,90,96,100,108,112,118]),('Kozi-screened out','23%','−2%',True,'bi-robot',[27,27,26,26,25,25,24,24,23,23],'noise filtered before delivery'),('Connected','61%','+3.4%',True,'bi-link-45deg',[54,55,56,57,58,58,59,60,60,61]),('Retained','24%','+1.1%',True,'bi-briefcase',[20,21,21,22,22,23,23,23,24,24])])
    body += card('', filters('Search inquiries', [('Status',['New','Connected','Waiting','Retained','Closed']),('Practice area',AREAS[:12]),('City',[f'{c}, {s}' for c, s, _ in CITIES]),('Delivery',['Rotation','Direct to lawyer','Partner copy (chiropractor)','Fallback'])], extra='<button class="btn-outline btn-sm"><i class="bi bi-calendar3"></i> Last 30 days</button>') + table([('Inquiry','wide'),'From',('Kozi score','num'),'Routed to','Status','Received',('','')], rows, total='1,184', shown='1–7'))
    shell('inquiries.html', 'Inquiries', 'inquiries.html', 'Inquiries', body, sub='AI-screened, location-matched leads delivered instantly to the providers in a territory. Personal-injury leads are also copied to a connected chiropractor.', actions='<button class="btn-outline"><i class="bi bi-download"></i> Export</button><a href="kozi-intake.html" class="btn-outline"><i class="bi bi-robot"></i> Screening rules</a><button class="btn-brand"><i class="bi bi-arrow-repeat"></i> Re-route stale</button>')

    # ============ Affiliates ============
    aff = [("Sunshine State Bail Bonds","Bail agent","Orlando, FL","Approved","1,204","12"),("Bayshore Chiropractic","Chiropractor","Tampa, FL","Approved","866","9"),("A1 Towing & Recovery","Towing","Orlando, FL","Pending","—","—"),("Notary Express Miami","Notary","Miami, FL","Approved","412","6"),("Central Florida Process Servers","Process server","Orlando, FL","Pending","—","—"),("Coastal Court Reporters","Court reporting","Jacksonville, FL","Approved","198","3"),("Gulf Auto Glass","Auto repair","Tampa, FL","Pending","—","—")]
    rows = [[f'<a href="affiliate-details.html" style="color:inherit">{who(n, cat)}</a>', c, status_pill(st), f'<span class="strong">{v}</span>', f'<span class="muted">{cl}</span>', row_actions('affiliate-details.html', more=[("bi-envelope","Send credentials","#"),("bi-link-45deg","Link a lawyer","connections.html"),("bi-trash","Delete","#")])] for n, cat, c, st, v, cl in aff]
    body = stats_row([('Affiliates','214','+18',True,'bi-shop',[150,158,165,172,180,188,195,202,208,214],'free listings'),('Pending approval','3','',True,'bi-hourglass-split',[5,5,4,4,4,3,3,3,3,3],'48-hour promise'),('Page views','18.4k','+22%',True,'bi-eye',[10,11,12,13,14,15,16,17,18,18.4],'last 30 days'),('Cross-links','1,120','+64',True,'bi-link-45deg',[800,840,880,920,960,1000,1040,1080,1100,1120],'deep links to providers')])
    body += '<div class="note mb-20"><i class="bi bi-info-circle-fill"></i><div><strong>Affiliates list for free.</strong> They claim a category and city like a provider (max 9 advertisers per city), are approved within 48 hours, and appear in search by location and category alongside related professionals.</div></div>'
    body += card('', filters('Search business', [('Category',['Bail agent','Chiropractor','Towing','Notary','Process server','Court reporting','Auto repair']),('City',[f'{c}, {s}' for c, s, _ in CITIES]),('Status',['Approved','Pending','Suspended'])]) + table([('Business','mid'),'City','Status',('Page views','num'),('Cross-links','num'),('','')], rows, total='214', shown='1–7'))
    shell('affiliates.html', 'Affiliates', 'affiliates.html', 'Affiliates', body, sub='Local businesses promoted for free and cross-linked with providers in their city.', actions='<button class="btn-outline"><i class="bi bi-download"></i> Export</button><a href="../affiliate/index.html" target="_blank" class="btn-outline"><i class="bi bi-box-arrow-up-right"></i> Affiliate portal</a><button class="btn-brand"><i class="bi bi-plus-lg"></i> Add affiliate</button>')

    # ============ Affiliate details ============
    hero = f'<div class="card mb-20"><div class="card-body"><div class="profile-hero">{av("Sunshine State Bail Bonds", cls="xl")}<div><h2>Sunshine State Bail Bonds {status_pill("Approved")} {pill("brand","Free listing")}</h2><div class="meta"><span><i class="bi bi-shop"></i> Bail agent</span><span><i class="bi bi-geo-alt"></i> 500 S Hughey Ave, Orlando, FL 32801</span><span><i class="bi bi-telephone"></i> (407) 555-0199</span><span><i class="bi bi-link-45deg"></i> inkozi.com/best-bail-bonds/orlando-florida/sunshine-state</span></div></div><div class="spacer"></div><div class="page-actions"><button class="btn-outline"><i class="bi bi-box-arrow-up-right"></i> Public page</button><a href="../affiliate/index.html" target="_blank" class="btn-outline"><i class="bi bi-person-badge"></i> Log in as</a><button class="btn-brand"><i class="bi bi-pencil"></i> Edit</button></div></div><div class="mini-stats mt-4"><div class="mini-stat"><strong>1,204</strong><span>Page views · 30 days</span></div><div class="mini-stat"><strong>12</strong><span>Cross-links</span></div><div class="mini-stat"><strong>38</strong><span>Coupon requests</span></div><div class="mini-stat"><strong>3</strong><span>Cities listed</span></div></div></div></div>'
    left = card('Listing content', '<div class="card-body">' + fld('Business name', inp('Sunshine State Bail Bonds')) + fld('Description', textarea('Licensed bail agents serving Orange County 24 hours a day. Payment plans available, most releases in under two hours.', 3)) + '<div class="row g-3"><div class="col-md-4">' + fld('Category', select(['Bail agent','Chiropractor','Towing','Notary','Process server'], 'Bail agent')) + '</div><div class="col-md-4">' + fld('County', select(['Orange County','Osceola County','Seminole County'], 'Orange County')) + '</div><div class="col-md-4">' + fld('Year established', inp('2009')) + '</div></div>' + fld('Cities listed', '<div class="d-flex flex-wrap gap-2">' + ''.join(f'<span class="chip active">{c} <i class="bi bi-x"></i></span>' for c in ["Orlando, FL","Kissimmee, FL","Sanford, FL"]) + '<span class="chip"><i class="bi bi-plus"></i> Add city</span></div>') + '</div>', foot='<button class="btn-brand" data-toast="Listing saved">Save listing</button>') \
        + card('Cross-links to providers', '<div class="card-body"><p class="muted mb-3" style="font-size:13px">Deep links shown on this page and on linked provider pages in Orlando.</p><ul class="list">' + ''.join(f'<li>{pav(n)}<div class="grow"><strong>{n}</strong><span>{PROV[n][1]}</span></div><button class="icon-btn danger"><i class="bi bi-x-lg"></i></button></li>' for n in ["Amir A. Ladan","John P. Morgan","Maria E. Gonzalez","Daniel Whitaker"]) + '</ul><a href="connections.html" class="btn-outline btn-sm w-100 mt-3"><i class="bi bi-plus-lg"></i> Link a provider</a></div>', hint='12') \
        + card('Coupons', '<div class="card-body"><div class="coupon-card"><div class="d-flex justify-content-between align-items-start gap-3 flex-wrap"><div><strong style="font-size:15px;color:var(--ink)">10% off any bond over $5,000</strong><div class="muted" style="font-size:12.5px">Valid to 31 Dec 2026 · 38 requests</div></div><span class="code">SUNSHINE10</span></div></div></div>', tools='<a href="coupons.html" class="btn-ghost btn-sm">All coupons</a>')
    right = card('Verification', '<div class="card-body">' + kv([('License','FL Bail Agent #BA-2210 · verified'),('Approved','2 Mar 2026 by Guido G.'),('Background check','Clear'),('Fee','$0 · affiliate program'),('Credentials','Sent 2 Mar 2026')]) + '</div>') + card('Contact', '<div class="card-body">' + kv([('Email','dispatch@sunshinebail.com'),('Phone','(407) 555-0199'),('Website','sunshinebail.com'),('Hours','24/7')]) + '</div>')
    shell('affiliate-details.html', 'Sunshine State Bail Bonds', 'affiliates.html', 'Affiliate', hero + two_col(left, right), crumbs=[("Dashboard","index.html"),("Affiliates","affiliates.html"),("Sunshine State Bail Bonds",None)])
