from gen_common import *

STAFF = [("Bert Seale","bert@inkozi.com","Founder & CEO","Super admin","Active","Yesterday"),("Liza Seale","liza@inkozi.com","Co-Founder & President","Super admin","Active","2 min ago"),("Chris Callaway","chris@inkozi.com","Chief Technology Officer","Super admin","Active","1 hr ago"),("Paul Cella","paul@inkozi.com","Chief Executive Officer","Super admin","Active","3 days ago"),("Dr. Sheffield Abood","sheffield@inkozi.com","Chief Financial Officer","Finance","Active","Yesterday"),("Bret Grubbs","bret@inkozi.com","National Sales Manager","Sales","Active","20 min ago"),("Guido Gulla","guido@inkozi.com","VP, Operations","Operations","Active","5 min ago"),("Michael Boggus","michael@inkozi.com","Chief Data Officer","Analyst","Active","Yesterday"),("Support agent (new)","agent@inkozi.com","Support","Support","Invited","—")]

def build():
    use_admin()
    # ============ Support inbox ============
    tickets = [("#4821","Provider not receiving inquiry SMS alerts","Omar Haddad","Provider","Account & login","Urgent","Open","Guido Gulla","12 min ago"),("#4820","Refund request for duplicate set-up fee","Jessica Pearson","Provider","Sales & territories","High","Open","Unassigned","48 min ago"),("#4819","Can't verify my mobile number","Hannah Reed","User","Account & login","Normal","Open","Liza Seale","2 hrs ago"),("#4818","Wrong city on my public profile","Michael T. Ross","Provider","Something else","Normal","Waiting","Guido Gulla","5 hrs ago"),("#4817","Please delete my account","Victor Alves","User","Account & login","Normal","Open","Unassigned","Yesterday"),("#4816","Advertising on the Orlando search page","Sunshine State Bail Bonds","Affiliate","Advertising","Normal","Open","Bret Grubbs","Yesterday"),("#4812","Interview request about Ask KOZI","Orlando Sentinel","Press","Press & media","Low","Resolved","Liza Seale","2 days ago")]
    rows = []
    for n, t, u, typ, topic, pr, st, asg, w in tickets:
        w2 = pwho(u, typ) if u in PROV else (uwho(u, typ) if u in USERS else who(u, typ))
        rows.append([f'<span class="mono">{n}</span>', f'<a href="#" class="strong">{t}</a><div class="muted">{typ} · contact form</div>', w2, f'<span class="tag">{topic}</span>', status_pill(pr) if pr == 'Urgent' else (pill('warn', pr) if pr == 'High' else f'<span class="muted">{pr}</span>'), status_pill(st), f'<span class="muted">{asg}</span>', f'<span class="muted">{w}</span>'])
    body = stats_row([('Open tickets','5','−3',True,'bi-inbox',[9,9,8,8,7,7,6,6,5,5],'vs yesterday'),('First response','1h 42m','−18m',True,'bi-stopwatch',[2.6,2.5,2.4,2.3,2.2,2.1,2.0,1.9,1.8,1.7],'promise: one business day'),('Resolved this week','61','+9',True,'bi-check2-all',[40,44,46,50,52,55,57,59,60,61]),('CSAT','96%','+2%',True,'bi-emoji-smile',[92,92,93,93,94,94,95,95,96,96])])
    body += '<div class="grid grid-8-4 mb-20">' + card('', filters('Search tickets', [('Topic',['Account & login','Sales & territories','Advertising','Press & media','Investor enquiry','Something else']),('From',['User','Provider','Affiliate','Press']),('Status',['Open','Waiting','Resolved']),('Assignee',['Liza Seale','Guido Gulla','Bret Grubbs','Unassigned'])], chips=['All 5','Mine 2','Unassigned 2']) + table(['Ticket',('Subject','wide'),'From','Topic','Priority','Status','Assignee','Updated'], rows, total='4,821', shown='1–7')) + card('Tickets this week', '<div class="card-body"><div class="chart-box sm"><canvas id="chart-tickets"></canvas></div><div class="legend mt-3"><span><i style="background:#E00A70"></i> Opened</span><span><i style="background:#CBD5E1"></i> Resolved</span></div>' + kv([('Phone','+1 786-451-0396'),('Email','support@inkozi.com'),('Hours','Mon 10:30–3:00 · Tue–Sat 9–5 · Sun closed')]) + '</div>', hint='contact.html') + '</div>'
    shell('support.html', 'Support inbox', 'support.html', 'Support inbox', body, sub='Messages from the contact form and in-app help. “A real person will get back to you within one business day.”', actions='<button class="btn-outline"><i class="bi bi-journal-text"></i> Canned replies</button><button class="btn-brand"><i class="bi bi-plus-lg"></i> New ticket</button>', charts=True)

    # ============ Demo & sales ============
    demos = [("Bayshore Chiropractic","Chiropractor · Tampa, FL","Request a Demo","Affiliate listing + Chiropractic territory","New","Yesterday","Bret Grubbs"),("Kim Defense, PLLC","Rachel Kim · DUI / DWI · Tampa","Sales & territories","Second territory: Criminal Defense · Tampa","Contacted","2 days ago","Bret Grubbs"),("Rodriguez Immigration Law","Elena Rodriguez · Austin, TX","Request a Demo","Immigration · Austin (6 open)","Demo booked · 17 Sep","3 days ago","Bret Grubbs"),("Specter & Associates","Harvey Specter · Miami, FL","Sales & territories","Personal Injury · Miami + Fort Lauderdale","Won","1 week ago","Bret Grubbs"),("Lone Star Bail","Bail agent · Austin, TX","Request a Demo","Affiliate listing","Lost · not launching TX bail yet","2 weeks ago","Guido Gulla"),("Orlando Injury Group","Investor enquiry","Investor form","Series A conversation","Contacted","3 weeks ago","Paul Cella")]
    rows = [[who(n, s), f'<span class="tag">{src}</span>', f'<span class="strong">{i}</span>', pill('ok','Won') if st == 'Won' else (pill('bad','Lost') if st.startswith('Lost') else (pill('info',st) if st != 'New' else status_pill('New'))), f'<span class="muted">{w}</span>', f'<span class="muted">{o}</span>', '<div class="actions"><button class="icon-btn"><i class="bi bi-telephone"></i></button><button class="icon-btn"><i class="bi bi-calendar2-plus"></i></button><button class="icon-btn" data-bs-toggle="tooltip" title="Push to Salesforce"><i class="bi bi-cloud-arrow-up"></i></button></div>'] for n, s, src, i, st, w, o in demos]
    body = stats_row([('Requests this month','42','+9',True,'bi-calendar2-check',[24,26,28,30,32,34,36,38,40,42]),('Demos booked','18','43%',True,'bi-camera-video',[10,11,12,13,14,15,16,17,18,18],'of requests'),('Won','11','+3',True,'bi-trophy',[5,6,6,7,8,8,9,10,10,11],'territories claimed'),('Synced to Salesforce','40','95%',True,'bi-cloud-check',[22,24,26,28,30,32,34,36,38,40],'leads + campaigns')])
    body += two_col(card('', filters('Search requests', [('Source',['Request a Demo','Sales & territories','Talk to Sales','Investor form','Claim-a-slot enquiry']),('Stage',['New','Contacted','Demo booked','Won','Lost']),('Owner',['Bret Grubbs','Guido Gulla','Paul Cella'])]) + table([('Business','mid'),'Source',('Interested in','mid'),'Stage','Received','Owner',('','')], rows, checks=False, total='42', shown='1–6')), card('Popular slots filling now', '<div class="card-body">' + ''.join(f'<div class="bar-row"><span class="lbl">{c} · {a}</span><div class="bar thin"><span style="width:{int((f + r) / 7 * 100)}%"></span></div><span class="val">{7 - f - r} open</span></div>' for a, c, s, f, r in TERR[:8]) + '<div class="muted mt-2" style="font-size:12.5px">Mirrors the “Open Territories” block on the For Lawyers page.</div></div>') + card('Sales contact & CRM', '<div class="card-body">' + kv([('Owner','Bret Grubbs · National Sales Manager'),('Phone','+1 786-451-0396'),('Form','contact.html → “Request a Demo”'),('CRM','Salesforce · leads + campaign “Lawyer 2026”')]) + '</div>'))
    shell('demo-requests.html', 'Demo & sales', 'demo-requests.html', 'Demo &amp; sales requests', body, sub='“Request a Demo”, “Talk to Sales”, claim-a-slot and investor enquiries, synced to Salesforce.', actions='<button class="btn-outline"><i class="bi bi-download"></i> Export</button><button class="btn-brand"><i class="bi bi-plus-lg"></i> Log a request</button>')

    # ============ Staff & roles ============
    rows = [[who(n, f'{t} · {e}'), f'<span class="tag">{r}</span>', status_pill(st) if st == 'Active' else pill('warn','Invited'), '<i class="bi bi-shield-fill-check text-success"></i> <span class="muted">On</span>' if st == 'Active' else '<span class="muted">—</span>', f'<span class="muted">{w}</span>', '<div class="actions"><button class="icon-btn"><i class="bi bi-pencil"></i></button><button class="icon-btn danger"><i class="bi bi-person-x"></i></button></div>'] for n, e, t, r, st, w in STAFF]
    perms = ['View dashboard & reports','Manage users','Manage providers & affiliates','Verify licenses & countersign','Moderate Q&A, reviews, chat','Refunds, invoices & billing','Marketing (ads, coupons, newsletters)','Edit site content & blog','Change settings']
    roles = [("Super admin",[1,1,1,1,1,1,1,1,1]),("Operations",[1,1,1,1,1,0,0,0,0]),("Support",[1,1,1,0,1,0,0,0,0]),("Sales",[1,0,1,0,0,0,1,0,0]),("Finance",[1,0,1,0,0,1,0,0,0]),("Analyst",[1,0,0,0,0,0,0,0,0]),("Content editor",[1,0,0,0,0,0,1,1,0])]
    mt = '<div class="table-wrap"><table class="tbl matrix"><thead><tr><th>Permission</th>' + ''.join(f'<th>{r}</th>' for r, _ in roles) + '</tr></thead><tbody>' + ''.join(f'<tr><td class="strong">{p}</td>' + ''.join(f'<td><i class="bi {"bi-check-circle-fill yes" if v[i] else "bi-dash-circle no"}"></i></td>' for _, v in roles) + '</tr>' for i, p in enumerate(perms)) + '</tbody></table></div>'
    body = card('', filters('Search staff', [('Role',[r for r, _ in roles]),('Status',['Active','Invited','Deactivated']),('Country scope',['United States','All countries'])]) + table(['Member','Role','Status','2FA','Last active',('','')], rows, checks=False, foot=False), hint='9 · leadership + support', cls='mb-20') + card('Role permissions', mt, tools='<button class="btn-outline btn-sm"><i class="bi bi-plus-lg"></i> New role</button>')
    shell('team.html', 'Staff & roles', 'team.html', 'Staff &amp; roles', body, sub='Who can access this console and what they can do. Two-factor is required for everyone; staff can be scoped to a country.', actions='<button class="btn-brand" data-bs-toggle="modal" data-bs-target="#invite"><i class="bi bi-person-plus"></i> Invite staff</button><div class="modal fade" id="invite" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Invite staff member</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><form data-demo><div class="modal-body"><div class="fld"><label>Work email</label><input class="form-control" type="email" placeholder="name@inkozi.com"></div><div class="fld mb-0"><label>Role</label><select class="form-select">' + ''.join(f'<option>{r}</option>' for r, _ in roles) + '</select></div></div><div class="modal-footer"><button type="button" class="btn-ghost" data-bs-dismiss="modal">Cancel</button><button class="btn-brand">Send invite</button></div></form></div></div></div>')

    # ============ Audit log ============
    data = [("Liza Seale","Approved verification","Jessica Pearson · Real Estate · Jacksonville","bi-patch-check","ok","Today, 10:42","10.4.2.18"),("Guido Gulla","Re-routed inquiry","Personal Injury · Tampa → Maria E. Gonzalez","bi-arrow-repeat","","Today, 10:05","10.4.2.31"),("Liza Seale","Hid Q&A post","Spam: “Cheap loans click here”","bi-eye-slash","bad","Today, 09:20","10.4.2.18"),("System","Retried hosting payment","Omar Haddad · attempt 2/3","bi-credit-card","","Today, 06:00","—"),("System","Sent newsletter","“September legal insights” · 18,204 recipients","bi-envelope-paper","","Today, 05:00","—"),("Chris Callaway","Changed setting","Ask KOZI iOS build 2.4 submitted","bi-phone","","Yesterday, 17:12","10.4.2.44"),("Dr. Sheffield Abood","Exported report","Revenue · Aug 2026 · CSV","bi-download","","Yesterday, 15:03","10.4.2.52"),("Bret Grubbs","Sent credentials","Sunshine State Bail Bonds · affiliate login","bi-key","warn","11 Sep, 11:40","10.4.2.27"),("Liza Seale","Published legal page","Privacy Policy v3.2","bi-shield-check","ok","8 Sep, 16:22","10.4.2.18"),("Guido Gulla","Suspended user","Victor Alves · repeated spam","bi-slash-circle","bad","1 Sep, 09:15","10.4.2.31")]
    rows = [[who(a, 'Staff' if a != 'System' else 'Automation'), f'<span class="pill {k} nodot"><i class="bi {ic}"></i> {act}</span>', f'<span class="strong">{obj}</span>', f'<span class="muted">{w}</span>', f'<span class="mono">{ip}</span>'] for a, act, obj, ic, k, w, ip in data]
    body = card('', filters('Search actions, objects or staff', [('Staff',[n for n, *_ in STAFF[:8]] + ['System']),('Action',['Approved','Re-routed','Hid','Changed setting','Published','Suspended','Exported','Sent'])], extra='<button class="btn-outline btn-sm"><i class="bi bi-calendar3"></i> Last 14 days</button>') + table(['Staff','Action',('Object','mid'),'When','IP'], rows, checks=False, total='18,204', shown='1–10'))
    shell('audit-log.html', 'Audit log', 'audit-log.html', 'Audit log', body, sub='Every change made in the console and by automation (cron), kept for 24 months.', actions='<button class="btn-outline"><i class="bi bi-download"></i> Export</button>')

    # ============ Settings ============
    tabs = '<div class="tabs"><a href="#" class="active">General</a><a href="#">Marketplace</a><a href="#">Notifications</a><a href="#">Integrations</a><a href="#">Security</a><a href="#">Automation</a></div>'
    gen = card('Brand & contact', '<div class="card-body"><form data-demo><div class="row g-3"><div class="col-md-6">' + fld('Site name', inp('InKozi')) + '</div><div class="col-md-6">' + fld('Tagline', inp('Ask · Trust · Connect')) + '</div><div class="col-md-6">' + fld('Support email', inp('support@inkozi.com')) + '</div><div class="col-md-6">' + fld('Support & sales phone', inp('+1 786-451-0396')) + '</div><div class="col-md-6">' + fld('Mailing address', textarea('8 The Green, Suite A\nDover, DE 19901', 2)) + '</div><div class="col-md-6">' + fld('Support hours', textarea('Monday 10:30 am – 3:00 pm\nTuesday – Saturday 9:00 am – 5:00 pm\nSunday closed', 3)) + '</div><div class="col-md-6">' + fld('Founded', inp('Orlando, Florida')) + '</div><div class="col-md-6">' + fld('Legal footer', inp('© 2024 InKozi, Inc. All rights reserved.')) + '</div></div></form></div>', foot='<button class="btn-ghost">Discard</button><button class="btn-brand" data-toast="Settings saved">Save changes</button>')
    market = card('Marketplace rules', '<div class="card-body"><div class="row g-3 mb-3">' + ''.join(f'<div class="col-md-4">{fld(l, inp(v), small=s)}</div>' for l, v, s in [("Providers per territory","7","max, lawyers per city"),("Advertisers per city","9","max, affiliates"),("Bail-bonds slots","3","per county"),("Set-up & administration fee","375","USD, one-time"),("Monthly hosting","45","USD per territory"),("Approval promise","48","hours"),("Slot hold time","24","hours"),("Unanswered alert","60","minutes"),("Coverage radius","25","miles"),("Billing cycle","30","days, pay-as-you-go"),("Payment retries","3","before the slot is released"),("Practice areas","28","published")]) + '</div>' + switch('One slot per firm','A firm cannot hold two of the seven slots in one territory') + switch('First in, first served','The first provider receives every inquiry until slot two fills, then leads rotate evenly by slot number and last-used') + switch('Fallback to preferred lawyer','Territories with no provider route to the preferred fallback') + switch('Bill only after verification','No charge until license, background, standing and agreement are approved') + switch('Hosting non-refundable once live','Cancellation stops the next 30-day renewal only') + switch('Release slot after failed renewal','After the third failed retry the slot reopens') + switch('AI-screened intake','Kozi questionnaire filters inquiries before delivery') + switch('Public slot counts','Show “3 of 7 slots filled” on the For Lawyers page') + '</div>', foot='<button class="btn-brand" data-toast="Marketplace rules saved">Save</button>')
    notif = card('Notifications', '<div class="card-body">' + ''.join(switch(t, d, c) for t, d, c in [("New verification submitted","Email the reviewer on duty",True),("Approval promise at risk","Slack #verifications when under 6 hours remain",True),("Unanswered question","In-app after 60 minutes without a lawyer reply",True),("Failed hosting payment","Email finance after the second retry",True),("Reported review or answer","Notify moderators immediately",True),("New question to provider","Email + SMS to the provider (and connected chiropractor for personal injury)",True),("Weekly digest","Monday 8:00 summary to all staff",False)]) + '</div>')
    integ = card('Integrations', '<div class="card-body"><ul class="list">' + ''.join(f'<li><span class="avatar sq soft"><i class="bi {i}"></i></span><div class="grow"><strong>{n}</strong><span>{d}</span></div>{p}</li>' for i, n, d, p in [("bi-stripe","Stripe","Hosting renewals and set-up fees · live mode",status_pill('Connected')),("bi-paypal","PayPal","Alternative checkout for invoices",status_pill('Connected')),("bi-credit-card","Authorize.net ARB","Legacy recurring billing · migrating",pill('warn','Read-only')),("bi-chat-dots","Telnyx","SMS verification codes and inquiry alerts",status_pill('Connected')),("bi-envelope","Postmark","Transactional email and newsletters",status_pill('Connected')),("bi-robot","Kozi AI","Intake screening and assistant",status_pill('Connected')),("bi-cloud","Salesforce","Leads and campaigns for sales",status_pill('Connected')),("bi-slack","Slack","#verifications, #support, #sales",status_pill('Connected')),("bi-google","Google Maps","Geocoding, distances and “Search by Map”",pill('warn','Key expires in 12 days')),("bi-facebook","Facebook & Google login","Social sign-in for users",status_pill('Connected')),("bi-award","Avvo","Rating sync for profile stats",status_pill('Connected'))]) + '</ul></div>')
    sec = card('Security', '<div class="card-body">' + switch('Require two-factor for all staff','Authenticator app or SMS code on every sign-in') + switch('Session timeout','Sign staff out after 30 minutes of inactivity') + switch('Secure gateway','User contact details encrypted and shared only with responding providers') + switch('Hash all passwords','bcrypt · plaintext credential emails are disabled') + switch('IP allow-list','Only office and VPN ranges can reach the console', False) + '</div>')
    auto = card('Automation (cron)', '<div class="card-body"><ul class="list">' + ''.join(f'<li><span class="avatar sq soft"><i class="bi {i}"></i></span><div class="grow"><strong>{n}</strong><span>{d}</span></div>{status_pill("Active")}</li>' for i, n, d in [("bi-arrow-repeat","Renew hosting","Daily 06:00 · charge 30-day renewals, retry failures, release slots"),("bi-envelope-paper","Newsletter queue","Every 5 min · send queued campaigns"),("bi-hourglass","Expire OTP codes","Hourly · purge verification codes older than 10 min"),("bi-hourglass-split","Release reserved slots","Hourly · after the 24-hour hold"),("bi-map","Rebuild sitemap","Nightly · profiles, cities, blog")]) + '</ul></div>')
    body = tabs + two_col(gen + market + notif, integ + sec + auto + card('Danger zone', '<div class="card-body"><p class="muted mb-3" style="font-size:13px">Pausing the marketplace hides the claim page and stops new questions. Existing conversations continue.</p><button class="btn-danger-soft w-100"><i class="bi bi-pause-circle"></i> Pause marketplace</button></div>'))
    shell('settings.html', 'Settings', 'settings.html', 'Settings', body, sub='Platform configuration. Changes apply immediately.')

    # ============ Profile ============
    left = card('Profile', '<div class="card-body"><div class="profile-hero mb-4"><span class="avatar xl">LS</span><div><h2>Liza Seale</h2><div class="meta"><span><i class="bi bi-shield-lock"></i> Super admin</span><span><i class="bi bi-briefcase"></i> Co-Founder &amp; President</span><span><i class="bi bi-envelope"></i> liza@inkozi.com</span><span><i class="bi bi-clock"></i> America/New_York</span></div></div><div class="spacer"></div><button class="btn-outline btn-sm"><i class="bi bi-camera"></i> Change photo</button></div><form data-demo><div class="row g-3"><div class="col-md-6">' + fld('First name', inp('Liza')) + '</div><div class="col-md-6">' + fld('Last name', inp('Seale')) + '</div><div class="col-md-6">' + fld('Email', inp('liza@inkozi.com')) + '</div><div class="col-md-6">' + fld('Phone', inp('+1 (407) 555-0142')) + '</div><div class="col-md-6">' + fld('Timezone', select(['America/New_York','America/Chicago','America/Los_Angeles'])) + '</div><div class="col-md-6">' + fld('Language', select(['English','Español'])) + '</div></div></form></div>', foot='<button class="btn-brand" data-toast="Profile saved">Save changes</button>') \
        + card('Password', '<div class="card-body"><form data-demo><div class="row g-3"><div class="col-md-4">' + fld('Current', inp('', '••••••••', 'password')) + '</div><div class="col-md-4">' + fld('New password', inp('', 'At least 12 characters', 'password')) + '</div><div class="col-md-4">' + fld('Confirm', inp('', '', 'password')) + '</div></div></form></div>', foot='<button class="btn-outline" data-toast="Password updated">Update password</button>')
    right = card('Two-factor authentication', '<div class="card-body"><div class="note ok mb-3"><i class="bi bi-shield-fill-check"></i><div><strong>Enabled</strong> with an authenticator app since 4 Jan 2025.</div></div><button class="btn-outline btn-sm w-100 mb-2"><i class="bi bi-qr-code"></i> Show recovery codes</button><button class="btn-danger-soft btn-sm w-100">Disable 2FA</button></div>') + card('Active sessions', '<div class="card-body"><ul class="list">' + ''.join(f'<li><span class="avatar sq soft"><i class="bi {i}"></i></span><div class="grow"><strong>{d}</strong><span>{l}</span></div>{p}</li>' for i, d, l, p in [("bi-laptop","MacBook Pro · Chrome","Orlando, FL · now",pill('ok','This device')),("bi-phone","iPhone · Safari","Orlando, FL · 2 hrs ago",'<button class="icon-btn danger"><i class="bi bi-x-lg"></i></button>')]) + '</ul><button class="btn-outline btn-sm w-100 mt-3">Sign out everywhere else</button></div>')
    shell('profile.html', 'My profile', 'profile.html', 'My profile', two_col(left, right))

    # ============ Login / forgot / 404 ============
    login = '''<div class="auth-wrap"><div class="auth-card">
  <div class="logo"><img src="assets/images/logo.png" alt="InKozi"><span class="env">Admin console</span></div>
  <h1>Sign in</h1><p class="sub">Restricted to InKozi staff. Every sign-in is logged.</p>
  <form data-demo="index.html">
    <div class="fld"><label for="l-email">Work email</label><div class="with-icon"><i class="bi bi-envelope"></i><input class="form-control" id="l-email" type="email" placeholder="you@inkozi.com" autocomplete="username" required></div></div>
    <div class="fld"><label for="l-pass">Password <a href="forgot-password.html" style="font-weight:600;font-size:12.5px">Forgot?</a></label><div class="pw-wrap"><input class="form-control" id="l-pass" type="password" placeholder="Your password" autocomplete="current-password" required><button type="button" class="pw-toggle" aria-label="Show password"><i class="bi bi-eye"></i></button></div></div>
    <div class="fld"><label>Authenticator code <small>6 digits</small></label><div class="otp">''' + ''.join(f'<input type="text" inputmode="numeric" maxlength="1" aria-label="Digit {i + 1}">' for i in range(6)) + '''</div></div>
    <div class="form-check mb-3"><input class="form-check-input" type="checkbox" id="l-trust"><label class="form-check-label" for="l-trust">Trust this device for 30 days</label></div>
    <button class="btn-brand w-100">Sign in <i class="bi bi-arrow-right"></i></button>
  </form>
  <div class="or">or</div>
  <button class="btn-outline w-100"><i class="bi bi-google"></i> Continue with Google Workspace</button>
  <div class="auth-foot">&copy; 2024 InKozi, Inc. <a href="../frontend/privacy-policy.html">Privacy</a> · <a href="../frontend/terms-of-use.html">Terms</a> · <a href="../frontend/index.html">Public site</a></div>
</div></div>'''
    standalone('login.html', 'Sign in', login)
    forgot = '''<div class="auth-wrap"><div class="auth-card">
  <div class="logo"><img src="assets/images/logo.png" alt="InKozi"><span class="env">Admin console</span></div>
  <h1>Reset your password</h1><p class="sub">Enter your work email. If it belongs to a staff account we will send a reset link that expires in 15 minutes.</p>
  <form data-demo="login.html">
    <div class="fld"><label for="f-email">Work email</label><div class="with-icon"><i class="bi bi-envelope"></i><input class="form-control" id="f-email" type="email" placeholder="you@inkozi.com" required></div></div>
    <button class="btn-brand w-100">Send reset link <i class="bi bi-arrow-right"></i></button>
  </form>
  <a href="login.html" class="btn-outline w-100 mt-3"><i class="bi bi-arrow-left"></i> Back to sign in</a>
  <div class="auth-foot">Locked out? Ask another super admin to reset it from <strong>Staff &amp; roles</strong>.</div>
</div></div>'''
    standalone('forgot-password.html', 'Reset password', forgot)
    nf = '''<div class="auth-wrap"><div class="auth-card" style="text-align:center;max-width:480px">
  <img src="assets/images/kozi-mascot.png" alt="" style="width:110px;border-radius:50%;box-shadow:0 0 0 6px #fff,0 0 0 8px rgba(224,10,112,.14);margin-bottom:18px">
  <div style="font-size:64px;font-weight:900;letter-spacing:-3px;line-height:1;background:var(--gradient);-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent">404</div>
  <h1 style="margin-top:8px">That page isn't in the console.</h1><p class="sub">The link may be out of date, or you may not have permission to see it.</p>
  <div class="d-flex gap-2 justify-content-center flex-wrap"><a href="index.html" class="btn-brand"><i class="bi bi-grid-1x2"></i> Dashboard</a><a href="javascript:history.back()" class="btn-outline"><i class="bi bi-arrow-left"></i> Go back</a></div>
</div></div>'''
    standalone('404.html', 'Not found', nf)
