from gen_common import *

PNAV = [
  ("Overview", [("index.html","bi-grid-1x2-fill","Dashboard",None),("notifications.html","bi-bell-fill","Notifications","4")]),
  ("Leads", [("inquiries.html","bi-send-fill","Inquiries","3 hot"),("questions.html","bi-chat-square-text-fill","Q&A to answer","2"),("chat.html","bi-chat-dots-fill","Live chat","1"),("clients.html","bi-people-fill","Clients & referrals",None),("tasks.html","bi-check2-square","Tasks","5")]),
  ("My presence", [("profile.html","bi-person-badge-fill","Public profile",None),("territories.html","bi-pin-map-fill","Territories",None),("blog.html","bi-journal-richtext","My blog",None),("coupons.html","bi-ticket-perforated-fill","Coupons & deals",None),("connections.html","bi-diagram-3-fill","Partner connections",None),("insights.html","bi-bar-chart-line-fill","Insights",None)]),
  ("Billing", [("billing.html","bi-credit-card-2-front-fill","Hosting & invoices",None),("agreement.html","bi-pen-fill","Agreement",None)]),
  ("Account", [("settings.html","bi-gear-fill","Settings",None)]),
]

def build():
    use_site(ROOT + 'provider/', 'Provider', PNAV, ('Amir A. Ladan', 'AL', 'Verified provider · Orlando', 'assets/images/lawyer-1.jpg'), 'Search inquiries, clients, questions…', [("territories.html","bi-pin-map","Claim a territory"),("blog-editor.html","bi-journal-plus","Write a blog post"),("coupons.html","bi-ticket-perforated","New coupon"),("tasks.html","bi-check2-square","New task")], public_link='../frontend/profile.html')

    # ============ Dashboard ============
    body = stats_row([('New inquiries','3','this week 11',True,'bi-send',[6,7,8,8,9,9,10,10,11,11],''),('Median reply','9 min','−2 min',True,'bi-stopwatch',[14,13,12,12,11,11,10,10,9,9],'“responds in under 5 min” target'),('Profile views','1,842','+18%',True,'bi-eye',[120,130,140,150,160,165,170,175,180,184],'last 30 days'),('Rating','4.9','128 reviews',True,'bi-star',[4.8,4.8,4.8,4.9,4.9,4.9,4.9,4.9,4.9,4.9],'')])
    inq = table([('Inquiry','wide'),'Kozi score','Status','Received',('','')], [['<span class="strong">DUI · Orlando, FL</span><div class="muted">Tom Becker · refused breath test · Orange County · wants a call today</div>', pill('ok','92'), status_pill('New'), '<span class="muted">2 hrs ago</span>', '<div class="actions"><a href="inquiry-details.html" class="btn-brand btn-xs">Respond</a></div>'],['<span class="strong">DUI · Orlando, FL</span><div class="muted">Lucas Nguyen · first offense · court date 22 Sep</div>', pill('ok','88'), status_pill('Retained'), '<span class="muted">3 days ago</span>', '<div class="actions"><a href="inquiry-details.html" class="icon-btn"><i class="bi bi-eye"></i></a></div>'],['<span class="strong">Criminal Defense · Orlando, FL</span><div class="muted">Michael Turner · background check after arrest</div>', pill('ok','81'), status_pill('Connected'), '<span class="muted">1 week ago</span>', '<div class="actions"><a href="inquiry-details.html" class="icon-btn"><i class="bi bi-eye"></i></a></div>']], checks=False, foot=False)
    terr = card('My territories', '<div class="card-body">' + ''.join(f'<div class="bar-row"><span class="lbl">{a}</span><div class="bar thin"><span style="width:{p}%"></span></div><span class="val">{v}</span></div>' for a, p, v in [("DUI / DWI · Orlando",71,"5/7"),("Criminal Defense · Orlando",57,"4/7")]) + '<div class="note mt-2"><i class="bi bi-arrow-repeat"></i><div>You are <strong>first in</strong> DUI / DWI · Orlando. Leads rotate evenly among 4 providers; you are next in 2 of 4.</div></div><a href="territories.html" class="btn-outline btn-sm w-100 mt-3">Claim another territory</a></div>')
    tasks = card('Tasks due today', '<div class="card-body"><ul class="list">' + ''.join(f'<li><input class="form-check-input" type="checkbox"><div class="grow"><strong>{t}</strong><span>{d}</span></div>{pill(k, p)}</li>' for t, d, k, p in [("Call Tom Becker about DHSMV hearing","Due 2:00 pm · Call","bad","High"),("Email retainer to Lucas Nguyen","Due 5:00 pm · Email","warn","Medium"),("Text Michael Turner court date","Tomorrow · Text","","Low")]) + '</ul><a href="tasks.html" class="btn-outline btn-sm w-100 mt-3">All tasks</a></div>')
    body += '<div class="grid grid-8-4 mb-20">' + card('Inquiries', inq, tools='<a href="inquiries.html" class="btn-ghost btn-sm">View all</a>', hint='delivered instantly to you') + terr + '</div>'
    body += '<div class="grid grid-8-4">' + card('Profile views', '<div class="card-body"><div class="chart-box sm"><canvas id="chart-response"></canvas></div></div>', hint='last 14 days', tools='<a href="insights.html" class="btn-ghost btn-sm">Insights</a>') + tasks + '</div>'
    shell('index.html', 'Dashboard', 'index.html', 'Welcome back, Amir', body, sub='Your territories are live. 3 new inquiries are waiting for a reply.', crumbs=[("Dashboard", None)], actions='<a href="../frontend/profile.html" target="_blank" class="btn-outline"><i class="bi bi-box-arrow-up-right"></i> View public profile</a><a href="inquiries.html" class="btn-brand"><i class="bi bi-send"></i> Respond to inquiries</a>', charts=True)

    # ============ Notifications ============
    items = [("bi-send-fill","warn","New inquiry from <strong>Tom Becker</strong> · DUI · Orlando. Reply within 5 minutes to keep your response badge.","2 hrs ago","inquiry-details.html",True),("bi-chat-dots-fill","","<strong>Jasmine Rivera</strong> is requesting a live chat.","2 min ago","chat.html",True),("bi-chat-square-text-fill","","New Q&A question in <strong>DUI / DWI · Orlando</strong>: “Is a first-offense DUI a felony?”","3 days ago","questions.html",True),("bi-star-fill","ok","<strong>Jasmine R.</strong> left you a 5-star review.","2 weeks ago","profile.html",False),("bi-credit-card","","Hosting renewed for 2 territories · $90.00 · next renewal 1 Oct.","Today, 06:00","billing.html",False),("bi-pin-map-fill","","<strong>Criminal Defense · Orlando</strong> has 3 open slots. You hold slot 2.","Yesterday","territories.html",False)]
    lis = ''.join(f'<li{" style=\"background:#FCFCFF\"" if u else ""}><span class="t-dot {k}" style="width:36px;height:36px;border-radius:11px;display:inline-flex;align-items:center;justify-content:center;flex:0 0 auto"><i class="bi {ic}"></i></span><div class="grow"><span style="font-size:13.5px;color:var(--ink-2)">{t}</span><span>{w}</span></div><a href="{h}" class="btn-outline btn-xs">Open</a></li>' for ic, k, t, w, h, u in items)
    shell('notifications.html', 'Notifications', 'notifications.html', 'Notifications', two_col(card('', f'<div class="card-body"><ul class="list">{lis}</ul></div>'), card('Alerts', '<div class="card-body">' + switch('New inquiry','Email + SMS instantly') + switch('Live chat request','Push + SMS') + switch('New Q&A in my territories','Email') + switch('Reviews','Email') + switch('Billing','Email') + '</div>')), actions='<button class="btn-outline" data-toast="Marked as read"><i class="bi bi-check2-all"></i> Mark all read</button>')

    # ============ Inquiries ============
    data = [("DUI · Orlando, FL","Tom Becker","refused breath test · Orange County · wants a call today",92,"New","2 hrs ago"),("DUI · Orlando, FL","Lucas Nguyen","first offense · court date 22 Sep",88,"Retained","3 days ago"),("Criminal Defense · Orlando, FL","Michael Turner","background check after arrest",81,"Connected","1 week ago"),("DUI · Orlando, FL","Hannah Reed","cost question only",41,"Waiting","1 week ago"),("Criminal Defense · Orlando, FL","David Lopez","expungement · 2019 misdemeanor",86,"Retained","1 month ago"),("DUI · Orlando, FL","Jasmine Rivera","second DUI · hearing scheduled",90,"Retained","2 months ago")]
    rows = [[f'<a href="inquiry-details.html" class="strong">{t}</a><div class="muted">{d}</div>', uwho(u), pill('ok' if s >= 80 else 'warn', str(s)), status_pill(st), f'<span class="muted">{w}</span>', f'<div class="actions"><a href="inquiry-details.html" class="btn-{"brand" if st == "New" else "outline"} btn-xs">{"Respond" if st == "New" else "Open"}</a></div>'] for t, u, d, s, st, w in data]
    body = stats_row([('This month','11','+3',True,'bi-send',[6,7,8,8,9,9,10,10,11,11],'delivered to you'),('Connected','8','73%',True,'bi-link-45deg',[5,5,6,6,6,7,7,7,8,8]),('Retained','4','36%',True,'bi-briefcase',[2,2,3,3,3,3,4,4,4,4]),('Median reply','9 min','−2 min',True,'bi-stopwatch',[14,13,12,12,11,11,10,10,9,9])])
    body += card('', filters('Search inquiries', [('Territory',['DUI / DWI · Orlando','Criminal Defense · Orlando']),('Status',['New','Connected','Waiting','Retained','Closed'])], chips=['All','New 1','Needs follow-up 1']) + table([('Inquiry','wide'),'From','Kozi score','Status','Received',('','')], rows, checks=False, total='142', shown='1–6'))
    shell('inquiries.html', 'Inquiries', 'inquiries.html', 'Inquiries', body, sub='AI-screened leads from people in your territories. Contact details are shared with you the moment you respond.', actions='<button class="btn-outline"><i class="bi bi-download"></i> Export</button>')

    # ============ Inquiry details ============
    left = card('', f'<div class="card-body"><div class="d-flex justify-content-between gap-3 flex-wrap mb-3"><div class="d-flex gap-2 flex-wrap"><span class="tag">DUI / DWI</span><span class="tag">Orlando, FL · Orange County</span>{status_pill("New")}</div><span class="muted" style="font-size:12.5px">Received 2 hrs ago · rotation 1 of 4 · <span class="mono">inq_9C21</span></span></div><h2 style="font-size:19px;font-weight:800;letter-spacing:-.4px;margin-bottom:12px">Refused breath test last night, license taken</h2><p class="quote">I was pulled over on I-4 for drifting between lanes. I refused the roadside exercises and the breathalyzer. The officer took my license and gave me a paper. Never been in trouble before. What should I do in the next few days?</p><div class="section-title mt-3">Kozi intake answers</div>' + kv([('When did this happen?','Last night, 13 Sep 2026'),('County','Orange County'),('Already hired a lawyer?','No'),('Breath / blood / urine test?','Refused'),('First offense?','Yes'),('Court date','Not yet'),('Preferred contact','Phone · available after 5 pm'),('Relevance score',pill('ok','92 · Relevant'))]) + '</div>', foot='<button class="btn-outline btn-sm"><i class="bi bi-x-circle"></i> Not a fit</button><button class="btn-outline btn-sm" data-toast="Added to tasks"><i class="bi bi-check2-square"></i> Add task</button><button class="btn-brand btn-sm" data-toast="Marked as retained"><i class="bi bi-briefcase"></i> Mark retained</button>') \
        + card('Reply', '<div class="card-body">' + fld('Message to Tom', textarea("Hi Tom, this is Amir Ladan. A refusal triggers an automatic suspension, but you have 10 days from the arrest to request a DHSMV review hearing, and that protects your driving in the meantime. I can call you after 5 pm today to walk through it, no charge for the consultation.", 5)) + '<div class="d-flex gap-2 flex-wrap">' + ''.join(f'<span class="chip">{t}</span>' for t in ["Free consultation template","Request documents","Schedule a call"]) + '</div></div>', foot='<button class="btn-outline btn-sm"><i class="bi bi-telephone"></i> Call now</button><button class="btn-outline btn-sm"><i class="bi bi-chat-dots"></i> Start live chat</button><button class="btn-brand btn-sm" data-toast="Reply sent by email and SMS">Send reply</button>')
    right = card('Contact', '<div class="card-body">' + uwho('Tom Becker', 'Orlando, FL · verified mobile', cls='lg') + '<div class="mt-3">' + kv([('Phone','(407) 555-7734'),('Email','tom.becker@example.com'),('Source','Ask KOZI iOS'),('Shared with','You only (rotation)')]) + '</div><div class="note mt-3"><i class="bi bi-shield-lock-fill"></i><div>Details are shared only with you because you received this inquiry. Anything you discuss from here is privileged.</div></div></div>') + card('Timeline', '<div class="card-body">' + timeline([("bi-send-fill","","Delivered to you by rotation (slot 1 of 4)","2 hrs ago"),("bi-robot","","Kozi intake completed · score 92","2 hrs ago"),("bi-chat-square-text","","Also posted anonymously in public Q&A","2 hrs ago")]) + '</div>')
    shell('inquiry-details.html', 'Inquiry · Tom Becker', 'inquiries.html', 'Inquiry', two_col(left, right), crumbs=[("Dashboard","index.html"),("Inquiries","inquiries.html"),("Tom Becker",None)], actions='<a href="inquiries.html" class="btn-outline"><i class="bi bi-arrow-left"></i> Back</a>')

    # ============ Q&A to answer ============
    qs = [(QUESTIONS[0], "Answered by you · 41 helpful"),(QUESTIONS[5], "Awaiting your answer · 4 answers"),(QUESTIONS[6], "Answered by you · most helpful"),(QUESTIONS[8], "Answered by you")]
    rows = [[f'<a href="../frontend/question-details.html" target="_blank" class="strong">{q[0]}</a><div class="muted">{q[1]} · {q[2]}, {q[3]} · {q[6]:,} views</div>', f'<span class="muted">{n}</span>', status_pill('Answered' if 'Answered' in n else 'Awaiting answer'), f'<span class="muted">{q[8]}</span>', f'<div class="actions"><button class="btn-{"outline" if "Answered" in n else "brand"} btn-xs" data-bs-toggle="modal" data-bs-target="#answer">{"Edit answer" if "Answered" in n else "Answer"}</button></div>'] for q, n in qs]
    body = stats_row([('Answers','312','top responder',True,'bi-chat-square-text',[280,284,288,292,296,300,304,308,310,312],'all time'),('Helpful votes','1,204','+38',True,'bi-hand-thumbs-up',[900,940,980,1020,1060,1100,1140,1170,1190,1204]),('Awaiting you','2','',True,'bi-hourglass',[3,3,3,2,2,2,2,2,2,2],'in your territories'),('Median answer time','22 min','−4 min',True,'bi-stopwatch',[30,29,28,27,26,25,24,23,22,22])])
    body += card('', filters('Search questions', [('Territory',['DUI / DWI · Orlando','Criminal Defense · Orlando']),('Status',['Awaiting answer','Answered'])], chips=['All','Awaiting 2','Answered by me 310']) + table([('Question','wide'),'Your answer','Status','Asked',('','')], rows, checks=False, total='412', shown='1–4') + '<div class="modal fade" id="answer" tabindex="-1"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Answer question</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><form data-demo><div class="modal-body"><p class="quote mb-3"><strong>Is a first-offense DUI in Florida a felony or a misdemeanor?</strong></p>' + fld('Your answer', textarea('', 6), small='general information only, shown publicly with your name') + '<div class="note"><i class="bi bi-info-circle-fill"></i><div>Answers are general information and do not create an attorney-client relationship. The user can then contact you directly.</div></div></div><div class="modal-footer"><button type="button" class="btn-ghost" data-bs-dismiss="modal">Cancel</button><button class="btn-brand">Post answer</button></div></form></div></div></div>')
    shell('questions.html', 'Q&A to answer', 'questions.html', 'Q&amp;A questions', body, sub='Public questions in your territories. Only verified lawyers can answer; helpful answers bring inquiries.', actions='<a href="../frontend/qa.html" target="_blank" class="btn-outline"><i class="bi bi-box-arrow-up-right"></i> Public Q&amp;A</a>')

    # ============ Live chat ============
    lst = ''.join(f'<div class="chat-item {"active" if i == 0 else ""}">{av(n)}<div class="grow"><strong>{n}</strong><span>{m}</span></div><time>{t}</time></div>' for i, (n, m, t) in enumerate([("Jasmine Rivera","Requesting a live chat · DUI hearing follow-up","now"),("Michael Turner","Thanks Amir, see you Thursday.","1 hr"),("Lucas Nguyen","Got it, I'll bring the citation.","3 hrs"),("David Lopez","Chat ended","2 days")]))
    msgs = '<div class="msg sys">Jasmine Rivera requested a live chat · accept to open the room</div><div class="msg">Hi Amir, quick question about the hearing next week. Do I need to bring anything?<time>2 min ago</time></div>'
    chat = f'<div class="card"><div class="chat"><div class="chat-list">{lst}</div><div class="chat-pane"><div class="chat-head">{uwho("Jasmine Rivera","Orlando, FL · client since Aug 2026")}<div class="spacer" style="flex:1"></div><button class="btn-brand btn-sm" data-toast="Chat accepted"><i class="bi bi-check-lg"></i> Accept chat</button><button class="btn-outline btn-sm"><i class="bi bi-telephone"></i> Call</button></div><div class="chat-body">{msgs}</div><div class="chat-foot"><button class="icon-btn"><i class="bi bi-paperclip"></i></button><input placeholder="Type a reply…"><button class="btn-brand btn-sm"><i class="bi bi-send"></i></button></div></div></div></div>'
    shell('chat.html', 'Live chat', 'chat.html', 'Live chat', chat, sub='Users can start a Live Chat from your profile. Accept a request to open the room; you usually respond in under 5 minutes.', actions='<div class="form-check form-switch mb-0"><input class="form-check-input" type="checkbox" checked id="avail"><label class="form-check-label" for="avail">Available now</label></div>')

    # ============ Clients & referrals ============
    cl = [("Tom Becker","DUI · Orlando","New inquiry","(407) 555-7734","2 hrs ago"),("Lucas Nguyen","DUI · Orlando","Retained · court 22 Sep","(407) 555-9930","3 days ago"),("Michael Turner","Criminal Defense · Orlando","Connected","(407) 555-8841","1 week ago"),("David Lopez","Criminal Defense · Orlando","Retained · expungement filed","(407) 555-2210","1 month ago"),("Jasmine Rivera","DUI · Orlando","Retained · hearing 19 Sep","(407) 555-0123","2 months ago")]
    rows = [[uwho(n), f'<span class="muted">{t}</span>', f'<span class="strong">{s}</span>', f'<span class="muted">{p}</span>', f'<span class="muted">{w}</span>', '<div class="actions"><button class="icon-btn"><i class="bi bi-telephone"></i></button><button class="icon-btn"><i class="bi bi-envelope"></i></button><button class="icon-btn"><i class="bi bi-check2-square"></i></button></div>'] for n, t, s, p, w in cl]
    refs = [("Bayshore Chiropractic","Carlos Mendez · PI · Tampa","$250","Paid","18 Aug 2026"),("John P. Morgan","Sofia Martins · DUI · Tampa (outside my territory)","$0","—","2 Sep 2026")]
    rrows = [[(pwho(p) if p in PROV else who(p, 'Partner')), f'<span class="muted">{c}</span>', f'<span class="strong">{f}</span>', status_pill(st) if st != '—' else '<span class="muted">—</span>', f'<span class="muted">{d}</span>'] for p, c, f, st, d in refs]
    body = '<div class="tabs"><a href="#" class="active">Clients <span class="n">5</span></a><a href="#">Referrals <span class="n">2</span></a></div>' + card('', filters('Search clients', [('Territory',['DUI / DWI · Orlando','Criminal Defense · Orlando']),('Status',['New inquiry','Connected','Retained','Closed'])]) + table(['Client',('Territory','mid'),'Status','Phone','Last activity',('','')], rows, checks=False, total='38', shown='1–5'), cls='mb-20') + card('Referrals', table(['Referred to / from',('Client','mid'),('Referral fee','num'),'Status','Date'], rrows, checks=False, foot=False), tools='<button class="btn-outline btn-sm"><i class="bi bi-plus-lg"></i> Log referral</button>', hint='track fees you pay or receive')
    shell('clients.html', 'Clients & referrals', 'clients.html', 'Clients &amp; referrals', body, sub='Everyone who connected with you through InKozi, and referrals to partners.', actions='<button class="btn-outline"><i class="bi bi-download"></i> Export</button><button class="btn-brand"><i class="bi bi-person-plus"></i> Add client</button>')

    # ============ Tasks ============
    tk = [("Call Tom Becker about DHSMV hearing","Call","Tom Becker","High","Today 2:00 pm","Open"),("Email retainer to Lucas Nguyen","Email","Lucas Nguyen","Medium","Today 5:00 pm","Open"),("Text Michael Turner court date","Text","Michael Turner","Low","Tomorrow","Open"),("Prepare hearing notes for Jasmine","Other","Jasmine Rivera","High","18 Sep","Open"),("Follow up Hannah Reed on cost question","Call","Hannah Reed","Low","20 Sep","Open"),("Send David Lopez expungement confirmation","Email","David Lopez","Medium","Yesterday","Complete")]
    rows = [['<input class="form-check-input" type="checkbox"' + (' checked' if st == 'Complete' else '') + '>', f'<span class="strong">{t}</span>', f'<span class="tag"><i class="bi bi-{ {"Call":"telephone","Email":"envelope","Text":"chat","Other":"list-check"}[a] }"></i> {a}</span>', uwho(c), pill({"High":"bad","Medium":"warn","Low":""}[p], p), f'<span class="muted">{d}</span>', status_pill(st), '<div class="actions"><button class="icon-btn"><i class="bi bi-pencil"></i></button><button class="icon-btn danger"><i class="bi bi-trash"></i></button></div>'] for t, a, c, p, d, st in tk]
    body = two_col(card('', filters('Search tasks', [('Action',['Call','Email','Text','Other']),('Priority',['High','Medium','Low']),('Status',['Open','Complete'])], chips=['Today 2','This week 5','All']) + table([('','chk'),('Task','wide'),'Action','Client','Priority','Due','Status',('','')], rows, checks=False, foot=False)), card('New task', '<div class="card-body"><form data-demo>' + fld('Task', inp('', 'e.g. Call back about hearing')) + fld('Action', select(['Call','Email','Text','Other'])) + fld('Client', select(['Tom Becker','Lucas Nguyen','Michael Turner','Jasmine Rivera'])) + fld('Priority', select(['High','Medium','Low'], 'Medium')) + fld('Due', inp('', '', 'datetime-local')) + fld('Notes', textarea('', 2)) + '<button class="btn-brand w-100">Add task</button></form></div>'))
    shell('tasks.html', 'Tasks', 'tasks.html', 'Tasks', body, sub='Your follow-up list: calls, emails and texts to clients.', actions='<button class="btn-brand"><i class="bi bi-plus-lg"></i> New task</button>')

    # ============ Public profile editor ============
    tabs = '<div class="tabs"><a href="#" class="active">Profile</a><a href="#">Practice areas</a><a href="#">Photos &amp; video</a><a href="#">FAQ</a><a href="#">Social media</a><a href="#">Reviews <span class="n">128</span></a></div>'
    left = card('Basics', '<div class="card-body"><div class="profile-hero mb-4"><img class="avatar xl" src="assets/images/lawyer-1.jpg" alt=""><div><h2>Amir A. Ladan ' + pill('ok','Verified InKozi Provider') + '</h2><div class="meta"><span><i class="bi bi-link-45deg"></i> inkozi.com/best-dui-lawyer/amir-a-ladan</span><span><i class="bi bi-eye"></i> 1,842 views · 30 days</span></div></div><div class="spacer"></div><button class="btn-outline btn-sm"><i class="bi bi-camera"></i> Change photo</button></div><div class="row g-3"><div class="col-md-4">' + fld('First name', inp('Amir')) + '</div><div class="col-md-4">' + fld('Middle', inp('A.')) + '</div><div class="col-md-4">' + fld('Last name', inp('Ladan')) + '</div><div class="col-md-6">' + fld('Firm', inp('Ladan Law, P.A.')) + '</div><div class="col-md-6">' + fld('Headline', inp('Criminal Defense • DUI / DWI')) + '</div><div class="col-12">' + fld('Short bio', textarea('Former prosecutor with over 15 years of experience defending clients against DUI and criminal charges.', 2), small='search cards') + '</div><div class="col-12">' + fld('About', textarea('Amir A. Ladan is a dedicated criminal defense attorney based in Orlando, Florida, with over 15 years of experience. He focuses his practice on DUI / DWI defense and works tirelessly to protect your rights and achieve the best possible outcome.', 4)) + '</div><div class="col-md-4">' + fld('Years experience', inp('15+')) + '</div><div class="col-md-4">' + fld('Cases won', inp('500+')) + '</div><div class="col-md-4">' + fld('Avvo rating', inp('10.0 · Superb')) + '</div></div></div>', foot='<button class="btn-ghost">Discard</button><button class="btn-brand" data-toast="Profile saved">Save</button>') \
        + card('Office & contact', '<div class="card-body"><div class="row g-3"><div class="col-md-8">' + fld('Address', inp('111 N Orange Ave, Ste 800')) + '</div><div class="col-md-4">' + fld('ZIP', inp('32801')) + '</div><div class="col-md-4">' + fld('City', inp('Orlando')) + '</div><div class="col-md-4">' + fld('State', select(STATES, 'Florida')) + '</div><div class="col-md-4">' + fld('Phone (Call Now)', inp('(407) 555-0123')) + '</div><div class="col-md-6">' + fld('Website', inp('ladanlaw.com')) + '</div><div class="col-md-6">' + fld('Languages', inp('English, Spanish')) + '</div><div class="col-12">' + fld('Payment options', '<div class="d-flex flex-wrap gap-2">' + ''.join(f'<span class="chip active">{x}</span>' for x in ["Credit Cards","Cash","Financing Options"]) + '<span class="chip">Payment plans</span></div>') + '</div></div>' + switch('Live chat','Show “Live Chat” on my profile') + switch('Available now badge','Show when I am online') + '</div>') \
        + card('Highlights & practice areas', '<div class="card-body">' + fld('Highlights', '<div class="d-flex flex-wrap gap-2">' + ''.join(f'<span class="chip active">{x} <i class="bi bi-x"></i></span>' for x in ["Former Prosecutor","Free Initial Consultation","Aggressive Representation","Payment Plans Available","Available 24/7","Se Habla Español"]) + '<span class="chip"><i class="bi bi-plus"></i> Add</span></div>') + fld('Practice areas', '<div class="d-flex flex-wrap gap-2">' + ''.join(f'<span class="chip active">{x} <i class="bi bi-x"></i></span>' for x in ["DUI / DWI","Criminal Defense","Traffic Violations","Drug Crimes","Expungements"]) + '<span class="chip"><i class="bi bi-plus"></i> Add</span></div>', small='first one is your headline') + fld('Profile FAQ', '<ul class="list">' + ''.join(f'<li><span class="avatar sq soft"><i class="bi bi-question-lg"></i></span><div class="grow"><strong>{q}</strong><span>{a}</span></div><button class="icon-btn"><i class="bi bi-pencil"></i></button></li>' for q, a in [("What should I do after a DUI arrest in Florida?","Act quickly and contact a qualified DUI attorney…"),("Can a DUI charge be reduced or dismissed?","Yes, in many cases…"),("How much does a DUI lawyer cost?","I offer a free initial consultation…"),("Will a DUI stay on my record?","In Florida, DUI convictions generally cannot be expunged…")]) + '</ul>', small='pick up to 4 default questions and write your answers') + '</div>')
    right = card('Introduction video', '<div class="card-body"><div class="cover" style="padding:30px 10px"><i class="bi bi-play-circle-fill"></i>intro-amir.mp4 · 1:42<div style="font-size:12px">Shown as “Watch Introduction”</div></div>' + fld('or YouTube link', inp('', 'https://youtube.com/…')) + '</div>') + card('Photos', '<div class="card-body"><div class="grid grid-2" style="gap:8px">' + ''.join(f'<div class="cover" style="padding:18px 8px"><i class="bi bi-image"></i>{x}</div>' for x in ["Office","Reception","Team","+ Add"]) + '</div></div>') + card('Social media', '<div class="card-body">' + ''.join(fld(l, inp(v)) for l, v in [("Facebook","facebook.com/ladanlaw"),("Instagram","@ladanlaw"),("LinkedIn","linkedin.com/in/amirladan"),("YouTube","youtube.com/@ladanlaw"),("Podcast",""),("Blog","ladanlaw.com/blog")]) + '</div>') + card('Credentials', '<div class="card-body">' + kv([('FL Bar','#0123456 · verified'),('Admitted','2011'),('Verified','4 Jan 2025'),('Good standing','Re-checked 1 Sep 2026')]) + '</div>')
    shell('profile.html', 'Public profile', 'profile.html', 'Public profile', tabs + two_col(left, right), sub='What people see on your InKozi page and search cards.', actions='<a href="../frontend/profile.html" target="_blank" class="btn-outline"><i class="bi bi-eye"></i> Preview</a><button class="btn-brand" data-toast="Profile published"><i class="bi bi-check-lg"></i> Publish changes</button>')

    # ============ Territories + claim flow ============
    mine = table([('Territory','mid'),'Slot','Rotation','Inquiries · 30d',('Hosting','num'),'Status',('','')], [['<span class="strong">DUI / DWI</span><div class="muted">Orlando, FL · Orange County</div>', '<span class="strong">1 of 7</span><div class="muted">first in · since Jan 2025</div>', '<span class="muted">Next in 2 of 4</span>', '<span class="strong">8</span>', '<span class="strong">$45 / mo</span>', status_pill('Active'), '<div class="actions"><a href="../frontend/search.html" target="_blank" class="icon-btn"><i class="bi bi-box-arrow-up-right"></i></a><button class="icon-btn danger" data-bs-toggle="tooltip" title="Cancel at renewal"><i class="bi bi-x-circle"></i></button></div>'],['<span class="strong">Criminal Defense</span><div class="muted">Orlando, FL · Orange County</div>', '<span class="strong">2 of 7</span><div class="muted">since Mar 2026</div>', '<span class="muted">Next in 1 of 4</span>', '<span class="strong">3</span>', '<span class="strong">$45 / mo</span>', status_pill('Active'), '<div class="actions"><a href="../frontend/search.html" target="_blank" class="icon-btn"><i class="bi bi-box-arrow-up-right"></i></a><button class="icon-btn danger"><i class="bi bi-x-circle"></i></button></div>']], checks=False, foot=False)
    claim = card('Claim another territory', '<div class="card-body">' + steps(["Choose city","Choose practice area","Pick a slot","Pay & go live"], 1) + '<div class="row g-3 mb-3"><div class="col-md-4">' + fld('State', select(STATES, 'Florida')) + '</div><div class="col-md-4">' + fld('City', select([f'{c}, {s}' for c, s, _ in CITIES], 'Tampa, FL')) + '</div><div class="col-md-4">' + fld('Practice area', select(AREAS[:10], 'DUI / DWI')) + '</div></div><div class="section-title">Availability for DUI / DWI in Tampa, FL</div><div class="slots">' + ''.join(f'<div class="slot">{pav(n)}<strong>{n}</strong><span>Slot {i + 1}</span></div>' for i, n in enumerate(["Maria E. Gonzalez","Rachel Kim","Daniel Whitaker"])) + '<div class="slot held"><span class="avatar soft"><i class="bi bi-hourglass-split"></i></span><strong>Reserved</strong><span>held 24h</span></div>' + ''.join(f'<div class="slot open" style="cursor:pointer"><span class="plus"><i class="bi bi-plus-lg"></i></span><strong>Open slot</strong><span>Slot {i}</span></div>' for i in (5, 6, 7)) + '</div><div class="sum-box mt-3" style="display:flex;justify-content:space-between;align-items:center;gap:14px;border:1.5px solid var(--line);border-radius:14px;background:var(--soft);padding:14px 16px"><div><strong>DUI / DWI · Tampa, FL · slot 5</strong><div class="muted" style="font-size:12.5px">One slot per firm · 3 open · you would be 4th in rotation</div></div><div class="text-end"><strong style="font-size:17px">$375 + $45 / mo</strong><div class="muted" style="font-size:12px">set-up + hosting · promo LAUNCH375 accepted</div></div></div></div>', foot='<button class="btn-outline">Back</button><button class="btn-brand" data-toast="Slot reserved for 24 hours · continue to payment">Reserve slot &amp; pay <i class="bi bi-arrow-right"></i></button>')
    body = stats_row([('My territories','2','',True,'bi-pin-map',[1,1,1,1,1,2,2,2,2,2],'$90 / month'),('Inquiries · 30 days','11','+3',True,'bi-send',[6,7,8,8,9,9,10,10,11,11]),('Rotation position','1st','DUI · Orlando',True,'bi-arrow-repeat',[1,1,1,1,1,1,1,1,1,1],'first in, every lead until slot 2 filled'),('Open slots near you','14','',True,'bi-grid-3x3-gap',[10,11,11,12,12,13,13,14,14,14],'Central Florida')])
    body += card('My territories', mine, hint='one slot per firm per territory') + '<div class="mt-4"></div>' + claim
    shell('territories.html', 'Territories', 'territories.html', 'Territories', body, sub='Each practice area × city holds seven providers. Claim as many as you like, one slot per firm each.', actions='<a href="../frontend/for-lawyers.html" target="_blank" class="btn-outline"><i class="bi bi-box-arrow-up-right"></i> How rotation works</a>')

    # ============ My blog ============
    mine = [p for p in POSTS if p[2] == 'Amir A. Ladan']
    rows = [[f'<a href="blog-editor.html" class="strong">{t}</a><div class="muted">{cat} · {r} read</div>', status_pill(st).replace('>Scheduled<','>Awaiting review<'), f'<span class="strong">{v}</span>', f'<span class="muted">{d}</span>', '<div class="actions"><a href="blog-editor.html" class="icon-btn"><i class="bi bi-pencil"></i></a><a href="../frontend/blog-details.html" target="_blank" class="icon-btn"><i class="bi bi-box-arrow-up-right"></i></a></div>'] for t, cat, a, d, st, v, r, cov in mine]
    body = two_col(card('', table([('Post','wide'),'Status',('Views','num'),'Date',('','')], rows, checks=False, foot=False), hint='published under your name on Legal Insights'), card('Why blog?', '<div class="card-body"><p class="muted" style="font-size:13px">Posts appear on the InKozi blog and on your profile, rank for your name and practice area, and are reviewed by InKozi staff before publishing.</p>' + kv([('Your posts','3 published'),('Views · 30 days','2,140'),('Inquiries from posts','4')]) + '<a href="blog-editor.html" class="btn-brand btn-sm w-100 mt-3"><i class="bi bi-plus-lg"></i> Write a post</a></div>'))
    shell('blog.html', 'My blog', 'blog.html', 'My blog', body, sub='Legal insights you publish on InKozi.', actions='<a href="blog-editor.html" class="btn-brand"><i class="bi bi-plus-lg"></i> New post</a>')
    toolbar = '<div class="editor-toolbar">' + ''.join(f'<button type="button" title="{t}"><i class="bi {i}"></i></button>' for t, i in [("Bold","bi-type-bold"),("Italic","bi-type-italic"),("Heading","bi-type-h2"),("Quote","bi-quote"),("Bullets","bi-list-ul"),("Link","bi-link-45deg"),("Image","bi-image")]) + '</div>'
    left = card('', '<div class="card-body"><div class="fld"><input class="form-control" style="height:52px;font-size:20px;font-weight:700" placeholder="Post title" value="Understanding Implied Consent in Florida"></div>' + toolbar + '<div class="editor-area" contenteditable="true"><p>Florida law operates under "implied consent," meaning that by holding a driver\'s license you have agreed to chemical testing when lawfully arrested for DUI.</p><h2>What refusing actually costs</h2><p>…</p></div></div>')
    right = card('Publish', '<div class="card-body">' + kv([('Status',pill('warn','Awaiting review')),('Category','Criminal Defense'),('Author','Amir A. Ladan')]) + '<div class="note mt-3"><i class="bi bi-info-circle-fill"></i><div>InKozi staff review posts within one business day before they go live.</div></div></div>', foot='<button class="btn-outline btn-sm" data-toast="Draft saved">Save draft</button><button class="btn-brand btn-sm" data-toast="Submitted for review">Submit for review</button>') + card('Cover image', '<div class="card-body"><div class="cover"><i class="bi bi-cloud-arrow-up-fill"></i>Drop an image or <a href="#">browse</a></div></div>')
    shell('blog-editor.html', 'Write a post', 'blog.html', 'Write a post', two_col(left, right), crumbs=[("Dashboard","index.html"),("My blog","blog.html"),("Write a post",None)])

    # ============ Coupons & deals ============
    body = two_col(card('My coupons', '<div class="card-body"><div class="grid grid-2">' + ''.join(f'<div class="coupon-card"><div class="d-flex justify-content-between gap-2 align-items-start"><div><strong style="font-size:15px;color:var(--ink)">{t}</strong><div class="muted" style="font-size:12.5px">{d}</div></div>{status_pill(st)}</div><div class="d-flex justify-content-between align-items-end mt-3 flex-wrap gap-2"><div class="price">{p}</div><span class="code">{c}</span></div><div class="muted mt-2" style="font-size:12px">{r} requests · expires {e}</div></div>' for t, d, p, c, st, r, e in [("Free DUI consultation","30-minute case review, in person or by phone","Free<s>$150</s>","KOZI-DUI-FREE","Active",38,"31 Dec 2026"),("Expungement flat fee","First-time misdemeanor expungement","$499<s>$750</s>","LADAN-EXP","Active",6,"30 Nov 2026")]) + '</div></div>', hint='shown on your profile and the public deals directory') + card('Coupon leads', table(['Person','Coupon','Status','Requested'], [[uwho('Tom Becker'),'<span class="strong">Free DUI consultation</span>',status_pill('Redeemed'),'<span class="muted">1 hr ago</span>'],[uwho('Hannah Reed'),'<span class="strong">Free DUI consultation</span>',status_pill('New'),'<span class="muted">Yesterday</span>'],[uwho('David Lopez'),'<span class="strong">Expungement flat fee</span>',status_pill('Redeemed'),'<span class="muted">1 month ago</span>']], checks=False, foot=False), hint='people who requested a coupon'), card('New coupon', '<div class="card-body"><form data-demo>' + fld('Title', inp('', 'e.g. Free first consultation')) + fld('Details', textarea('', 2)) + '<div class="row g-2"><div class="col-6">' + fld('Regular price', inp('', '$')) + '</div><div class="col-6">' + fld('Discounted price', inp('', '$ or Free')) + '</div></div>' + fld('Code', inp('', 'auto-generated if empty')) + fld('Expires', inp('', '', 'date')) + fld('Limitations', inp('', 'e.g. new clients only')) + '<div class="cover mb-3"><i class="bi bi-image"></i>Coupon image · 270 × 90</div><button class="btn-brand w-100">Publish coupon</button></form></div>'))
    shell('coupons.html', 'Coupons & deals', 'coupons.html', 'Coupons &amp; deals', body, sub='Offers shown on your profile and in the public deals directory. Requests arrive as leads.', actions='<button class="btn-brand"><i class="bi bi-plus-lg"></i> New coupon</button>')

    # ============ Partner connections ============
    body = two_col(card('My connections', '<div class="card-body"><ul class="list"><li>' + av('Bayshore Chiropractic', cls='lg') + '<div class="grow"><strong>Bayshore Chiropractic</strong><span>Chiropractor · Orlando &amp; Tampa · personal-injury inquiries are copied to them · their ad shows on my profile</span></div>' + status_pill('Active') + '<button class="icon-btn danger"><i class="bi bi-x-circle"></i></button></li><li>' + av('Sunshine State Bail Bonds', cls='lg') + '<div class="grow"><strong>Sunshine State Bail Bonds</strong><span>Bail agent · Orlando · their ad shows on my DUI profile · 24/7 releases for my clients</span></div>' + status_pill('Active') + '<button class="icon-btn danger"><i class="bi bi-x-circle"></i></button></li></ul></div>', hint='2') + card('Requests', '<div class="card-body"><ul class="list"><li>' + av('Coastal Spine & Injury') + '<div class="grow"><strong>Coastal Spine &amp; Injury</strong><span>Chiropractor · Orlando · wants to connect for PI leads</span></div><button class="btn-outline btn-xs">Decline</button><button class="btn-brand btn-xs" data-toast="Connection accepted">Accept</button></li></ul></div>'), card('Find a partner', '<div class="card-body"><form data-demo>' + fld('Partner type', select(['Chiropractor','Bail agent'])) + fld('City', select([f'{c}, {s}' for c, s, _ in CITIES], 'Orlando, FL')) + '<ul class="list mt-2">' + ''.join(f'<li>{av(n)}<div class="grow"><strong>{n}</strong><span>{d}</span></div><button class="btn-outline btn-xs" data-toast="Request sent">Connect</button></li>' for n, d in [("Orlando Spine Center","Chiropractor · 4.8 · 52 reviews"),("A-1 Bail Bonds","Bail agent · 4.6 · 31 reviews")]) + '</ul></form></div>') + card('How it works', '<div class="card-body"><p class="muted" style="font-size:13px">Connect with a verified chiropractor or bail agent in your city. Their ad appears on your profile, personal-injury inquiries are copied to your chiropractor, and you can log referral fees under Clients &amp; referrals.</p></div>'))
    shell('connections.html', 'Partner connections', 'connections.html', 'Partner connections', body, sub='Cross-referrals with chiropractors and bail agents in your city.')

    # ============ Insights ============
    body = stats_row([('Profile views','1,842','+18%',True,'bi-eye',[120,130,140,150,160,165,170,175,180,184],'last 30 days'),('Search impressions','9,310','+11%',True,'bi-search',[7,7.4,7.8,8.1,8.4,8.7,8.9,9.1,9.2,9.3]),('Call Now taps','86','+9',True,'bi-telephone',[60,64,68,70,72,76,78,80,84,86]),('Q&A answer views','4,120','+22%',True,'bi-chat-square-text',[2.8,3,3.2,3.4,3.5,3.7,3.8,3.9,4,4.1])])
    body += '<div class="grid grid-8-4 mb-20">' + card('Profile views by month', '<div class="card-body"><div class="chart-box"><canvas id="chart-growth"></canvas></div></div>', tools='<button class="btn-outline btn-sm"><i class="bi bi-calendar3"></i> Last 12 months</button>') + card('Where views come from', '<div class="card-body">' + ''.join(f'<div class="bar-row"><span class="lbl">{l}</span><div class="bar thin"><span style="width:{p}%"></span></div><span class="val">{p}%</span></div>' for l, p in [("Search results",46),("Q&A answers",24),("Google",18),("Blog posts",8),("Coupons directory",4)]) + '</div>') + '</div>'
    body += '<div class="grid grid-3">' + card('Listing views', '<div class="card-body">' + kv([('DUI Lawyers in Orlando','3,204 views · position 1'),('Criminal Defense · Orlando','1,102 views · position 2'),('Coupon: Free DUI consultation','412 views')]) + '</div>') + card('Statistics explained · Florida', '<div class="card-body">' + kv([('DUI arrests · Orange County','4,812 / yr'),('Avg. case value','$3,200'),('Searches “DUI lawyer Orlando”','2,900 / mo'),('Providers in territory','5 of 7')]) + '<div class="muted mt-2" style="font-size:12.5px">From the InKozi state statistics spreadsheet.</div></div>') + card('Response badge', '<div class="card-body"><div class="note ok"><i class="bi bi-lightning-charge-fill"></i><div><strong>Usually responds in under 5 minutes</strong> is shown on your profile. Keep your median reply under 5 minutes to keep it.</div></div>' + kv([('Median reply · 30 days','9 min'),('Target','5 min')]) + '</div>') + '</div>'
    shell('insights.html', 'Insights', 'insights.html', 'Insights', body, sub='How people find and contact you.', actions='<button class="btn-outline"><i class="bi bi-download"></i> Export</button>', charts=True)

    # ============ Billing ============
    inv = [("inv_2026_09_4411","Territory hosting · DUI / DWI · Orlando","$45.00","Paid","14 Sep 2026"),("inv_2026_09_4410","Territory hosting · Criminal Defense · Orlando","$45.00","Paid","14 Sep 2026"),("inv_2026_08_3990","Territory hosting · 2 territories","$90.00","Paid","15 Aug 2026"),("inv_2026_03_2210","Set-up & administration fee · Criminal Defense · Orlando","$375.00","Paid","2 Mar 2026"),("inv_2025_01_0412","Set-up & administration fee · DUI / DWI · Orlando","$375.00","Paid","4 Jan 2025")]
    rows = [[f'<span class="mono">{i}</span>', f'<span class="strong">{d}</span>', f'<span class="strong">{a}</span>', status_pill(st), f'<span class="muted">{w}</span>', '<div class="actions"><button class="icon-btn" data-bs-toggle="tooltip" title="Download PDF"><i class="bi bi-file-earmark-pdf"></i></button></div>'] for i, d, a, st, w in inv]
    left = card('Hosting', '<div class="card-body"><div class="mini-stats"><div class="mini-stat"><strong>$90.00</strong><span>per 30 days · 2 territories</span></div><div class="mini-stat"><strong>1 Oct 2026</strong><span>next renewal</span></div><div class="mini-stat"><strong>Mastercard •• 8810</strong><span>payment method</span></div><div class="mini-stat"><strong>$0.00</strong><span>due now</span></div></div><div class="note mt-3"><i class="bi bi-info-circle-fill"></i><div>Hosting renews every 30 days and is non-refundable once live. Cancel a territory before its renewal date to stop the next charge.</div></div></div>', foot='<button class="btn-outline btn-sm"><i class="bi bi-credit-card"></i> Update card</button><button class="btn-outline btn-sm"><i class="bi bi-paypal"></i> Use PayPal</button>') + card('Invoices & transactions', table(['Invoice',('Description','wide'),('Amount','num'),'Status','Date',('','')], rows, checks=False, total='22', shown='1–5'))
    right = card('Pay an invoice', '<div class="card-body"><p class="muted" style="font-size:13px">No open invoices. Set-up fees appear here after a new territory is approved.</p><button class="btn-brand w-100" disabled>Nothing to pay</button></div>') + card('Financing & merchant services', '<div class="card-body"><ul class="list"><li><span class="avatar sq soft"><i class="bi bi-cash-coin"></i></span><div class="grow"><strong>Legal financing partners</strong><span>Offer case funding to your clients</span></div><a href="#" class="icon-btn"><i class="bi bi-arrow-up-right"></i></a></li><li><span class="avatar sq soft"><i class="bi bi-credit-card-2-front"></i></span><div class="grow"><strong>Merchant account</strong><span>Accept card payments from clients</span></div><a href="#" class="icon-btn"><i class="bi bi-arrow-up-right"></i></a></li></ul></div>')
    shell('billing.html', 'Hosting & invoices', 'billing.html', 'Hosting &amp; invoices', two_col(left, right), sub='$45 per month per territory, plus a one-time $375 set-up fee per territory.')

    # ============ Agreement ============
    left = card('Hosting agreement v1.4', '<div class="card-body"><div class="editor-area" style="min-height:280px" contenteditable="false"><p><strong>InKozi Territory Hosting Agreement</strong></p><p>This agreement is between InKozi, Inc. and the Provider named below. Territory hosting is billed per category and city at $45 per 30-day period plus a one-time $375 administration and set-up fee. Hosting renews automatically until cancelled before a renewal date and is non-refundable once the profile is live. Each Provider may hold one slot per category per city; territories are capped at seven Providers…</p></div></div>', foot='<button class="btn-outline btn-sm"><i class="bi bi-file-earmark-pdf"></i> Download signed PDF</button>')
    right = card('Your signature', '<div class="card-body"><div class="note ok mb-3"><i class="bi bi-check-circle-fill"></i><div><strong>Signed</strong> 4 Jan 2025 · countersigned by InKozi, Inc.</div></div>' + kv([('Signer','Amir A. Ladan · Ladan Law, P.A.'),('Version','v1.4 (current)'),('Re-sign required','No')]) + '<div class="sig-pad mt-3" style="height:120px"><span class="sig-x">×</span><span class="sig-line"></span><em style="font-family:cursive;font-size:22px;color:var(--ink)">Amir A. Ladan</em></div></div>')
    shell('agreement.html', 'Agreement', 'agreement.html', 'Hosting agreement', two_col(left, right), sub='You signed this electronically before your first territory went live.')

    # ============ Settings ============
    left = card('Account', '<div class="card-body"><form data-demo><div class="row g-3"><div class="col-md-6">' + fld('Login email', inp('amir@ladanlaw.com')) + '</div><div class="col-md-6">' + fld('Mobile (SMS alerts)', inp('(407) 555-0100')) + '</div><div class="col-md-6">' + fld('Notification email', inp('leads@ladanlaw.com')) + '</div><div class="col-md-6">' + fld('Timezone', select(['America/New_York'])) + '</div></div></form></div>', foot='<button class="btn-brand" data-toast="Saved">Save</button>') + card('Password', '<div class="card-body"><form data-demo><div class="row g-3"><div class="col-md-4">' + fld('Current', inp('', '••••••••', 'password')) + '</div><div class="col-md-4">' + fld('New', inp('', '', 'password')) + '</div><div class="col-md-4">' + fld('Confirm', inp('', '', 'password')) + '</div></div></form></div>', foot='<button class="btn-outline" data-toast="Password updated">Update password</button>')
    right = card('Alerts', '<div class="card-body">' + switch('New inquiry','Email + SMS instantly') + switch('Live chat requests','Push + SMS') + switch('Q&A in my territories','Daily email') + switch('Marketing from InKozi','Monthly newsletter', False) + '</div>') + card('Danger zone', '<div class="card-body"><button class="btn-danger-soft w-100"><i class="bi bi-pause-circle"></i> Pause my profile</button><div class="muted mt-2" style="font-size:12.5px">Hides your profile and stops inquiries. Hosting continues until you cancel territories.</div></div>')
    shell('settings.html', 'Settings', 'settings.html', 'Settings', two_col(left, right))
