from gen_common import *

def build():
    use_admin()
    # ============ Questions ============
    rows = []
    for t, a, c, s, u, ans, v, st, w, by, anon in QUESTIONS:
        loc = f'{a} · {c}, {s}' if s else a
        rows.append([f'<a href="question-details.html" class="strong">{t}</a><div class="muted">{loc}</div>', uwho(u, 'Posted anonymously' if anon else f'{USERS[u][0]}, {USERS[u][1]}'), f'<span class="strong">{ans}</span>', f'<span class="muted">{v:,}</span>', pwho(by, PROV[by][1].split(' • ')[0]) if by else '<span class="muted">—</span>', status_pill(st), f'<span class="muted">{w}</span>', '<div class="actions"><a href="question-details.html" class="icon-btn"><i class="bi bi-eye"></i></a><button class="icon-btn"><i class="bi bi-eye-slash"></i></button><button class="icon-btn danger"><i class="bi bi-flag"></i></button></div>'])
    body = stats_row([('Questions','12,437','+11%',True,'bi-chat-square-text',[9,9.5,10,10.4,10.9,11.3,11.7,12,12.2,12.4],'all time · shown as 12k+'),('Answered','94%','+1.2%',True,'bi-check2-circle',[90,91,91,92,92,93,93,93,94,94]),('Avg. reply','18 min','−3 min',True,'bi-stopwatch',[26,25,24,23,22,21,20,19,18,18]),('Unanswered > 1h','7','+2',False,'bi-hourglass',[4,4,5,5,5,6,6,6,7,7],'needs a nudge')])
    body += card('', filters('Search questions', [('Practice area',['DUI / DWI','Family Law','Personal Injury','Immigration','Bankruptcy','Criminal Defense','Real Estate','Employment']),('Location',[f'{c}, {s}' for c, s, _ in CITIES]),('Status',['Answered','Awaiting answer','Flagged','Hidden','Closed']),('Sort',['Newest','Most viewed','Unanswered'])], chips=['All','Awaiting answer 7','Flagged 3','Anonymous']) + table([('Question','wide'),'Asked by',('Answers','num'),('Views','num'),'Top answer','Status','Asked',('','')], rows, total='12,437'))
    shell('questions.html', 'Q&A questions', 'questions.html', 'Q&amp;A questions', body, sub='Free public forum. Only verified lawyers can answer. Routed by territory rotation; category “Bail Bonds” goes straight to the county bail agent.', actions='<a href="../frontend/qa.html" target="_blank" class="btn-outline"><i class="bi bi-box-arrow-up-right"></i> Public Q&amp;A</a><button class="btn-brand"><i class="bi bi-lightning-charge"></i> Nudge unanswered</button>')

    # ============ Question details ============
    q = card('', f'<div class="card-body"><div class="d-flex justify-content-between gap-3 flex-wrap mb-3"><div class="d-flex gap-2 flex-wrap"><span class="tag">DUI / DWI</span><span class="tag">Orlando, FL</span>{status_pill("Answered")}</div><span class="muted" style="font-size:12.5px">Asked anonymously · 2 hours ago · 412 views · <span class="mono">q_7A21F</span></span></div><h2 style="font-size:20px;font-weight:800;letter-spacing:-.4px;margin-bottom:12px">Can I refuse a breathalyzer in Florida without losing my license?</h2><p class="quote">I was pulled over last night on I-4 for what the officer said was drifting between lanes. He asked me to do some roadside exercises and then to blow into the breathalyzer. I refused both. He took my license and handed me a paper.</p><p class="quote">I have never been in trouble before. Is my license automatically gone because I refused? Is there anything I should be doing right now?</p><div class="d-flex align-items-center gap-3 mt-3 flex-wrap">{uwho("Tom Becker", "Shown publicly as Anonymous · Orlando, FL")}<span class="muted" style="font-size:12.5px"><i class="bi bi-people"></i> 3 lawyer answers · <i class="bi bi-eye"></i> 412 views · urgency: high</span></div></div>', foot='<button class="btn-outline btn-sm"><i class="bi bi-pencil"></i> Edit</button><button class="btn-outline btn-sm"><i class="bi bi-arrow-left-right"></i> Re-categorise</button><button class="btn-outline btn-sm"><i class="bi bi-eye-slash"></i> Hide</button><button class="btn-danger-soft btn-sm"><i class="bi bi-flag"></i> Flag</button>')
    ans = ''
    for n, sub, txt, helpful, when, extra in [("Amir A. Ladan","Criminal Defense & DUI · Orlando, FL · 15 years · 4.9 ★ (128)","First, take a breath. A refusal is a serious problem but it is not the end of the road, and you have more control than you think. Florida's implied consent law means a refusal triggers a one-year administrative suspension, separate from criminal court. The single most important thing: you have 10 days from the arrest to request a formal review hearing with the DHSMV.",41,"9 min after", pill('brand','Most helpful')),("Maria E. Gonzalez","Criminal Defense · Orlando, FL · 4.7 ★ (72)","Agree with the answer above on the 10-day deadline, and I want to add one practical point. If this is truly a first refusal you may be eligible to waive the hearing in exchange for immediate hardship-license eligibility.",17,"41 min after",''),("John P. Morgan","DUI Defense · Orlando, FL · 4.8 ★ (96)","One thing nobody has mentioned: request the arrest report and any dash or body camera footage as soon as possible. Footage of the stop often decides whether “drifting between lanes” holds up.",9,"2 hrs after",'')]:
        ans += f'<li><div class="d-flex justify-content-between gap-3 flex-wrap w-100"><div class="who">{pav(n)}<div><strong>{n}</strong><span>{sub}</span></div></div><div class="d-flex gap-2 align-items-center flex-wrap">{extra}<span class="tag"><i class="bi bi-hand-thumbs-up"></i> Helpful · {helpful}</span><button class="icon-btn"><i class="bi bi-pencil"></i></button><button class="icon-btn danger"><i class="bi bi-eye-slash"></i></button></div></div><p class="quote mt-2 mb-1 w-100">{txt}</p><span class="muted" style="font-size:12px">{when}</span></li>'
    left = q + card('Lawyer answers', f'<div class="card-body"><ul class="list" style="display:grid;gap:0">{ans}</ul><div class="note mt-3"><i class="bi bi-info-circle-fill"></i><div>Answers are general information from independent attorneys and do not create an attorney-client relationship. This disclaimer is shown under every thread.</div></div></div>', hint='3 · verified attorneys only', tools='<select class="form-select form-select-sm" style="width:auto;border-radius:8px"><option>Most helpful</option><option>Newest</option></select>')
    right = card('Moderation', '<div class="card-body">' + kv([('Status',status_pill('Answered')),('Routed to','4 providers in DUI / DWI · Orlando'),('First reply','9 min · Amir A. Ladan'),('Visibility','Public forum · anonymous'),('Source','Ask KOZI iOS'),('User rating','★★★★★ “Very helpful”'),('Reports','None')]) + '</div>', foot='<button class="btn-outline btn-sm" data-toast="Thread closed">Close thread</button><button class="btn-brand btn-sm" data-toast="Marked as featured">Feature on Q&amp;A page</button>') \
        + card('Asked by', '<div class="card-body">' + uwho('Tom Becker','tom.becker@example.com', cls='lg') + '<a href="user-details.html" class="btn-outline btn-sm w-100 mt-3">Open user</a></div>') \
        + card('Related questions', '<div class="card-body"><ul class="list">' + ''.join(f'<li><div class="grow"><strong>{t}</strong><span>{n} answers · {a}</span></div><button class="icon-btn"><i class="bi bi-x-lg"></i></button></li>' for t, n, a in [("Is a first-offense DUI in Florida a felony or a misdemeanor?",4,"DUI / DWI"),("How much does a DUI lawyer cost in Orlando?",6,"DUI / DWI"),("Can I get a hardship license after a refusal?",2,"DUI / DWI"),("Will a DUI arrest show up on a background check if I'm not convicted?",3,"Criminal Defense")]) + '</ul><button class="btn-outline btn-sm w-100 mt-3"><i class="bi bi-plus-lg"></i> Add related</button></div>', hint='shown in sidebar')
    shell('question-details.html', 'Question · q_7A21F', 'questions.html', 'Question', two_col(left, right), crumbs=[("Dashboard","index.html"),("Q&amp;A questions","questions.html"),("q_7A21F",None)], actions='<a href="../frontend/question-details.html" target="_blank" class="btn-outline"><i class="bi bi-box-arrow-up-right"></i> View public</a><a href="questions.html" class="btn-outline"><i class="bi bi-arrow-left"></i> Back</a>')

    # ============ Default questions ============
    dq = [("DUI / DWI",["What should I do after a DUI arrest in Florida?","Can a DUI charge be reduced or dismissed?","How much does a DUI lawyer cost?","Will a DUI stay on my record?","Can I get a hardship license after a refusal?"]),("Family Law",["How is child custody decided in Florida?","Can my ex move out of state with our kids?","How long does a divorce take?"]),("Personal Injury",["Do I need a lawyer after a car accident?","How much is my injury claim worth?","What if the other driver is uninsured?"]),("Immigration",["How long is the H-1B grace period after a layoff?","Green card through marriage: what is the timeline?"]),("Bankruptcy",["Chapter 7 or Chapter 13?","Will bankruptcy wipe out my student loans?"]),("Bail Bonds",["How fast can a bond be posted?","What does a bail bond cost?"])]
    rows = []
    for cat, qs in dq:
        for i, qq in enumerate(qs):
            rows.append([f'<span class="strong">{qq}</span>', f'<span class="tag">{cat}</span>', f'<span class="muted">{[412,388,2310,144,388,266,268,190,301,222,140,530,177,744,120,96,88][len(rows) % 17]}</span>', '<div class="form-check form-switch mb-0"><input class="form-check-input" type="checkbox" checked></div>', f'<span class="muted">{i + 1}</span>', '<div class="actions"><button class="icon-btn"><i class="bi bi-pencil"></i></button><button class="icon-btn"><i class="bi bi-arrows-move"></i></button><button class="icon-btn danger"><i class="bi bi-trash"></i></button></div>'])
    body = two_col(card('', filters('Search default questions', [('Practice area',[c for c, _ in dq]),('Country',['United States'])]) + table([('Question','wide'),'Practice area',('Times asked','num'),'On',('Order','num'),('','')], rows, checks=False, foot=False), hint='canned questions on profiles and the Ask box'), card('Add default question', '<div class="card-body"><form data-demo>' + fld('Practice area', select([c for c, _ in dq])) + fld('Question', inp('', 'e.g. Can I expunge a first offense?')) + fld('Suggested answer', textarea('', 3), small='optional, shown to providers as a draft') + switch('Show on provider profiles','Under “Frequently Asked Questions”') + switch('Show in the Ask box','Quick-pick list before free text') + '<button class="btn-brand w-100 mt-3">Add question</button></form></div>') + card('How they are used', '<div class="card-body"><ul class="list"><li><span class="avatar sq soft"><i class="bi bi-person-badge"></i></span><div class="grow"><strong>Provider profiles</strong><span>Providers pick 4 to show with their own answers</span></div></li><li><span class="avatar sq soft"><i class="bi bi-chat-square-text"></i></span><div class="grow"><strong>Ask a question flow</strong><span>Users tap a default question or type their own</span></div></li><li><span class="avatar sq soft"><i class="bi bi-robot"></i></span><div class="grow"><strong>Kozi assistant</strong><span>Suggested prompts in chat</span></div></li></ul></div>'))
    shell('default-questions.html', 'Default questions', 'default-questions.html', 'Default questions', body, sub='Canned questions per practice area, offered on provider profiles, in the Ask box and to Kozi.', actions='<button class="btn-brand"><i class="bi bi-plus-lg"></i> Add question</button>')

    # ============ Reviews ============
    data = [("Jasmine R.","Jasmine Rivera","Amir A. Ladan",5,"Amir was amazing! He explained everything clearly and got my case dismissed. Highly recommend!","Published","2 weeks ago"),("Michael T.","Michael Turner","Amir A. Ladan",5,"Professional, responsive, and truly cared about my case. Best DUI lawyer in Orlando.","Published","1 month ago"),("David L.","David Lopez","Amir A. Ladan",5,"Great communication and very knowledgeable. Case outcome was better than I expected.","Published","2 months ago"),("Aisha K.","Aisha Khan","Sarah J. Connor",5,"Sarah explained the relocation statute in plain English and had a plan within a day.","Pending","3 hrs ago"),("Carlos M.","Carlos Mendez","Harvey Specter",4,"Very knowledgeable, took a couple of days to get a call back.","Pending","Yesterday"),("Anonymous","Victor Alves","Omar Haddad",1,"Terrible, never called me back and charged me anyway!!!","Reported","5 hrs ago")]
    rows = [[uwho(u, f'Shown as {d} · {w}'), pwho(p), stars(r), f'<span class="quote">{t}</span>', status_pill(st), '<div class="actions"><button class="icon-btn" data-toast="Review approved"><i class="bi bi-check-lg"></i></button><button class="icon-btn danger" data-toast="Review hidden"><i class="bi bi-eye-slash"></i></button><button class="icon-btn"><i class="bi bi-three-dots"></i></button></div>'] for d, u, p, r, t, st, w in data]
    body = stats_row([('Reviews','4,206','+212',True,'bi-star',[30,31,33,34,36,37,38,40,41,42]),('Average rating','4.8','+0.1',True,'bi-star-half',[4.6,4.6,4.7,4.7,4.7,4.8,4.8,4.8,4.8,4.8]),('Pending','3','',True,'bi-hourglass',[6,5,5,4,4,4,3,3,3,3],'awaiting moderation'),('Reported by providers','1','',True,'bi-flag',[2,2,2,1,1,1,1,1,1,1])])
    body += '<div class="note mb-20"><i class="bi bi-shield-check"></i><div>Only people who connected with a provider through InKozi can leave a review, one per provider. Names are shortened to first name and initial on the public profile.</div></div>'
    body += card('', filters('Search reviews', [('Status',['Published','Pending','Reported','Hidden']),('Rating',['5 stars','4 stars','3 stars','2 stars','1 star']),('Provider',list(PROV)[:8]),('Type',['Lawyer','Affiliate'])], chips=['All','Pending 3','Reported 1']) + table(['Reviewer','Provider','Rating',('Review','wide'),'Status',('','')], rows, total='4,206', shown='1–6'))
    shell('reviews.html', 'Reviews', 'reviews.html', 'Reviews', body, sub='Client reviews shown on provider and affiliate profiles and on search cards.', actions='<button class="btn-outline"><i class="bi bi-gear"></i> Moderation rules</button>')

    # ============ Live chat ============
    convs = [("Jasmine Rivera","Amir A. Ladan","Live Chat · DUI hearing follow-up","Active","2 min ago","12 min",8),("Carlos Mendez","Kozi","Chat with Kozi · “Do I need a lawyer for a car accident?”","Active","5 min ago","4 min",6),("Aisha Khan","Sarah J. Connor","Live Chat · relocation paperwork","Waiting","18 min ago","—",1),("Hannah Reed","Kozi","Chat with Kozi · “How much does a DUI lawyer cost?”","Ended","1 hr ago","6 min",9),("Lucas Nguyen","John P. Morgan","Live Chat · court date 22 Sep","Ended","3 hrs ago","21 min",24),("Priya Natarajan","Kozi","Chat with Kozi → handed to Elena Rodriguez","Ended","Yesterday","9 min",11)]
    rows = [[uwho(u), pwho(p, 'Lawyer · usually responds in under 5 min') if p != 'Kozi' else '<div class="who"><img class="avatar" src="assets/images/kozi-mascot.png" alt=""><div><strong>Kozi</strong><span>AI assistant</span></div></div>', f'<span class="strong">{t}</span>', status_pill(st), f'<span class="muted">{d}</span>', f'<span class="muted">{m}</span>', f'<span class="muted">{w}</span>', '<div class="actions"><button class="icon-btn" data-bs-toggle="tooltip" title="Open transcript"><i class="bi bi-chat-text"></i></button><button class="icon-btn danger" data-bs-toggle="tooltip" title="Escalate"><i class="bi bi-exclamation-triangle"></i></button></div>'] for u, p, t, st, w, d, m in convs]
    body = stats_row([('Chats today','312','+14%',True,'bi-chat-dots',[20,22,24,26,27,28,29,30,31,31]),('Lawyer median reply','4 min','−1 min',True,'bi-stopwatch',[6,6,5.5,5.5,5,5,4.5,4.5,4,4],'“usually responds in under 5 minutes”'),('Kozi → lawyer handoffs','41%','+5%',True,'bi-robot',[32,33,34,35,36,37,38,39,40,41]),('Escalated','2','',True,'bi-exclamation-triangle',[4,4,3,3,3,2,2,2,2,2],'needs staff')])
    body += '<div class="grid grid-8-4">' + card('', filters('Search conversations', [('Type',['Live Chat with lawyer','Chat with Kozi']),('Status',['Active','Waiting','Ended','Escalated']),('Provider',list(PROV)[:8])], chips=['All','Active 2','Waiting 1','Escalated 2']) + table(['User','With',('Conversation','mid'),'Status','Duration',('Messages','num'),'Last activity',('','')], rows, checks=False, total='2,418', shown='1–6')) \
        + card('Kozi assistant', '<div class="card-body"><div class="d-flex align-items-center gap-3 mb-3"><img src="assets/images/kozi-mascot.png" alt="" style="width:56px;border-radius:50%"><div><strong style="font-size:15px">Ask Kozi — Get Legal Help</strong><div class="muted" style="font-size:12.5px">Widget on profiles, Q&amp;A and search</div></div></div>' + fld('Greeting', textarea("Not sure what you need? Ask Kozi and we'll guide you.", 2)) + fld('Button label', inp('Chat with Kozi')) + switch('Hand off to Live Chat','Offer a lawyer in the user\'s territory when intent is clear') + switch('Chat request must be accepted','Lawyer accepts before the room opens') + switch('Disclaimer','“InKozi does not provide legal advice” on every chat') + switch('Ask KOZI app','Same assistant on iOS and Android') + '</div>', foot='<a href="kozi-intake.html" class="btn-outline btn-sm">Intake rules</a><button class="btn-brand btn-sm" data-toast="Kozi settings saved">Save</button>') + '</div>'
    shell('live-chat.html', 'Live chat', 'live-chat.html', 'Live chat', body, sub='Live Chat between users and lawyers (with an accept step), plus conversations with the Kozi assistant.', actions='<button class="btn-outline"><i class="bi bi-download"></i> Export transcripts</button>')

    # ============ Kozi AI intake ============
    stp = [("When did this happen?","Date picker","All"),("Which county or city?","Location · matches territory radius","All"),("Have you already hired a lawyer?","Yes / No · filters out represented users","All"),("Did you take a breath, blood or urine test?","Yes / No / Refused","DUI / DWI"),("Is this your first offense?","Yes / No","DUI / DWI"),("Do you have a court date?","Date · optional","DUI / DWI"),("Were you injured? Did you get treatment?","Yes / No + free text","Personal Injury"),("Is there an existing custody order?","Yes / No","Family Law")]
    rows = [[f'<span class="strong">{q}</span>', f'<span class="muted">{t}</span>', f'<span class="tag">{a}</span>', '<div class="form-check form-switch mb-0"><input class="form-check-input" type="checkbox" checked></div>', '<div class="actions"><button class="icon-btn"><i class="bi bi-pencil"></i></button><button class="icon-btn"><i class="bi bi-arrows-move"></i></button></div>'] for q, t, a in stp]
    body = stats_row([('Inquiries screened','1,184','+18%',True,'bi-robot',[70,74,80,86,90,96,100,108,112,118],'last 30 days'),('Filtered as noise','23%','−2%',True,'bi-funnel',[27,27,26,26,25,25,24,24,23,23]),('Avg. completion','1m 40s','−12s',True,'bi-stopwatch',[2.2,2.1,2.1,2.0,1.9,1.9,1.8,1.8,1.7,1.7]),('Relevance score avg.','84','+3',True,'bi-bullseye',[76,77,78,79,80,81,82,83,83,84],'0–100')])
    left = card('Intake questionnaire', filters('Search questions', [('Practice area',['All areas'] + AREAS[:8])], extra='<button class="btn-outline btn-sm"><i class="bi bi-plus-lg"></i> Add question</button>') + table([('Question','mid'),('Answer type','mid'),'Applies to','On',('','')], rows, checks=False, foot=False), hint='asked before a question reaches providers') \
        + card('Screening & routing rules', '<div class="card-body">' + switch('Block spam and off-topic text','Links, promo language and repeated posts are hidden automatically') + switch('Require a location inside a live territory','Users outside coverage are told when their city opens') + switch('Minimum relevance score to deliver','Inquiries below 40 are held for staff review') + switch('Skip already-represented users','“Have you already hired a lawyer?” = Yes ends the intake politely') + switch('Fair rotation','First provider gets every lead until slot two fills, then round-robin by slot number and last-used') + switch('Fallback to preferred lawyer','If no provider holds the territory, deliver to the preferred fallback') + switch('Copy personal-injury leads to connected chiropractor','Email + SMS to the partner when the lawyer has a connection') + '</div>', foot='<button class="btn-brand btn-sm" data-toast="Rules saved">Save rules</button>')
    right = card('Held for review', '<div class="card-body"><ul class="list">' + ''.join(f'<li><div class="grow"><strong>{t}</strong><span>{d}</span></div>{pill("warn", str(s))}</li>' for t, d, s in [("“How much for a lawyer?” · DUI · Orlando","Hannah Reed · cost question only",41),("Out-of-state license · DUI · Orlando","Anonymous · no Florida location",12),("Rear-ended, $1,800 offer · PI · Tampa","Carlos Mendez · awaiting provider",84)]) + '</ul><button class="btn-outline btn-sm w-100 mt-3">Review all 14</button></div>', hint='score below threshold') \
        + card('Score model', '<div class="card-body">' + ''.join(f'<div class="bar-row"><span class="lbl">{l}</span><div class="bar thin"><span style="width:{p}%"></span></div><span class="val">{p}%</span></div>' for l, p in [("Practice-area match",30),("Location match",25),("Urgency signals",20),("Detail quality",15),("Contact reachable",10)]) + '<div class="muted mt-2" style="font-size:12.5px">Weights sum to 100. Changing them re-scores held inquiries.</div></div>')
    shell('kozi-intake.html', 'Kozi AI intake', 'kozi-intake.html', 'Kozi AI intake', body + two_col(left, right), sub='The smart intake questionnaire that screens inquiries before they reach a provider’s dashboard, and the routing rules.', actions='<a href="live-chat.html" class="btn-outline"><i class="bi bi-chat-dots"></i> Kozi assistant</a><button class="btn-brand"><i class="bi bi-play-fill"></i> Preview intake</button>')

    # ============ Payments & invoices ============
    data = [("inv_2026_09_4412","Sarah J. Connor","Territory hosting · Family Law · Miami","$45.00","Paid","Visa •• 4242","14 Sep 2026"),("inv_2026_09_4411","Amir A. Ladan","Territory hosting · DUI / DWI · Orlando","$45.00","Paid","Mastercard •• 8810","14 Sep 2026"),("inv_2026_09_4410","Amir A. Ladan","Territory hosting · Criminal Defense · Orlando","$45.00","Paid","Mastercard •• 8810","14 Sep 2026"),("inv_2026_09_4409","Rachel Kim","Set-up & administration fee · Tampa · DUI / DWI","$375.00","Due","—","14 Sep 2026"),("inv_2026_09_4402","Omar Haddad","Territory hosting · Bail Bonds · Fort Lauderdale","$45.00","Failed","Amex •• 3007","12 Sep 2026"),("inv_2026_09_4398","Michael T. Ross","Territory hosting · Corporate Law · Tampa","$45.00","Paid","Visa •• 9931","11 Sep 2026"),("inv_2026_09_4371","Jessica Pearson","Set-up & administration fee · Jacksonville · Real Estate","$375.00","Paid","Mastercard •• 2201","8 Sep 2026"),("inv_2026_09_4366","David Kim","Territory hosting · Bankruptcy · Los Angeles","$45.00","Paid","PayPal","6 Sep 2026")]
    rows = [[f'<span class="mono">{i}</span>', pwho(p, d), f'<span class="strong">{a}</span>', status_pill(st).replace('>Failed<','>Failed · retry 2/3<'), f'<span class="muted"><i class="bi bi-credit-card me-1"></i>{m}</span>', f'<span class="muted">{w}</span>', '<div class="actions"><button class="icon-btn" data-bs-toggle="tooltip" title="Invoice PDF"><i class="bi bi-file-earmark-pdf"></i></button><button class="icon-btn" data-bs-toggle="tooltip" title="Mark paid"><i class="bi bi-check2-circle"></i></button><button class="icon-btn" data-bs-toggle="tooltip" title="Retry / refund"><i class="bi bi-arrow-repeat"></i></button></div>'] for i, p, d, a, st, m, w in data]
    body = stats_row([('Revenue this month','$103,425','+7.1%',True,'bi-cash-stack',[86,88,90,92,94,96,98,100,102,103],'hosting + set-up fees'),('Territory MRR','$96,300','+6.8%',True,'bi-graph-up-arrow',[80,82,84,86,88,90,91,93,95,96],'2,140 slots × $45'),('Invoices due','14','$1,830',True,'bi-receipt',[12,13,14,15,16,17,17,18,19,14],'awaiting payment'),('Failed renewals','9','+2',False,'bi-x-octagon',[5,5,6,6,7,7,8,8,9,9],'retrying automatically')])
    body += card('Revenue', '<div class="card-body"><div class="chart-box sm"><canvas id="chart-revenue"></canvas></div></div>', tools='<div class="legend"><span><i style="background:#8c1fa9"></i> $45 hosting</span><span><i style="background:#F9A8D4"></i> $375 set-up fees</span></div><button class="btn-outline btn-sm"><i class="bi bi-calendar3"></i> Last 12 months</button>', hint='$ thousands', cls='mb-20')
    body += '<div class="note mb-20"><i class="bi bi-info-circle-fill"></i><div>Hosting renews every 30 days and is <strong>non-refundable once a profile is live</strong>. Set-up fees are charged only after verification is approved. Providers can pay open invoices by card, PayPal or Stripe from their portal.</div></div>'
    body += card('', filters('Search invoice, provider or card', [('Status',['Paid','Due','Failed','Refunded']),('Type',['Territory hosting $45','Set-up fee $375']),('Gateway',['Stripe','PayPal','Authorize.net'])], extra='<button class="btn-outline btn-sm"><i class="bi bi-calendar3"></i> Sep 2026</button><button class="btn-outline btn-sm"><i class="bi bi-plus-lg"></i> Create invoice</button>') + table(['Invoice',('Provider','mid'),('Amount','num'),'Status','Method','Date',('','')], rows, total='4,412', shown='1–8'))
    shell('payments.html', 'Payments & invoices', 'payments.html', 'Payments &amp; invoices', body, sub='Every hosting renewal, set-up fee and manual invoice across all providers.', actions='<button class="btn-outline"><i class="bi bi-download"></i> Export</button><button class="btn-outline"><i class="bi bi-stripe"></i> Open Stripe</button><button class="btn-brand"><i class="bi bi-plus-lg"></i> Manual charge</button>', charts=True)

    # ============ Hosting & pricing ============
    plan = card('Territory Hosting', '<div class="card-body"><div class="d-flex justify-content-between align-items-start flex-wrap gap-3"><div><div class="section-title mb-1">Per category &amp; city</div><div style="font-size:34px;font-weight:800;letter-spacing:-1px;color:var(--ink)">$45 <span style="font-size:14px;font-weight:600;color:var(--muted)">/ month</span></div><div class="muted" style="font-size:13px">plus a one-time <strong style="color:var(--ink)">$375</strong> administration &amp; set-up fee</div></div>' + pill('brand','Live on for-lawyers page') + '</div><ul class="list mt-3">' + ''.join(f'<li><i class="bi bi-check-circle-fill" style="color:var(--green)"></i><span style="font-size:13.5px">{f}</span></li>' for f in ["One exclusive slot in a 7-provider territory","Instant inquiry alerts to your dashboard","Verified badge and SEO-optimised profile URL","AI-screened, location-matched leads","Blog, social and phone/email support services","30-day pay-as-you-go, cancel any time"]) + '</ul><div class="row g-3 mt-2"><div class="col-md-3">' + fld('Monthly hosting', inp('45'), small='USD') + '</div><div class="col-md-3">' + fld('Set-up fee', inp('375'), small='USD, one-time') + '</div><div class="col-md-3">' + fld('Extra practice area', inp('45'), small='USD / mo') + '</div><div class="col-md-3">' + fld('Billing cycle', select(['30 days','Calendar month'], '30 days')) + '</div></div><div class="muted" style="font-size:12.5px">Approval within 48 hours. Hosting renews monthly and is non-refundable once live.</div></div>', foot='<button class="btn-brand btn-sm" data-toast="Pricing saved">Save pricing</button>')
    aff = card('Affiliate listing', '<div class="card-body"><div class="section-title mb-1">Free</div><div style="font-size:34px;font-weight:800;letter-spacing:-1px;color:var(--ink)">$0</div><div class="muted" style="font-size:13px">Free brand promotion for local businesses, approved within 48 hours</div><ul class="list mt-3">' + ''.join(f'<li><i class="bi bi-check-circle-fill" style="color:var(--green)"></i><span style="font-size:13.5px">{f}</span></li>' for f in ["Listed in search by location and category","Cross-linking and deep linking to related services","Coupons and promo codes","Community partnerships"]) + '</ul></div>')
    cmp = '<div class="table-wrap"><table class="tbl"><thead><tr><th>What you get</th><th>InKozi</th><th>Typical directory</th></tr></thead><tbody>' + ''.join(f'<tr><td class="strong">{a}</td><td><span class="pill ok nodot">{b}</span></td><td><span class="muted">{c}</span></td></tr>' for a, b, c in [("Providers per city & category","Max 7","Unlimited"),("Pay-per-click or per-lead","Never","Usually"),("Share of your fees","0%","Varies"),("Long-term contract","None","6–12 months"),("Client screening","AI intake","None"),("Lead delivery","Instant alert","Email digest")]) + '</tbody></table></div>'
    subs = [("Amir A. Ladan",2,"$90.00","Active","1 Oct 2026"),("Sarah J. Connor",2,"$90.00","Active","1 Oct 2026"),("Maria E. Gonzalez",2,"$90.00","Active","4 Oct 2026"),("Michael T. Ross",1,"$45.00","Active","11 Oct 2026"),("Jessica Pearson",1,"$45.00","Active","8 Oct 2026"),("John P. Morgan",1,"$45.00","Active","2 Oct 2026"),("David Kim",1,"$45.00","Active","6 Oct 2026"),("Omar Haddad",1,"$45.00","Past due","12 Sep 2026"),("Laura Chen",1,"$45.00","Cancelling","30 Sep 2026")]
    rows = [[pwho(n), f'<span class="strong">{t}</span>', f'<span class="strong">{a}</span>', status_pill(st).replace('>Cancelling<','>Cancels 30 Sep<'), f'<span class="muted">{nx}</span>', '<div class="actions"><button class="icon-btn"><i class="bi bi-pencil"></i></button><button class="icon-btn"><i class="bi bi-pause"></i></button><button class="icon-btn danger"><i class="bi bi-x-circle"></i></button></div>'] for n, t, a, st, nx in subs]
    body = stats_row([('Active hosting','2,140','+29',True,'bi-arrow-repeat',[1800,1840,1880,1920,1960,2000,2040,2080,2110,2140],'territory slots'),('Providers billed','1,796','+22',True,'bi-briefcase',[15.5,16,16.4,16.8,17,17.3,17.5,17.7,17.8,17.9],'avg 1.19 territories each'),('Churn','1.9%','−0.3%',True,'bi-graph-down',[2.6,2.5,2.4,2.4,2.3,2.2,2.1,2.0,2.0,1.9],'per 30-day cycle'),('Past due','9','+2',False,'bi-exclamation-circle',[4,5,5,6,6,7,7,8,8,9])])
    body += '<div class="grid grid-8-4 mb-20"><div>' + plan + '</div><div>' + aff + '</div></div>'
    body += '<div class="grid grid-8-4">' + card('', filters('Search provider', [('Status',['Active','Past due','Cancelling']),('Territories',['1','2','3+'])]) + table(['Provider',('Territories','num'),('Monthly','num'),'Status','Next renewal',('','')], rows, checks=False, total='1,796', shown='1–9')) + card('Compared with directories', cmp, hint='shown on the pricing page') + '</div>'
    shell('subscriptions.html', 'Hosting & pricing', 'subscriptions.html', 'Hosting &amp; pricing', body, sub='One flat rate. No surprises. $45 / month per territory plus a one-time $375 set-up fee. Failed renewals release the slot after the third retry.', actions='<a href="../frontend/for-lawyers.html" target="_blank" class="btn-outline"><i class="bi bi-box-arrow-up-right"></i> Pricing page</a><a href="coupons.html" class="btn-outline"><i class="bi bi-tag"></i> Promo codes</a>')
