from gen_common import *

ANAV = [
  ("Overview", [("index.html","bi-grid-1x2-fill","Dashboard",None),("notifications.html","bi-bell-fill","Notifications","3")]),
  ("My listing", [("profile.html","bi-shop","Business profile",None),("cities.html","bi-geo-alt-fill","Cities & slots",None),("ads.html","bi-badge-ad-fill","Advertisements",None),("connections.html","bi-diagram-3-fill","Partner lawyers","1")]),
  ("Offers", [("coupons.html","bi-ticket-perforated-fill","Coupons & promo codes",None),("leads.html","bi-hand-index-thumb-fill","Coupon leads","4")]),
  ("Leads", [("inquiries.html","bi-send-fill","Inquiries","2"),("insights.html","bi-bar-chart-line-fill","Listing views",None)]),
  ("Billing", [("billing.html","bi-credit-card-2-front-fill","Billing",None)]),
  ("Account", [("settings.html","bi-gear-fill","Settings",None)]),
]
BIZ = "Sunshine State Bail Bonds"

def build():
    use_site(ROOT + 'affiliate/', 'Affiliate', ANAV, (BIZ, 'SB', 'Bail agent · Orlando', None), 'Search leads, coupons, cities…', [("coupons.html","bi-ticket-perforated","New coupon"),("cities.html","bi-geo-alt","Add a city"),("ads.html","bi-badge-ad","New ad")], public_link='../frontend/search.html')

    # ============ Dashboard ============
    body = stats_row([('Listing views','1,204','+22%',True,'bi-eye',[80,85,90,95,100,105,110,115,118,120],'last 30 days'),('Coupon requests','38','+9',True,'bi-hand-index',[20,22,24,26,28,30,32,34,36,38]),('Inquiries','12','+3',True,'bi-send',[6,7,7,8,9,9,10,11,11,12],'bail-bond questions · Orange County'),('Partner lawyers','4','+1',True,'bi-diagram-3',[2,2,3,3,3,3,4,4,4,4],'cross-links')])
    leads = table([('Lead','wide'),'Type','Status','Received',('','')], [['<span class="strong">Bail set at $25k · misdemeanor</span><div class="muted">Sofia Martins · Fort Lauderdale · needs release tonight</div>', '<span class="tag">Inquiry</span>', status_pill('New'), '<span class="muted">Yesterday</span>', '<div class="actions"><button class="btn-brand btn-xs"><i class="bi bi-telephone"></i> Call</button></div>'],['<span class="strong">SUNSHINE10 coupon request</span><div class="muted">Tom Becker · Orlando</div>', '<span class="tag">Coupon</span>', status_pill('New'), '<span class="muted">1 hr ago</span>', '<div class="actions"><button class="btn-outline btn-xs">Mark redeemed</button></div>'],['<span class="strong">Referral from Amir A. Ladan</span><div class="muted">Lucas Nguyen · DUI · Orlando</div>', '<span class="tag">Partner</span>', status_pill('Connected'), '<span class="muted">3 days ago</span>', '<div class="actions"><button class="icon-btn"><i class="bi bi-eye"></i></button></div>']], checks=False, foot=False)
    body += '<div class="grid grid-8-4 mb-20">' + card('Latest leads', leads, tools='<a href="inquiries.html" class="btn-ghost btn-sm">All leads</a>') + card('Your listing', '<div class="card-body">' + kv([('Status',status_pill('Approved')),('Category','Bail agent'),('Cities','Orlando, Kissimmee, Sanford'),('Page','inkozi.com/best-bail-bonds/orlando-florida/sunshine-state'),('Fee','$0 · free listing')]) + '<a href="../frontend/search.html" target="_blank" class="btn-outline btn-sm w-100 mt-3"><i class="bi bi-box-arrow-up-right"></i> View public page</a></div>') + '</div>'
    body += '<div class="grid grid-8-4">' + card('Listing views', '<div class="card-body"><div class="chart-box sm"><canvas id="chart-response"></canvas></div></div>', hint='last 14 days') + card('Partner lawyers', '<div class="card-body"><ul class="list">' + ''.join(f'<li>{pav(n)}<div class="grow"><strong>{n}</strong><span>{PROV[n][1]}</span></div>{status_pill("Active")}</li>' for n in ["Amir A. Ladan","John P. Morgan","Daniel Whitaker"]) + '</ul><a href="connections.html" class="btn-ghost btn-sm w-100 mt-2">Manage</a></div>') + '</div>'
    shell('index.html', 'Dashboard', 'index.html', 'Welcome back', body, sub='Sunshine State Bail Bonds · free affiliate listing · 3 cities', crumbs=[("Dashboard", None)], actions='<a href="coupons.html" class="btn-outline"><i class="bi bi-ticket-perforated"></i> New coupon</a><a href="cities.html" class="btn-brand"><i class="bi bi-geo-alt"></i> Add a city</a>', charts=True)

    # ============ Notifications ============
    items = [("bi-send-fill","warn","New bail inquiry from <strong>Sofia Martins</strong> in Fort Lauderdale (outside your cities · offered as overflow).","Yesterday","inquiries.html",True),("bi-hand-index-thumb-fill","","<strong>Tom Becker</strong> requested your SUNSHINE10 coupon.","1 hr ago","leads.html",True),("bi-diagram-3-fill","","<strong>Daniel Whitaker</strong> wants to connect as a partner lawyer.","Yesterday","connections.html",True),("bi-check-circle-fill","ok","Your listing for <strong>Sanford, FL</strong> was approved.","3 days ago","cities.html",False)]
    lis = ''.join(f'<li{" style=\"background:#FCFCFF\"" if u else ""}><span class="t-dot {k}" style="width:36px;height:36px;border-radius:11px;display:inline-flex;align-items:center;justify-content:center;flex:0 0 auto"><i class="bi {ic}"></i></span><div class="grow"><span style="font-size:13.5px;color:var(--ink-2)">{t}</span><span>{w}</span></div><a href="{h}" class="btn-outline btn-xs">Open</a></li>' for ic, k, t, w, h, u in items)
    shell('notifications.html', 'Notifications', 'notifications.html', 'Notifications', two_col(card('', f'<div class="card-body"><ul class="list">{lis}</ul></div>'), card('Alerts', '<div class="card-body">' + switch('Inquiries','Email + SMS') + switch('Coupon requests','Email') + switch('Partner requests','Email') + '</div>')))

    # ============ Business profile ============
    left = card('Business', '<div class="card-body"><div class="profile-hero mb-4">' + av(BIZ, cls='xl') + '<div><h2>' + BIZ + ' ' + status_pill('Approved') + '</h2><div class="meta"><span><i class="bi bi-link-45deg"></i> inkozi.com/best-bail-bonds/orlando-florida/sunshine-state</span><span><i class="bi bi-eye"></i> 1,204 views · 30 days</span></div></div><div class="spacer"></div><button class="btn-outline btn-sm"><i class="bi bi-camera"></i> Logo</button></div><div class="row g-3"><div class="col-md-6">' + fld('Business name', inp(BIZ)) + '</div><div class="col-md-6">' + fld('Category', select(['Bail agent','Chiropractor','Towing','Notary','Process server'], 'Bail agent')) + '</div><div class="col-12">' + fld('Description', textarea('Licensed bail agents serving Orange County 24 hours a day. Payment plans available, most releases in under two hours.', 3)) + '</div><div class="col-md-8">' + fld('Address', inp('500 S Hughey Ave')) + '</div><div class="col-md-4">' + fld('Suite', inp('')) + '</div><div class="col-md-4">' + fld('City', inp('Orlando')) + '</div><div class="col-md-4">' + fld('State', select(STATES, 'Florida')) + '</div><div class="col-md-4">' + fld('ZIP', inp('32801')) + '</div><div class="col-md-4">' + fld('Phone', inp('(407) 555-0199')) + '</div><div class="col-md-4">' + fld('Website', inp('sunshinebail.com')) + '</div><div class="col-md-4">' + fld('Year established', inp('2009')) + '</div><div class="col-md-6">' + fld('Hours', inp('24/7')) + '</div><div class="col-md-6">' + fld('Video link', inp('', 'YouTube URL')) + '</div><div class="col-12">' + fld('Payment methods', '<div class="d-flex flex-wrap gap-2">' + ''.join(f'<span class="chip active">{x}</span>' for x in ["Cash","Credit cards","Payment plans"]) + '</div>') + '</div></div></div>', foot='<button class="btn-ghost">Discard</button><button class="btn-brand" data-toast="Profile saved">Save</button>')
    right = card('Verification', '<div class="card-body">' + kv([('License','FL Bail Agent #BA-2210 · verified'),('Approved','2 Mar 2026'),('Background check','Clear')]) + '</div>') + card('Reviews', '<div class="card-body"><div class="d-flex align-items-center gap-2 mb-2">' + stars(4.6) + '<strong>4.6</strong><span class="muted">(31)</span></div><ul class="list"><li>' + av('Lucas N.') + '<div class="grow"><strong>Lucas N. ' + stars(5) + '</strong><span>Out in 90 minutes, exactly as promised.</span></div></li></ul></div>') + card('Photos', '<div class="card-body"><div class="grid grid-2" style="gap:8px">' + ''.join(f'<div class="cover" style="padding:18px 8px"><i class="bi bi-image"></i>{x}</div>' for x in ["Storefront","Office","+ Add"]) + '</div></div>')
    shell('profile.html', 'Business profile', 'profile.html', 'Business profile', two_col(left, right), sub='What people see on your InKozi page and in search.', actions='<a href="../frontend/search.html" target="_blank" class="btn-outline"><i class="bi bi-eye"></i> Preview</a><button class="btn-brand" data-toast="Published"><i class="bi bi-check-lg"></i> Publish</button>')

    # ============ Cities & slots ============
    rows = [[f'<span class="strong">{c}, FL</span><div class="muted">{co} County</div>', f'<span class="strong">{s} of 9</span>', status_pill(st), f'<span class="muted">{v}</span>', f'<span class="muted">{d}</span>', '<div class="actions"><a href="../frontend/search.html" target="_blank" class="icon-btn"><i class="bi bi-box-arrow-up-right"></i></a><button class="icon-btn danger"><i class="bi bi-x-circle"></i></button></div>'] for c, co, s, st, v, d in [("Orlando","Orange","3","Approved","1,204","2 Mar 2026"),("Kissimmee","Osceola","2","Approved","318","20 Apr 2026"),("Sanford","Seminole","1","Approved","96","11 Sep 2026"),("Winter Park","Orange","—","Pending","—","Requested yesterday")]]
    claim = card('Add a city', '<div class="card-body">' + steps(["Choose city","Confirm details","Approval (48 h)"], 0) + '<div class="row g-3"><div class="col-md-4">' + fld('State', select(STATES, 'Florida')) + '</div><div class="col-md-4">' + fld('County', select(['Orange','Osceola','Seminole','Lake','Volusia'], 'Lake')) + '</div><div class="col-md-4">' + fld('City', select(['Clermont','Leesburg','Mount Dora'], 'Clermont')) + '</div></div><div class="note"><i class="bi bi-info-circle-fill"></i><div><strong>Clermont, FL · Bail agent:</strong> 7 of 9 advertiser slots open. Listing is free; approval takes about 48 hours.</div></div></div>', foot='<button class="btn-brand" data-toast="Request sent · we will approve within 48 hours">Request listing <i class="bi bi-arrow-right"></i></button>')
    shell('cities.html', 'Cities & slots', 'cities.html', 'Cities &amp; slots', card('My cities', table([('City','mid'),'Slot','Status',('Views · 30d','num'),'Since',('','')], rows, checks=False, foot=False), hint='max 9 advertisers per city · bail agents are matched by county') + '<div class="mt-4"></div>' + claim, sub='Where your listing appears. Add as many cities as you serve.')

    # ============ Advertisements ============
    ads = [("Out in under 2 hours, 24/7","DUI & Criminal lawyer profiles · Orlando","Included with partner connection","Active","8,120","Ongoing"),("Payment plans available","Search results · Orlando bail bonds","Sponsored · $14.95 / mo","Paused","2,050","Paused 10 Sep")]
    rows = [[f'<div class="who"><span class="avatar sq soft"><i class="bi bi-image"></i></span><div><strong>{h}</strong><span>270 × 90 creative</span></div></div>', f'<span class="muted">{p}</span>', f'<span class="tag">{t}</span>', status_pill(st), f'<span class="strong">{i}</span>', f'<span class="muted">{d}</span>', '<div class="actions"><button class="icon-btn"><i class="bi bi-pencil"></i></button><button class="icon-btn"><i class="bi bi-play"></i></button></div>'] for h, p, t, st, i, d in ads]
    body = two_col(card('My ads', table([('Creative','mid'),('Placement','mid'),'Type','Status',('Impressions','num'),'Schedule',('','')], rows, checks=False, foot=False)), card('New ad', '<div class="card-body"><form data-demo>' + fld('Headline', inp('', 'e.g. Out in under 2 hours')) + fld('Placement', select(['Partner lawyer profiles (included)','Search results · sponsored $14.95 / mo','Ask KOZI app · sponsored'])) + fld('Cities', inp('Orlando')) + '<div class="cover mb-3"><i class="bi bi-image"></i>Upload creative · 270 × 90</div><button class="btn-brand w-100">Create ad</button></form></div>') + card('How ads work', '<div class="card-body"><p class="muted" style="font-size:13px">Ads on your partner lawyers’ profiles are included with the connection. Sponsored placements in search results and the app cost $14.95 per month per city.</p></div>'))
    shell('ads.html', 'Advertisements', 'ads.html', 'Advertisements', body, sub='Creatives shown on partner lawyer profiles and, optionally, sponsored placements.')

    # ============ Partner lawyers ============
    body = two_col(card('Connected lawyers', '<div class="card-body"><ul class="list">' + ''.join(f'<li>{pav(n)}<div class="grow"><strong>{n}</strong><span>{PROV[n][1]} · {PROV[n][2]} · your ad on their profile · {r} referrals</span></div>{status_pill("Active")}<button class="icon-btn danger"><i class="bi bi-x-circle"></i></button></li>' for n, r in [("Amir A. Ladan",6),("John P. Morgan",3),("Maria E. Gonzalez",2),("Daniel Whitaker",0)]) + '</ul></div>', hint='4') + card('Requests', '<div class="card-body"><ul class="list"><li>' + pav('Daniel Whitaker') + '<div class="grow"><strong>Daniel Whitaker</strong><span>Traffic Violations · Orlando · sent yesterday</span></div><button class="btn-outline btn-xs">Decline</button><button class="btn-brand btn-xs" data-toast="Connected">Accept</button></li></ul></div>'), card('Find lawyers to partner with', '<div class="card-body"><form data-demo>' + fld('Practice area', select(['DUI / DWI','Criminal Defense','Traffic Violations'])) + fld('City', select([f'{c}, {s}' for c, s, _ in CITIES], 'Orlando, FL')) + '<ul class="list mt-2">' + ''.join(f'<li>{pav(n)}<div class="grow"><strong>{n}</strong><span>{PROV[n][1]}</span></div><button class="btn-outline btn-xs" data-toast="Request sent">Connect</button></li>' for n in ["Laura Chen"] if False) + f'<li>{av("Grace Lee")}<div class="grow"><strong>Grace Lee</strong><span>Criminal Defense · Orlando · 4.8</span></div><button class="btn-outline btn-xs" data-toast="Request sent">Connect</button></li></ul></form></div>') + card('Why connect?', '<div class="card-body"><p class="muted" style="font-size:13px">Your ad appears on the lawyer’s profile, they can refer clients who need a bond, and you appear together in search for that city.</p></div>'))
    shell('connections.html', 'Partner lawyers', 'connections.html', 'Partner lawyers', body, sub='Lawyers in your cities who refer clients and show your ad.')

    # ============ Coupons ============
    body = two_col(card('My coupons', '<div class="card-body"><div class="grid grid-2">' + ''.join(f'<div class="coupon-card"><div class="d-flex justify-content-between gap-2 align-items-start"><div><strong style="font-size:15px;color:var(--ink)">{t}</strong><div class="muted" style="font-size:12.5px">{d}</div></div>{status_pill(st)}</div><div class="d-flex justify-content-between align-items-end mt-3 flex-wrap gap-2"><div class="price">{p}</div><span class="code">{c}</span></div><div class="muted mt-2" style="font-size:12px">{r} requests · expires {e}</div></div>' for t, d, p, c, st, r, e in [("10% off any bond over $5,000","New clients · Orange County","10% off","SUNSHINE10","Active",38,"31 Dec 2026"),("No-fee payment plan","Bonds under $10,000","$0 fee<s>$150</s>","SUNSHINE-PLAN","Pending",0,"30 Nov 2026")]) + '</div></div>', hint='shown on your page, partner profiles and the deals directory'), card('New coupon', '<div class="card-body"><form data-demo>' + fld('Title', inp('')) + fld('Details', textarea('', 2)) + '<div class="row g-2"><div class="col-6">' + fld('Regular price', inp('', '$')) + '</div><div class="col-6">' + fld('Discounted', inp('', '$ or %')) + '</div></div>' + fld('Code', inp('')) + fld('Expires', inp('', '', 'date')) + '<div class="cover mb-3"><i class="bi bi-image"></i>Coupon image · 270 × 90</div><button class="btn-brand w-100">Submit for approval</button></form></div>'))
    shell('coupons.html', 'Coupons & promo codes', 'coupons.html', 'Coupons &amp; promo codes', body, sub='Deals reviewed by InKozi before publishing.', actions='<button class="btn-brand"><i class="bi bi-plus-lg"></i> New coupon</button>')

    # ============ Coupon leads ============
    rows = [[uwho(u), '<span class="strong">SUNSHINE10</span>', f'<span class="muted">{ph}</span>', status_pill(st), f'<span class="muted">{w}</span>', '<div class="actions"><button class="icon-btn"><i class="bi bi-telephone"></i></button><button class="icon-btn" data-toast="Marked redeemed"><i class="bi bi-check2-circle"></i></button></div>'] for u, ph, st, w in [("Tom Becker","(407) 555-7734","New","1 hr ago"),("Lucas Nguyen","(407) 555-9930","Redeemed","3 days ago"),("Hannah Reed","(813) 555-4470","New","Yesterday"),("Sofia Martins","(954) 555-2231","New","Yesterday")]]
    shell('leads.html', 'Coupon leads', 'leads.html', 'Coupon leads', card('', filters('Search leads', [('Coupon',['SUNSHINE10','SUNSHINE-PLAN']),('Status',['New','Redeemed','Expired'])]) + table(['Person','Coupon','Phone','Status','Requested',('','')], rows, checks=False, total='38', shown='1–4')), sub='People who requested one of your coupons. Contact details are shared with you.', actions='<button class="btn-outline"><i class="bi bi-download"></i> Export</button>')

    # ============ Inquiries ============
    rows = [[f'<span class="strong">{t}</span><div class="muted">{d}</div>', uwho(u), f'<span class="tag">{s}</span>', status_pill(st), f'<span class="muted">{w}</span>', '<div class="actions"><button class="btn-brand btn-xs"><i class="bi bi-telephone"></i> Call</button><button class="icon-btn"><i class="bi bi-envelope"></i></button></div>'] for t, d, u, s, st, w in [("Bail set at $25k · misdemeanor","needs release tonight · Broward County (overflow)","Sofia Martins","Bail bonds question","New","Yesterday"),("Bond for DUI arrest · Orange County","referred by Amir A. Ladan","Lucas Nguyen","Partner referral","Connected","3 days ago"),("How fast can you post a $5,000 bond?","Orange County","Michael Turner","Bail bonds question","Closed","2 weeks ago")]]
    shell('inquiries.html', 'Inquiries', 'inquiries.html', 'Inquiries', stats_row([('This month','12','+3',True,'bi-send',[6,7,7,8,9,9,10,11,11,12]),('Partner referrals','5','+2',True,'bi-diagram-3',[2,2,3,3,3,4,4,4,5,5]),('Connected','75%','',True,'bi-link-45deg',[60,62,65,68,70,71,72,73,74,75]),('Median reply','6 min','−1 min',True,'bi-stopwatch',[9,9,8,8,7,7,7,6,6,6])]) + card('', filters('Search inquiries', [('Source',['Bail bonds question','Partner referral','Coupon']),('Status',['New','Connected','Closed'])]) + table([('Inquiry','wide'),'From','Source','Status','Received',('','')], rows, checks=False, total='42', shown='1–3')), sub='Bail-bond questions in your county are routed straight to you, plus referrals from partner lawyers.')

    # ============ Insights ============
    body = stats_row([('Listing views','1,204','+22%',True,'bi-eye',[80,85,90,95,100,105,110,115,118,120],'last 30 days'),('Ad impressions','8,120','+9%',True,'bi-badge-ad',[6,6.4,6.8,7,7.3,7.6,7.8,8,8.1,8.1]),('Click-throughs','38','3.2%',True,'bi-cursor',[24,26,28,30,31,33,35,36,37,38]),('Coupon requests','38','+9',True,'bi-hand-index',[20,22,24,26,28,30,32,34,36,38])])
    body += '<div class="grid grid-8-4">' + card('Views by month', '<div class="card-body"><div class="chart-box"><canvas id="chart-growth"></canvas></div></div>') + card('By city', '<div class="card-body">' + ''.join(f'<div class="bar-row"><span class="lbl">{l}</span><div class="bar thin"><span style="width:{p}%"></span></div><span class="val">{v}</span></div>' for l, p, v in [("Orlando",100,"1,204"),("Kissimmee",26,"318"),("Sanford",8,"96")]) + '</div>') + '</div>'
    shell('insights.html', 'Listing views', 'insights.html', 'Listing views', body, charts=True)

    # ============ Billing ============
    left = card('Your plan', '<div class="card-body"><div class="mini-stats"><div class="mini-stat"><strong>$0</strong><span>Affiliate listing · free</span></div><div class="mini-stat"><strong>$14.95</strong><span>Sponsored ad · paused</span></div><div class="mini-stat"><strong>—</strong><span>No card on file</span></div><div class="mini-stat"><strong>$0.00</strong><span>Due now</span></div></div><div class="note mt-3"><i class="bi bi-gift-fill"></i><div>Your listing, coupons and partner ads are free. Only sponsored placements are billed, monthly, and can be paused any time.</div></div></div>', foot='<button class="btn-outline btn-sm"><i class="bi bi-credit-card"></i> Add card</button>') + card('Transactions', table(['Invoice',('Description','wide'),('Amount','num'),'Status','Date'], [['<span class="mono">inv_2026_08_3111</span>','<span class="strong">Sponsored ad · search results · Orlando · Aug</span>','<span class="strong">$14.95</span>',status_pill('Paid'),'<span class="muted">1 Aug 2026</span>']], checks=False, foot=False))
    shell('billing.html', 'Billing', 'billing.html', 'Billing', two_col(left, card('Questions?', '<div class="card-body">' + kv([('Sales','Bret Grubbs'),('Phone','+1 786-451-0396'),('Email','support@inkozi.com')]) + '</div>')))

    # ============ Settings ============
    left = card('Account', '<div class="card-body"><form data-demo><div class="row g-3"><div class="col-md-6">' + fld('Login email', inp('dispatch@sunshinebail.com')) + '</div><div class="col-md-6">' + fld('Mobile (SMS alerts)', inp('(407) 555-0199')) + '</div><div class="col-md-6">' + fld('Contact name', inp('Ray Sunshine')) + '</div><div class="col-md-6">' + fld('Timezone', select(['America/New_York'])) + '</div></div></form></div>', foot='<button class="btn-brand" data-toast="Saved">Save</button>') + card('Password', '<div class="card-body"><form data-demo><div class="row g-3"><div class="col-md-4">' + fld('Current', inp('', '', 'password')) + '</div><div class="col-md-4">' + fld('New', inp('', '', 'password')) + '</div><div class="col-md-4">' + fld('Confirm', inp('', '', 'password')) + '</div></div></form></div>', foot='<button class="btn-outline" data-toast="Password updated">Update password</button>')
    right = card('Alerts', '<div class="card-body">' + switch('Inquiries','Email + SMS') + switch('Coupon requests','Email') + switch('Partner requests','Email') + '</div>') + card('Danger zone', '<div class="card-body"><button class="btn-danger-soft w-100"><i class="bi bi-pause-circle"></i> Pause my listing</button></div>')
    shell('settings.html', 'Settings', 'settings.html', 'Settings', two_col(left, right))
