from gen_common import *

def build():
    use_admin()
    # ============ Partner connections (lawyer ↔ chiropractor / bail agent) ============
    conns = [("Amir A. Ladan","Bayshore Chiropractic","Chiropractor","Personal Injury · Orlando","Active","Leads copied + ad on profile","2 Mar 2026"),("Maria E. Gonzalez","Bayshore Chiropractic","Chiropractor","Personal Injury · Tampa","Active","Leads copied + ad on profile","18 Apr 2026"),("John P. Morgan","Sunshine State Bail Bonds","Bail agent","DUI / DWI · Orlando","Active","Ad on profile","6 May 2026"),("Daniel Whitaker","Sunshine State Bail Bonds","Bail agent","Traffic Violations · Orlando","Pending","Awaiting lawyer approval","Yesterday"),("Harvey Specter","Coastal Spine & Injury","Chiropractor","Personal Injury · Miami","Paused","Partner unverified","1 Sep 2026")]
    rows = [[pwho(l), who(p, t), f'<span class="tag">{c}</span>', f'<span class="muted">{m}</span>', status_pill(st), f'<span class="muted">{w}</span>', '<div class="actions"><button class="icon-btn"><i class="bi bi-pencil"></i></button><button class="icon-btn"><i class="bi bi-pause"></i></button><button class="icon-btn danger"><i class="bi bi-x-circle"></i></button></div>'] for l, p, t, c, st, m, w in conns]
    body = stats_row([('Connections','184','+12',True,'bi-diagram-3',[140,145,150,155,160,165,170,175,180,184],'lawyer ↔ partner pairs'),('PI leads copied','312','+18%',True,'bi-send',[20,22,24,25,26,27,28,29,30,31],'to chiropractors, 30 days'),('Partner ads shown','48k','+9%',True,'bi-badge-ad',[36,38,40,41,42,43,44,45,47,48],'impressions on lawyer profiles'),('Pending approval','1','',True,'bi-hourglass',[3,3,2,2,2,1,1,1,1,1])])
    body += '<div class="note mb-20"><i class="bi bi-info-circle-fill"></i><div><strong>How connections work.</strong> A lawyer links to a chiropractor or bail agent in the same city. The partner’s ad appears on the lawyer’s profile, and personal-injury inquiries to the lawyer are copied to the connected chiropractor by email and SMS. Both sides must approve.</div></div>'
    body += two_col(card('', filters('Search lawyer or partner', [('Partner type',['Chiropractor','Bail agent']),('City',[f'{c}, {s}' for c, s, _ in CITIES]),('Status',['Active','Pending','Paused'])]) + table(['Lawyer','Partner','Type',('Territory','mid'),'Status','Since',('','')], rows, checks=False, total='184', shown='1–5')), card('Create connection', '<div class="card-body"><form data-demo>' + fld('Lawyer', select(['Amir A. Ladan','John P. Morgan','Maria E. Gonzalez','Daniel Whitaker'])) + fld('Partner', select(['Bayshore Chiropractic','Sunshine State Bail Bonds','Coastal Spine & Injury'])) + fld('Territory', select(['Personal Injury · Orlando','DUI / DWI · Orlando','Personal Injury · Tampa'])) + switch('Copy personal-injury leads to partner','Email + SMS') + switch('Show partner ad on lawyer profile','Creative from Advertisements') + '<button class="btn-brand w-100 mt-3">Create connection</button></form></div>'))
    shell('connections.html', 'Partner connections', 'connections.html', 'Partner connections', body, sub='Lawyers linked with chiropractors and bail agents for cross-referrals and profile ads.', actions='<button class="btn-brand"><i class="bi bi-plus-lg"></i> New connection</button>')

    # ============ Agreements & e-sign ============
    ag = [("Rachel Kim","Hosting agreement v1.4","Tampa · DUI / DWI","Signed","Awaiting countersign","14 Sep 2026, 00:20"),("Elena Rodriguez","Hosting agreement v1.4","Austin · Immigration","Signed","Awaiting countersign","13 Sep 2026"),("Laura Chen","Hosting agreement v1.4","Orlando · Chiropractic","Unsigned","Reminder sent","—"),("Amir A. Ladan","Hosting agreement v1.4","Orlando · DUI / DWI + Criminal Defense","Signed","Complete","4 Jan 2025"),("Sarah J. Connor","Hosting agreement v1.3","Miami · Family Law","Signed","Complete · re-sign at renewal","2 Feb 2025"),("Sunshine State Bail Bonds","Affiliate terms v1.1","Orlando · Bail agent","Signed","Complete","2 Mar 2026")]
    rows = [[pwho(n) if n in PROV else who(n, 'Affiliate'), f'<span class="strong">{d}</span><div class="muted">{t}</div>', status_pill(s), pill('warn', st) if 'Awaiting' in st or 'Reminder' in st else (pill('ok','Complete') if st.startswith('Complete') else pill('', st)), f'<span class="muted">{w}</span>', '<div class="actions"><button class="icon-btn" data-bs-toggle="tooltip" title="View PDF"><i class="bi bi-file-earmark-pdf"></i></button><button class="icon-btn" data-bs-toggle="tooltip" title="Countersign"><i class="bi bi-pen"></i></button><button class="icon-btn" data-bs-toggle="tooltip" title="Send reminder"><i class="bi bi-envelope"></i></button></div>'] for n, d, t, s, st, w in ag]
    left = card('', filters('Search provider or agreement', [('Document',['Hosting agreement','Affiliate terms']),('Status',['Signed','Unsigned','Awaiting countersign','Complete'])], chips=['All','To countersign 2','Unsigned 1']) + table(['Party',('Document','mid'),'Signature','Status','Signed on',('','')], rows, checks=False, total='1,842', shown='1–6'))
    right = card('Countersign', '<div class="card-body"><div class="doc mb-3"><span class="d-icon"><i class="bi bi-file-earmark-pdf-fill"></i></span><div class="grow"><strong>hosting-agreement-rachel-kim.pdf</strong><span>Signed by Rachel Kim · 14 Sep 2026, 00:20 · IP 72.14.8.2</span></div></div><div class="sig-pad"><span class="sig-x">×</span><span class="sig-line"></span>Draw your signature here</div><div class="muted mt-2" style="font-size:12.5px">Countersigning as Liza Seale, Co-Founder &amp; President, on behalf of InKozi, Inc.</div></div>', foot='<button class="btn-outline btn-sm">Clear</button><button class="btn-brand btn-sm" data-toast="Agreement countersigned · PDF emailed to Rachel Kim">Countersign &amp; send</button>') + card('Template', '<div class="card-body">' + kv([('Hosting agreement','v1.4 · 8 Sep 2026'),('Affiliate terms','v1.1 · 1 Mar 2026'),('Signature capture','Canvas → PNG, embedded in PDF'),('Storage','Encrypted · 7 years')]) + '<a href="legal.html" class="btn-outline btn-sm w-100 mt-3">Edit templates</a></div>')
    shell('agreements.html', 'Agreements & e-sign', 'agreements.html', 'Agreements &amp; e-sign', stats_row([('Signed agreements','1,842','+34',True,'bi-pen',[16,16.5,17,17.2,17.5,17.8,18,18.2,18.3,18.4]),('Awaiting countersign','2','',True,'bi-hourglass-split',[4,4,3,3,3,2,2,2,2,2]),('Unsigned > 48h','1','',True,'bi-exclamation-circle',[3,3,2,2,2,2,1,1,1,1],'blocks purchase'),('Re-sign due at renewal','118','v1.3 → v1.4',True,'bi-arrow-repeat',[200,190,180,170,160,150,140,130,125,118])]) + two_col(left, right), sub='Providers must e-sign the hosting agreement before a slot can be purchased. InKozi countersigns and stores the PDF.', actions='<button class="btn-outline"><i class="bi bi-download"></i> Export</button><button class="btn-brand"><i class="bi bi-envelope"></i> Remind unsigned</button>')

    # ============ Advertisements ============
    ads = [("Bayshore Chiropractic","assets/images/lawyer-3.jpg","Injured? Free same-day consult","Personal Injury lawyer profiles · Tampa, Orlando","Sponsored · $14.95/mo","Active","12,400","1 Sep – 30 Sep 2026"),("Sunshine State Bail Bonds",None,"Out in under 2 hours, 24/7","DUI & Criminal profiles · Orlando","Included with connection","Active","8,120","Ongoing"),("Notary Express Miami",None,"Mobile notary, same day","Real Estate profiles · Miami","Sponsored · $14.95/mo","Paused","2,050","Paused 10 Sep"),("Legal financing partner",None,"Fund your case, pay when you win","Search results sidebar · all cities","House ad","Active","31,900","Ongoing"),("Ask KOZI app",None,"Get answers on the go","Search results · all cities","House ad","Active","44,300","Ongoing")]
    rows = [[f'<div class="who"><span class="avatar sq soft"><i class="bi bi-image"></i></span><div><strong>{h}</strong><span>{a}</span></div></div>', f'<span class="muted">{p}</span>', f'<span class="tag">{t}</span>', status_pill(st), f'<span class="strong">{i}</span>', f'<span class="muted">{d}</span>', '<div class="actions"><button class="icon-btn"><i class="bi bi-pencil"></i></button><button class="icon-btn"><i class="bi bi-pause"></i></button><button class="icon-btn danger"><i class="bi bi-trash"></i></button></div>'] for a, img, h, p, t, st, i, d in ads]
    body = stats_row([('Live ads','62','+4',True,'bi-badge-ad',[50,52,54,55,56,58,59,60,61,62]),('Impressions','98.8k','+11%',True,'bi-eye',[70,74,78,82,85,88,91,94,96,98.8],'last 30 days'),('Clicks','3,120','3.2% CTR',True,'bi-cursor',[2.1,2.3,2.4,2.5,2.6,2.7,2.8,2.9,3.0,3.1]),('Sponsored revenue','$612','+$45',True,'bi-cash',[400,430,460,480,500,530,560,580,600,612],'this month')])
    body += two_col(card('', filters('Search ads', [('Placement',['Lawyer profiles','Search results sidebar','Homepage','Ask KOZI app']),('Type',['Sponsored','Included with connection','House ad']),('City',[f'{c}, {s}' for c, s, _ in CITIES]),('Status',['Active','Paused','Expired'])]) + table([('Creative','mid'),('Placement','mid'),'Type','Status',('Impressions','num'),'Schedule',('','')], rows, checks=False, total='62', shown='1–5')), card('New advertisement', '<div class="card-body"><form data-demo>' + fld('Advertiser', select(['Bayshore Chiropractic','Sunshine State Bail Bonds','Notary Express Miami','House ad'])) + fld('Headline', inp('', 'e.g. Injured? Free same-day consult')) + fld('Placement', select(['Lawyer profiles in a territory','Search results sidebar','Ask KOZI app'])) + fld('Cities', inp('', 'Orlando, Tampa')) + '<div class="cover mb-3"><i class="bi bi-image"></i>Upload creative · 600 × 200 or 270 × 90</div>' + fld('Schedule', inp('1 Oct – 31 Oct 2026')) + '<button class="btn-brand w-100">Create ad</button></form></div>') + card('Ad slots per city', '<div class="card-body">' + kv([('Max advertisers per city','9'),('Sponsored profile ad','$14.95 / month'),('Connection ad','Included'),('In-app ads','Managed in Ask KOZI app')]) + '</div>'))
    shell('advertisements.html', 'Advertisements', 'advertisements.html', 'Advertisements', body, sub='Partner and house ads shown on lawyer profiles, search results and in the Ask KOZI app.', actions='<button class="btn-outline"><i class="bi bi-download"></i> Report</button><button class="btn-brand"><i class="bi bi-plus-lg"></i> New ad</button>')

    # ============ Coupons & promo codes ============
    cps = [("Free DUI consultation","KOZI-DUI-FREE","Amir A. Ladan","Lawyer","Free · was $150","31 Dec 2026","Active","38"),("10% off any bond over $5,000","SUNSHINE10","Sunshine State Bail Bonds","Affiliate","10% off","31 Dec 2026","Active","38"),("First adjustment $29","BAYSHORE29","Bayshore Chiropractic","Affiliate","$29 · was $95","30 Nov 2026","Active","61"),("Half-price custody consult","CONNOR50","Sarah J. Connor","Lawyer","$100 · was $200","15 Oct 2026","Active","12"),("Provider signup: waive set-up fee","LAUNCH375","InKozi","Promo code","$375 off set-up","30 Sep 2026","Active","9 redeemed"),("Immigration Q&A week","IMMIG-FREE","Elena Rodriguez","Lawyer","Free consult","—","Pending","—")]
    rows = [[f'<div class="who"><span class="avatar sq soft"><i class="bi bi-ticket-perforated"></i></span><div><strong>{t}</strong><span>{o}</span></div></div>', f'<span class="code" style="font-family:Menlo,monospace;font-weight:700;color:var(--primary)">{c}</span>', f'<span class="tag">{k}</span>', f'<span class="strong">{p}</span>', f'<span class="muted">{e}</span>', status_pill(st), f'<span class="strong">{r}</span>', '<div class="actions"><button class="icon-btn"><i class="bi bi-pencil"></i></button><button class="icon-btn"><i class="bi bi-eye"></i></button><button class="icon-btn danger"><i class="bi bi-trash"></i></button></div>'] for t, c, o, k, p, e, st, r in cps]
    body = stats_row([('Live coupons','126','+9',True,'bi-ticket-perforated',[90,95,100,105,110,114,118,121,124,126],'lawyers + affiliates'),('Coupon requests','842','+23%',True,'bi-hand-index',[50,55,60,64,68,72,76,79,82,84],'last 30 days'),('Promo codes','4','',True,'bi-tag',[2,2,2,3,3,3,3,4,4,4],'provider signup offers'),('Set-up fees waived','9','$3,375',True,'bi-gift',[2,3,4,5,6,7,8,8,9,9],'LAUNCH375')])
    body += two_col(card('', filters('Search coupons or codes', [('Type',['Lawyer coupon','Affiliate coupon','Promo code']),('Category',AREAS[:8]),('Status',['Active','Pending','Expired'])], chips=['All','Pending approval 1','Expiring soon 2']) + table([('Coupon','mid'),'Code','Type','Offer','Expires','Status',('Requests','num'),('','')], rows, checks=False, total='130', shown='1–6')), card('New promo code', '<div class="card-body"><form data-demo>' + fld('Code', inp('', 'e.g. FALL2026')) + fld('Applies to', select(['Set-up fee ($375)','First month hosting ($45)','Sponsored ad'])) + fld('Discount', inp('', '$ or %')) + fld('Valid', inp('1 Oct – 31 Dec 2026')) + fld('Limit', inp('50'), small='redemptions') + '<button class="btn-brand w-100">Create code</button></form></div>') + card('Public coupon directory', '<div class="card-body"><p class="muted" style="font-size:13px">Approved coupons are listed on the public discount-code directory and on the provider or affiliate page.</p>' + switch('Directory enabled','frontend “Deals” page') + switch('Require approval for new coupons','Staff review before publishing') + '</div>'))
    shell('coupons.html', 'Coupons & promo codes', 'coupons.html', 'Coupons &amp; promo codes', body, sub='Deals published by lawyers and affiliates, plus InKozi promo codes for provider signup.', actions='<button class="btn-outline"><i class="bi bi-download"></i> Export leads</button><button class="btn-brand"><i class="bi bi-plus-lg"></i> New coupon</button>')

    # ============ Newsletters ============
    camps = [("September legal insights","Users · Florida","18,204","42.1%","6.8%","Sent","Today, 05:00"),("Open slots in your city","Prospect lawyers · Tampa Bay","1,240","38.4%","9.2%","Sent","11 Sep 2026"),("Ask KOZI 2.4 is here","All app users","8,920","—","—","Queued","16 Sep 2026, 09:00"),("Hosting renewal reminder","Providers · renewals in 7 days","212","—","—","Scheduled","24 Sep 2026"),("Affiliate program launch","Affiliates","214","51.0%","12.4%","Sent","1 Sep 2026")]
    rows = [[f'<span class="strong">{t}</span><div class="muted">{l}</div>', f'<span class="strong">{r}</span>', f'<span class="muted">{o}</span>', f'<span class="muted">{c}</span>', status_pill(st), f'<span class="muted">{w}</span>', '<div class="actions"><button class="icon-btn"><i class="bi bi-eye"></i></button><button class="icon-btn"><i class="bi bi-files"></i></button><button class="icon-btn"><i class="bi bi-bar-chart"></i></button></div>'] for t, l, r, o, c, st, w in camps]
    lists = '<ul class="list">' + ''.join(f'<li><span class="avatar sq soft"><i class="bi bi-people"></i></span><div class="grow"><strong>{n}</strong><span>{c} members</span></div><button class="icon-btn"><i class="bi bi-pencil"></i></button></li>' for n, c in [("Users · Florida","18,204"),("All app users","8,920"),("Providers","1,796"),("Prospect lawyers · Tampa Bay","1,240"),("Affiliates","214")]) + '</ul><button class="btn-outline btn-sm w-100 mt-3"><i class="bi bi-plus-lg"></i> New list</button>'
    body = stats_row([('Subscribers','29,318','+412',True,'bi-people',[24,25,26,26.5,27,27.5,28,28.5,29,29.3]),('Sent this month','3','',True,'bi-envelope-paper',[2,2,3,3,3,3,3,3,3,3],'campaigns'),('Open rate','42%','+3%',True,'bi-envelope-open',[36,37,38,38,39,40,40,41,41,42]),('Queue','8,920','',True,'bi-hourglass-split',[0,0,0,0,0,0,0,0,8920,8920],'sending 16 Sep 09:00')])
    body += two_col(card('', filters('Search campaigns', [('List',['Users · Florida','All app users','Providers','Affiliates']),('Status',['Sent','Queued','Scheduled','Draft'])]) + table([('Campaign','mid'),('Recipients','num'),'Opens','Clicks','Status','Sent',('','')], rows, checks=False, total='48', shown='1–5'), tools='<a href="#" class="btn-ghost btn-sm">Templates</a>'), card('Lists', f'<div class="card-body">{lists}</div>') + card('Sending', '<div class="card-body">' + kv([('Provider','Postmark · broadcast stream'),('Queue worker','Cron · every 5 minutes'),('Unsubscribe','One-click, footer link'),('From','InKozi &lt;hello@inkozi.com&gt;')]) + '</div>'))
    shell('newsletters.html', 'Newsletters', 'newsletters.html', 'Newsletters', body, sub='Email marketing: lists, campaigns and the sending queue.', actions='<button class="btn-outline"><i class="bi bi-upload"></i> Import CSV</button><button class="btn-brand"><i class="bi bi-plus-lg"></i> New campaign</button>')

    # ============ Press releases ============
    pr = [("InKozi launches Ask KOZI 2.4 with live lawyer chat","12 Sep 2026","Published","Orlando Sentinel, Law.com"),("InKozi expands territories to Austin, Los Angeles and New York","1 Jul 2026","Published","PRNewswire"),("Liza Seale named Orlando Woman of the Year","3 Mar 2020","Published","Orlando Business Journal"),("InKozi partners with legal-financing lenders","—","Draft","—")]
    rows = [[f'<span class="strong">{t}</span>', f'<span class="muted">{d}</span>', status_pill(st), f'<span class="muted">{c}</span>', '<div class="actions"><button class="icon-btn"><i class="bi bi-pencil"></i></button><a href="../frontend/blog.html" target="_blank" class="icon-btn"><i class="bi bi-box-arrow-up-right"></i></a><button class="icon-btn danger"><i class="bi bi-trash"></i></button></div>'] for t, d, st, c in pr]
    body = two_col(card('', table([('Release','wide'),'Date','Status','Coverage',('','')], rows, checks=False, foot=False), hint='shown on the Press & media page'), card('Media kit', '<div class="card-body"><ul class="list"><li><span class="avatar sq soft"><i class="bi bi-file-zip"></i></span><div class="grow"><strong>Logo pack</strong><span>SVG, PNG · 2.1 MB</span></div></li><li><span class="avatar sq soft"><i class="bi bi-file-earmark-pdf"></i></span><div class="grow"><strong>Company fact sheet</strong><span>PDF · updated Jul 2026</span></div></li><li><span class="avatar sq soft"><i class="bi bi-camera"></i></span><div class="grow"><strong>Leadership photos</strong><span>8 headshots</span></div></li></ul><button class="btn-outline btn-sm w-100 mt-3"><i class="bi bi-upload"></i> Upload</button></div>') + card('Press contact', '<div class="card-body">' + kv([('Contact','Liza Seale'),('Email','press@inkozi.com'),('Phone','+1 786-451-0396')]) + '</div>'))
    shell('press-releases.html', 'Press releases', 'press-releases.html', 'Press releases', body, sub='Announcements and the media kit for the Press & media page.', actions='<button class="btn-brand"><i class="bi bi-plus-lg"></i> New release</button>')

    # ============ Ask KOZI app ============
    left = card('App content', '<div class="card-body"><div class="row g-3"><div class="col-md-6">' + fld('Intro video', inp('videos/Inkozi-Video.mp4'), small='shown on first launch') + '</div><div class="col-md-6">' + fld('Loading video', inp('videos/loading.mp4')) + '</div></div>' + fld('Onboarding slides', '<div class="grid grid-3" style="gap:10px">' + ''.join(f'<div class="cover" style="padding:20px 10px"><i class="bi bi-phone"></i>{t}</div>' for t in ["Ask a free question","Verified local lawyers","Chat, call or connect"]) + '</div>') + fld('In-app ads', '<ul class="list"><li><span class="avatar sq soft"><i class="bi bi-badge-ad"></i></span><div class="grow"><strong>Legal financing partner</strong><span>Home screen banner · 44k impressions</span></div>' + status_pill('Active') + '</li><li><span class="avatar sq soft"><i class="bi bi-badge-ad"></i></span><div class="grow"><strong>Sunshine State Bail Bonds</strong><span>DUI results · Orlando</span></div>' + status_pill('Active') + '</li></ul>') + '</div>', foot='<button class="btn-brand btn-sm" data-toast="App content saved">Save</button>') \
        + card('Releases', table(['Version','Platform','Status','Released','Notes'], [['<span class="strong">2.4</span>','<span class="tag">iOS</span>',pill('warn','In review'),'<span class="muted">Submitted 13 Sep</span>','<span class="muted">Live lawyer chat, Kozi handoff</span>'],['<span class="strong">2.4</span>','<span class="tag">Android</span>',status_pill('Live'),'<span class="muted">12 Sep 2026</span>','<span class="muted">Live lawyer chat, Kozi handoff</span>'],['<span class="strong">2.3</span>','<span class="tag">iOS · Android</span>',status_pill('Live'),'<span class="muted">2 Jul 2026</span>','<span class="muted">New territories, favourites</span>']], checks=False, foot=False), hint='minimum supported 2.1')
    right = card('Store links', '<div class="card-body">' + fld('App Store', inp('https://apps.apple.com/app/ask-kozi')) + fld('Google Play', inp('https://play.google.com/store/apps/details?id=com.inkozi.askkozi')) + switch('Store badges in the site footer','') + switch('Deep-link questions to the app','Open Ask KOZI when installed') + '</div>', foot='<button class="btn-brand btn-sm" data-toast="Saved">Save</button>') + card('API', '<div class="card-body">' + kv([('Base URL','api.inkozi.com/v1'),('Auth','Phone OTP (Telnyx) + JWT'),('Endpoints','users, lawyers, categories, cities, nearest, favourites, chat, questions, ads, media, legal'),('Uptime','99.98% · 30 days')]) + '</div>') + card('Usage', '<div class="card-body"><div class="mini-stats"><div class="mini-stat"><strong>8,920</strong><span>Monthly active</span></div><div class="mini-stat"><strong>4.7</strong><span>Store rating</span></div><div class="mini-stat"><strong>38%</strong><span>of questions via app</span></div><div class="mini-stat"><strong>1,204</strong><span>Installs · 30 days</span></div></div></div>')
    shell('mobile-app.html', 'Ask KOZI app', 'mobile-app.html', 'Ask KOZI app', two_col(left, right), sub='Content, releases and API served to the iOS and Android apps.', actions='<button class="btn-outline"><i class="bi bi-phone"></i> Test on device</button>')
