from gen_common import *
STATE_NAMES = {"FL":"Florida","TX":"Texas","CA":"California","NY":"New York"}

def build():
    use_admin()
    # ============ Homepage ============
    hero = card('Hero', '<div class="card-body"><div class="row g-3"><div class="col-md-6">' + fld('Title line 1', inp('Connect with')) + '</div><div class="col-md-6">' + fld('Title line 2', inp('on-demand lawyers.'), small='gradient highlight') + '</div><div class="col-12">' + fld('Subtitle', inp('Real help. Real people. Right when you need it.')) + '</div><div class="col-md-4">' + fld('Badge 1', inp('Available 24/7')) + '</div><div class="col-md-4">' + fld('Badge 2', inp('Verified Lawyers')) + '</div><div class="col-md-4">' + fld('Badge 3', inp('Low Cost Options')) + '</div><div class="col-md-6">' + fld('Search placeholder', inp('What type of lawyer do you need?')) + '</div><div class="col-md-3">' + fld('Location default', inp('Orlando, FL')) + '</div><div class="col-md-3">' + fld('Button', inp('Search')) + '</div><div class="col-12">' + fld('Trust line', inp('Trusted by thousands of families across Florida.')) + '</div><div class="col-12"><div class="cover"><i class="bi bi-image"></i>hero-man.png · man holding the Ask KOZI app <div style="font-size:12px">Click to replace · 1200 × 900 recommended</div></div></div></div></div>', foot='<a href="../frontend/index.html" target="_blank" class="btn-outline btn-sm"><i class="bi bi-eye"></i> Preview</a><button class="btn-brand btn-sm" data-toast="Homepage saved">Save</button>')
    feats = card('Features bar', '<div class="card-body"><div class="row g-3">' + ''.join(f'<div class="col-md-6"><div class="doc"><span class="d-icon img"><i class="bi {ic}"></i></span><div class="grow"><strong>{t}</strong><span>{d}</span></div><button class="icon-btn"><i class="bi bi-pencil"></i></button></div></div>' for ic, t, d in [("bi-clock","On-Demand Help","Connect with a lawyer right when you need it."),("bi-shield-check","Verified Lawyers","All lawyers are checked and reviewed."),("bi-currency-dollar","Affordable Options","Low-cost and payment plans available."),("bi-people","For Our Community","We're here to help and put people first.")]) + '</div></div>', hint='gradient band under the hero')
    tiles = card('“What can we help you with?” tiles', '<div class="card-body"><div class="d-flex flex-wrap gap-2">' + ''.join(f'<span class="chip active"><i class="bi bi-grip-vertical"></i> {t}</span>' for t in HOME_TILES) + '</div><div class="muted mt-2" style="font-size:12.5px">Drag to reorder. “More Areas” links to the full practice-area list (28+).</div></div>', tools='<a href="practice-areas.html" class="btn-ghost btn-sm">Practice areas</a>')
    featured = card('Top Rated Lawyers', '<div class="card-body"><p class="muted mb-3" style="font-size:13px">“Find experienced professionals ready to help you today.” Four cards, then “View All Lawyers”. Only providers flagged “show on homepage” qualify.</p><ul class="list">' + ''.join(f'<li>{pav(n)}<div class="grow"><strong>{n}</strong><span>{PROV[n][1]} · {PROV[n][2]} · {PROV[n][4]} ({PROV[n][5]})</span></div><button class="icon-btn"><i class="bi bi-arrows-move"></i></button><button class="icon-btn danger"><i class="bi bi-x-lg"></i></button></li>' for n in ["Amir A. Ladan","Sarah J. Connor","Michael T. Ross","Jessica Pearson"]) + '</ul><button class="btn-outline btn-sm w-100 mt-3"><i class="bi bi-plus-lg"></i> Feature another lawyer</button></div>', hint='4 featured')
    hiw = card('How It Works', '<div class="card-body">' + fld('Subtitle', inp("It's easy to get the legal help you need.")) + '<ul class="list">' + ''.join(f'<li><span class="avatar sq soft">{i + 1}</span><div class="grow"><strong>{t}</strong><span>{d}</span></div><button class="icon-btn"><i class="bi bi-pencil"></i></button></li>' for i, (t, d) in enumerate([("Search for a Lawyer","Tell us what type of legal help you need and your location. We'll find the right match for you."),("Review & Connect","Browse verified lawyer profiles, read reviews, and connect with the attorney that fits your needs."),("Get Legal Help","Chat, call, or schedule a consultation. Get the legal assistance you need, when you need it.")])) + '</ul></div>')
    insights = card('Legal Insights', '<div class="card-body">' + switch('Show latest 3 posts automatically','Pulled from the blog, newest first') + switch('“View All Articles” button','Links to blog.html') + '</div>', hint='latest blog')
    seo = card('SEO', '<div class="card-body">' + fld('Page title', inp('InKozi — On-Demand Lawyers | Legal Help When You Need It')) + fld('Meta description', textarea('InKozi — Connect with on-demand lawyers. Real help. Real people. Available 24/7. Find verified lawyers near you for Criminal Defense, DUI, Family Law, and more.', 3)) + '</div>')
    shell('homepage.html', 'Homepage', 'homepage.html', 'Homepage', two_col(hero + feats + hiw, tiles + featured + insights + seo), sub='Everything shown on index.html, section by section.', actions='<a href="../frontend/index.html" target="_blank" class="btn-outline"><i class="bi bi-box-arrow-up-right"></i> View live</a><button class="btn-brand" data-toast="Homepage published"><i class="bi bi-check-lg"></i> Publish changes</button>')

    # ============ Site pages ============
    pages = [("Home","index.html","Marketing","Published","Today, 10:42","homepage.html"),("About InKozi","about.html","Marketing","Published","2 Sep 2026","page-editor.html"),("How It Works","how-it-works.html","Marketing","Published","2 Sep 2026","page-editor.html"),("For Lawyers & Pricing","for-lawyers.html","Marketing","Published","8 Sep 2026","subscriptions.html"),("Find a Lawyer (search)","search.html","App","Published","—","locations.html"),("Lawyer profile","profile.html","App","Published","—","providers.html"),("Q&A Forum","qa.html","App","Published","—","questions.html"),("Blog","blog.html","Content","Published","12 Sep 2026","blog.html"),("FAQ / Help Center","faq.html","Support","Published","1 Sep 2026","faq.html"),("Contact","contact.html","Support","Published","1 Sep 2026","page-editor.html"),("Privacy Policy","privacy-policy.html","Legal","Published","8 Sep 2026","legal.html"),("Terms of Use","terms-of-use.html","Legal","Published","8 Sep 2026","legal.html"),("Hosting agreement","terms-of-use.html","Legal","Published","8 Sep 2026","agreements.html"),("Sign in / Register / Claim territory","login.html","Auth","Published","14 Sep 2026","settings.html"),("Error pages (401, 403, 404, 500, 503, offline)","404.html","System","Published","14 Sep 2026","settings.html")]
    rows = [[f'<a href="{e}" class="strong">{t}</a><div class="muted mono">/{f}</div>', f'<span class="tag">{g}</span>', status_pill(st), f'<span class="muted">{w}</span>', f'<div class="actions"><a href="{e}" class="icon-btn"><i class="bi bi-pencil"></i></a><a href="../frontend/{f}" target="_blank" class="icon-btn"><i class="bi bi-box-arrow-up-right"></i></a></div>'] for t, f, g, st, w, e in pages]
    body = card('', filters('Search pages', [('Group',['Marketing','App','Content','Support','Legal','Auth','System']),('Status',['Published','Draft'])]) + table([('Page','wide'),'Group','Status','Last edited',('','')], rows, checks=False, foot=False), hint='15 public pages')
    shell('pages.html', 'Site pages', 'pages.html', 'Site pages', body, sub='Every public page on inkozi.com and where its content is managed. SEO city pages are generated from Locations.', actions='<button class="btn-outline"><i class="bi bi-diagram-3"></i> Navigation &amp; footer</button><button class="btn-outline"><i class="bi bi-map"></i> Sitemap</button><button class="btn-brand"><i class="bi bi-plus-lg"></i> New page</button>')

    # ============ Page editor ============
    tabs = '<div class="tabs"><a href="#" class="active">About InKozi</a><a href="#">How It Works</a><a href="#">Contact</a><a href="#">Navigation &amp; footer</a></div>'
    left = card('Hero', '<div class="card-body"><div class="row g-3"><div class="col-md-4">' + fld('Eyebrow', inp('About InKozi')) + '</div><div class="col-md-4">' + fld('Title line 1', inp('Legal help should be')) + '</div><div class="col-md-4">' + fld('Title line 2', inp('one tap away.')) + '</div><div class="col-12">' + fld('Intro', textarea("InKozi was built in Orlando, Florida with a simple belief: when someone needs a lawyer, they shouldn't have to wait days for a call back.", 2)) + '</div><div class="col-md-6">' + fld('Primary button', inp('Find a Lawyer')) + '</div><div class="col-md-6">' + fld('Secondary button', inp('Meet the Team')) + '</div></div><div class="grid grid-3 mt-1">' + ''.join(f'<div class="doc"><span class="d-icon img"><i class="bi bi-check-lg"></i></span><div class="grow"><strong>{a}</strong><span>{b}</span></div></div>' for a, b in [("Answered in minutes","Not 24–48 hours"),("Every lawyer verified","License, background & standing"),("Local by design","Matched to your city")]) + '</div></div>') \
        + card('Stats strip', '<div class="card-body"><div class="row g-3">' + ''.join(f'<div class="col-md-3"><div class="fld mb-0"><label>{l}</label>{inp(v)}</div></div>' for v, l in [("72%","want to talk to a lawyer by phone"),("50%","expect a same-day response"),("78%","research a lawyer online first"),("28+","practice areas covered")]) + '</div></div>') \
        + card('Our Story', '<div class="card-body">' + fld('Heading', inp('From a frustrating wait to an instant connection.')) + fld('Body', textarea('People typically visit two to five websites before contacting a lawyer, and then wait a day or two for a reply. InKozi was built to close that gap.', 3)) + '<ul class="list">' + ''.join(f'<li><i class="bi bi-check-circle-fill" style="color:var(--green)"></i><div class="grow"><strong>{a}</strong><span>{b}</span></div><button class="icon-btn"><i class="bi bi-pencil"></i></button></li>' for a, b in [("We build the technology.","The conversation, the advice and the agreement happen directly between you and the professional."),("We are not a referral service.","InKozi never takes a cut of your case and never gets involved in your matter."),("Free for everyone who needs help.","Asking a question and finding a lawyer costs nothing.")]) + '</ul></div>') \
        + card('What We Stand For · Ask. Trust. Connect.', '<div class="card-body"><div class="grid grid-2">' + ''.join(f'<div class="doc"><span class="d-icon img"><i class="bi {ic}"></i></span><div class="grow"><strong>{a}</strong><span>{b}</span></div><button class="icon-btn"><i class="bi bi-pencil"></i></button></div>' for ic, a, b in [("bi-chat-dots","Ask freely","No appointment, no gatekeeping."),("bi-shield-check","Trust by default","Every provider is vetted."),("bi-geo-alt","Connect locally","Location-aware matching."),("bi-lock","Protect privacy","Secure gateway, privileged conversation.")]) + '</div></div>')
    right = card('Publish', '<div class="card-body">' + kv([('Status',status_pill('Published')),('URL','/about.html'),('Last edited','2 Sep 2026 by Liza S.')]) + '</div>', foot='<button class="btn-outline btn-sm" data-toast="Draft saved">Save draft</button><button class="btn-brand btn-sm" data-toast="About page published">Publish</button>') + card('Leadership section', '<div class="card-body"><p class="muted" style="font-size:13px">“The people behind the platform.” Pulled from the Leadership team list (8 members).</p><a href="leadership.html" class="btn-outline btn-sm w-100">Manage team</a></div>') + card('Closing CTA', '<div class="card-body">' + fld('Heading', inp('Ready to talk to a lawyer today?')) + fld('Text', textarea('Post your question for free and hear back from a verified local professional in minutes.', 2)) + '</div>') + card('SEO', '<div class="card-body">' + fld('Title', inp('About InKozi — Ask. Trust. Connect.')) + fld('Meta description', textarea('Legal help should be one tap away. Learn how InKozi connects people with verified local lawyers in minutes.', 2)) + '</div>')
    shell('page-editor.html', 'Edit · About InKozi', 'pages.html', 'Edit page', tabs + two_col(left, right), crumbs=[("Dashboard","index.html"),("Site pages","pages.html"),("About InKozi",None)], actions='<a href="../frontend/about.html" target="_blank" class="btn-outline"><i class="bi bi-eye"></i> Preview</a><button class="btn-brand" data-toast="About page published"><i class="bi bi-check-lg"></i> Publish</button>')

    # ============ Blog ============
    rows = []
    for t, cat, a, d, st, v, r, cov in POSTS:
        thumb = f'<img src="{cov}" alt="" class="avatar sq" style="width:44px;height:44px">' if cov else '<span class="avatar sq soft"><i class="bi bi-image"></i></span>'
        rows.append([f'<div class="who">{thumb}<div><a href="blog-editor.html" class="strong">{t}</a><span>{cat} · {r} read</span></div></div>', pwho(a, PROV[a][1].split(" • ")[0]) if a in PROV else a, status_pill(st), f'<span class="strong">{v}</span>', f'<span class="muted">{d}</span>', '<div class="actions"><a href="blog-editor.html" class="icon-btn"><i class="bi bi-pencil"></i></a><a href="../frontend/blog-details.html" target="_blank" class="icon-btn"><i class="bi bi-box-arrow-up-right"></i></a><button class="icon-btn danger"><i class="bi bi-trash"></i></button></div>'])
    cats = '<ul class="list">' + ''.join(f'<li><div class="grow"><strong>{c}</strong><span>{n} posts</span></div><button class="icon-btn"><i class="bi bi-pencil"></i></button></li>' for c, n in BLOG_CATS) + '</ul><button class="btn-outline btn-sm w-100 mt-3"><i class="bi bi-plus-lg"></i> Add category</button>'
    popular = '<ul class="list">' + ''.join(f'<li><span class="avatar sq soft">{i + 1}</span><div class="grow"><strong>{t}</strong><span>{d}</span></div></li>' for i, (t, d) in enumerate([("What to Do Immediately After a DUI Arrest","Oct 12, 2024"),("Understanding Child Custody Laws","Oct 08, 2024"),("5 Common Legal Mistakes Startup Founders Make","Oct 05, 2024")])) + '</ul>'
    body = stats_row([('Published','53','+6',True,'bi-journal-check',[40,42,44,45,47,48,50,51,52,53],'across 6 categories'),('Views this month','48.2k','+22%',True,'bi-eye',[28,30,33,35,38,40,42,44,46,48]),('Provider-written','31','58%',True,'bi-person-badge',[20,22,24,25,26,27,28,29,30,31],'posted from the provider portal'),('Awaiting review','2','',True,'bi-pencil-square',[4,4,3,3,3,2,2,2,2,2],'provider drafts')])
    body += '<div class="grid grid-8-4">' + card('', filters('Search posts', [('Status',['Published','Scheduled','Draft','Awaiting review']),('Category',[c for c, _ in BLOG_CATS]),('Author',['Amir A. Ladan','Sarah J. Connor','Michael T. Ross','Jessica Pearson','Harvey Specter','Elena Rodriguez','Staff'])]) + table([('Post','wide'),'Author','Status',('Views','num'),'Date',('','')], rows, total='55', shown='1–11')) + '<div>' + card('Categories', f'<div class="card-body">{cats}</div>', hint='sidebar counts') + card('Popular posts', f'<div class="card-body">{popular}</div>', hint='sidebar widget') + '</div></div>'
    shell('blog.html', 'Blog', 'blog.html', 'Legal Insights blog', body, sub='“Expert advice, latest legal news, and practical tips.” Staff posts plus provider posts submitted from their portal.', actions='<a href="../frontend/blog.html" target="_blank" class="btn-outline"><i class="bi bi-box-arrow-up-right"></i> View blog</a><a href="blog-editor.html" class="btn-brand"><i class="bi bi-plus-lg"></i> New post</a>')

    # ============ Blog editor ============
    toolbar = '<div class="editor-toolbar">' + ''.join(f'<button type="button" title="{t}"><i class="bi {i}"></i></button>' for t, i in [("Bold","bi-type-bold"),("Italic","bi-type-italic"),("Underline","bi-type-underline")]) + '<span class="sep"></span>' + ''.join(f'<button type="button" title="{t}"><i class="bi {i}"></i></button>' for t, i in [("Heading 2","bi-type-h2"),("Heading 3","bi-type-h3"),("Quote","bi-quote"),("Bullets","bi-list-ul"),("Numbered","bi-list-ol")]) + '<span class="sep"></span>' + ''.join(f'<button type="button" title="{t}"><i class="bi {i}"></i></button>' for t, i in [("Link","bi-link-45deg"),("Image","bi-image"),("Embed","bi-code-slash")]) + '</div>'
    editor = '<div class="fld"><input class="form-control" style="height:52px;font-size:20px;font-weight:700" value="What to Do Immediately After a DUI Arrest in Florida"></div>' + toolbar + '<div class="editor-area" contenteditable="true"><p>Navigating the aftermath of a DUI arrest can be confusing and scary. The decisions you make in the first 24 to 48 hours can shape the outcome of your case.</p><h2>1. Remain Silent and Do Not Incriminate Yourself</h2><p>The most important rule following an arrest is to exercise your right to remain silent.</p><blockquote>"Anything you say can and will be used against you in a court of law. The best defense begins with knowing when to stop talking."</blockquote><h2>2. Request to Speak with an Attorney Immediately</h2><p>As soon as you are arrested, clearly state that you wish to speak with an attorney.</p><h3>Understanding Implied Consent in Florida</h3><p>Florida law operates under "implied consent," meaning that by holding a driver\'s license you have implicitly agreed to chemical testing.</p><h2>3. Document Everything You Remember</h2><h2>4. Request a DMV Hearing</h2><p>In Florida, you only have 10 days from the date of your arrest to request a formal review hearing…</p><h2>Conclusion</h2></div>'
    left = card('', f'<div class="card-body">{editor}</div>') + card('SEO', '<div class="card-body">' + fld('URL slug', '<div class="with-icon"><i class="bi bi-link-45deg"></i><input class="form-control" value="what-to-do-immediately-after-a-dui-arrest"></div>') + fld('Meta description', textarea('Arrested for DUI in Florida? Here are the critical first steps you must take in the first 48 hours to protect your license and your case.', 2), small='152 / 160') + '<div class="fld mb-0"><label>Search preview</label><div style="border:1px solid var(--line);border-radius:10px;padding:12px 14px"><div style="color:#1a0dab;font-size:16px">What to Do Immediately After a DUI Arrest | InKozi</div><div style="color:#006621;font-size:12.5px">inkozi.com › blog › what-to-do-immediately-after-a-dui-arrest</div><div class="muted" style="font-size:13px">Arrested for DUI in Florida? Here are the critical first steps you must take…</div></div></div></div>') + card('Related articles', '<div class="card-body"><ul class="list">' + ''.join(f'<li><div class="grow"><strong>{t}</strong><span>Criminal Defense</span></div><button class="icon-btn danger"><i class="bi bi-x-lg"></i></button></li>' for t in ["How to Choose the Right Criminal Defense Attorney","Understanding Bail and Bonds in the Florida System","Misdemeanor vs. Felony: What Are the Real Differences?"]) + '</ul></div>', hint='shown under the post')
    right = card('Publish', '<div class="card-body">' + kv([('Status',status_pill('Published')),('Published','October 12, 2024'),('Read time','5 min · auto'),('Last edited','Today, 10:42 by Liza S.')]) + '<div class="fld mt-3 mb-0"><label>Schedule</label><input class="form-control" type="datetime-local" value="2024-10-12T08:00"></div></div>', foot='<button class="btn-outline btn-sm" data-toast="Draft saved">Save draft</button><button class="btn-brand btn-sm" data-toast="Post updated">Update</button>') \
        + card('Organisation', '<div class="card-body">' + fld('Category', select([c for c, _ in BLOG_CATS], 'Criminal Defense')) + fld('Author', select(['Amir A. Ladan · Criminal Defense Attorney','Sarah J. Connor','Michael T. Ross','Staff'], 'Amir A. Ladan · Criminal Defense Attorney')) + fld('Tags', inp('dui, license suspension, dmv hearing, florida')) + switch('Popular post','Pin in the sidebar widget') + switch('Show on author profile','Listed under the provider’s blog tab') + '</div>') \
        + card('Cover image', '<div class="card-body"><img src="https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=800" alt="" style="width:100%;border-radius:10px;display:block;margin-bottom:10px"><button class="btn-outline btn-sm w-100"><i class="bi bi-arrow-repeat"></i> Replace</button></div>')
    shell('blog-editor.html', 'Edit post', 'blog.html', 'Edit post', two_col(left, right), crumbs=[("Dashboard","index.html"),("Blog","blog.html"),("Edit post",None)], actions='<a href="../frontend/blog-details.html" target="_blank" class="btn-outline"><i class="bi bi-eye"></i> Preview</a><button class="btn-brand" data-toast="Post updated"><i class="bi bi-check-lg"></i> Update post</button>')

    # ============ FAQ ============
    tabs = '<div class="tabs">' + ''.join(f'<a href="#" class="{"active" if i == 0 else ""}">{g} <span class="n">{len(FAQ[g])}</span></a>' for i, g in enumerate(FAQ)) + '<a href="#">How It Works page <span class="n">3</span></a></div>'
    rows = [[f'<span class="strong">{q}</span><div class="muted">{a[:110]}…</div>', '<span class="tag">For Users</span>', '<div class="form-check form-switch mb-0"><input class="form-check-input" type="checkbox" checked></div>', f'<span class="muted">{i + 1}</span>', '<div class="actions"><button class="icon-btn"><i class="bi bi-pencil"></i></button><button class="icon-btn"><i class="bi bi-arrows-move"></i></button><button class="icon-btn danger"><i class="bi bi-trash"></i></button></div>'] for i, (q, a) in enumerate(FAQ["For Users"])]
    left = card('', table([('Question','wide'),'Group','Published',('Order','num'),('','')], rows, checks=False, foot=False), hint='For Users · 8 entries')
    right = card('Add entry', '<div class="card-body"><form data-demo>' + fld('Group', select(list(FAQ) + ['How It Works page'])) + fld('Question', inp('', 'e.g. Can I ask more than one question?')) + fld('Answer', textarea('', 4)) + switch('Published','Visible on the Help Center') + '<button class="btn-brand w-100 mt-3">Add entry</button></form></div>') + card('Help Center footer', '<div class="card-body">' + fld('Heading', inp('Still have a question?')) + fld('Text', inp('Our support team replies within one business day.')) + fld('Button', inp('Contact Support')) + '</div>')
    shell('faq.html', 'FAQ', 'faq.html', 'FAQ / Help Center', tabs + two_col(left, right), sub='Three groups on faq.html (users, providers, affiliates) plus the “Common questions” block on How It Works.', actions='<a href="../frontend/faq.html" target="_blank" class="btn-outline"><i class="bi bi-box-arrow-up-right"></i> View live</a><button class="btn-brand"><i class="bi bi-plus-lg"></i> New entry</button>')

    # ============ Practice areas ============
    counts = {"Criminal Defense":(986,318,"bi-shield"),"DUI / DWI":(1204,271,"bi-cup-straw"),"Family Law":(1122,240,"bi-people"),"Personal Injury":(804,198,"bi-bandaid"),"Immigration":(611,120,"bi-globe-americas"),"Bankruptcy":(302,88,"bi-bank"),"Real Estate":(288,64,"bi-house"),"Employment":(210,52,"bi-briefcase"),"Corporate Law":(96,31,"bi-building"),"Tax Law":(74,26,"bi-calculator")}
    rows = []
    for i, a in enumerate(AREAS):
        q, p, ic = counts.get(a, (0, 0, "bi-tag")); slug = a.lower().replace(" / ", "-").replace(" ", "-").replace("'", "")
        home = a in ("Criminal Defense","DUI / DWI","Family Law","Personal Injury","Immigration","Bankruptcy")
        rows.append([f'<div class="who"><span class="avatar sq soft"><i class="bi {ic}"></i></span><div><strong>{a}</strong><span>best-{slug}-lawyer/…</span></div></div>', f'<span class="strong">{q or "—"}</span>', f'<span class="strong">{p or "—"}</span>', '<div class="form-check form-switch mb-0"><input class="form-check-input" type="checkbox"' + (' checked' if home else '') + '></div>', '<div class="form-check form-switch mb-0"><input class="form-check-input" type="checkbox"' + (' checked' if i < 6 else '') + '></div>', pill('ok','Live') if i < 26 else pill('brand','Provider type'), '<div class="actions"><button class="icon-btn"><i class="bi bi-pencil"></i></button><button class="icon-btn"><i class="bi bi-arrows-move"></i></button></div>'])
    left = card('', filters('Search practice areas', [('Shown',['On homepage tiles','In search filters','In Q&A form'])]) + table([('Practice area','mid'),('Questions','num'),('Providers','num'),'Home tile','Search filter','Status',('','')], rows, checks=False, foot=False), hint='28 areas · each has a vanity URL prefix')
    right = card('Add practice area', '<div class="card-body"><form data-demo>' + fld('Name', inp('', 'e.g. Estate Planning')) + fld('Slug', inp('', 'estate-planning')) + fld('URL prefix', inp('', 'best-estate-planning-lawyer'), small='profile vanity URLs') + fld('Icon', select(['bi-file-earmark-text','bi-house','bi-people','bi-shield'])) + fld('Description', textarea('', 3), small='shown on the category page') + switch('Homepage tile','Show in “What can we help you with?”', False) + switch('Search filter chip','Show on search.html', False) + '<button class="btn-brand w-100 mt-3">Create area</button></form></div>') + card('Sub-specialties', '<div class="card-body"><p class="muted mb-2" style="font-size:13px">Shown as “Criminal Defense • DUI / DWI” on cards and in the profile sidebar.</p><div class="d-flex flex-wrap gap-2">' + ''.join(f'<span class="chip">{x}</span>' for x in ["Divorce","Child Custody","M&A","Tax Law","Traffic Violations","Drug Crimes","Expungements"]) + '</div></div>')
    shell('practice-areas.html', 'Practice areas', 'practice-areas.html', 'Practice areas', two_col(left, right), sub='Categories used on the homepage tiles, search filters, the Q&A form, territories and profile URLs.', actions='<button class="btn-brand"><i class="bi bi-plus-lg"></i> Add practice area</button>')

    # ============ Locations ============
    rows = []
    counties = {"Miami":"Miami-Dade","Tampa":"Hillsborough","Jacksonville":"Duval","Fort Lauderdale":"Broward","Orlando":"Orange","Austin":"Travis","Los Angeles":"Los Angeles","New York":"New York"}
    for c, s, n in CITIES:
        popular = c in ("Miami","Tampa","Orlando","Jacksonville","Fort Lauderdale")
        terr = {"Miami":71,"Tampa":58,"Jacksonville":49,"Fort Lauderdale":44,"Orlando":64,"Austin":9,"Los Angeles":12,"New York":5}[c]
        rows.append([f'<div class="who"><span class="avatar sq soft"><i class="bi bi-geo-alt-fill"></i></span><div><strong>{c}, {s}</strong><span>{counties[c]} County · {STATE_NAMES[s]}</span></div></div>', f'<span class="strong">{n}</span>', f'<span class="strong">{terr}</span>', '<div class="form-check form-switch mb-0"><input class="form-check-input" type="checkbox"' + (' checked' if popular else '') + '></div>', status_pill('Live'), '<div class="actions"><button class="icon-btn"><i class="bi bi-pencil"></i></button><a href="territories.html" class="icon-btn"><i class="bi bi-pin-map"></i></a><button class="icon-btn" data-bs-toggle="tooltip" title="Generate SEO pages"><i class="bi bi-file-earmark-plus"></i></button></div>'])
    states = '<ul class="list">' + ''.join(f'<li><div class="grow"><strong>{s}</strong><span>{d}</span></div>{p}</li>' for s, d, p in [("Florida","67 counties · 5 cities live · HQ Orlando",status_pill('Live')),("Texas","Austin · 9 territories",status_pill('Live')),("California","Los Angeles · 12 territories",status_pill('Live')),("New York","New York · 5 territories",status_pill('Live')),("Georgia","Planned Q1 2027",pill('','Planned'))]) + '</ul>'
    body = two_col(card('', filters('Search city or county', [('State',STATES),('County',['Orange','Miami-Dade','Hillsborough','Duval','Broward']),('Status',['Live','Launching'])]) + table([('City','mid'),('Lawyers','num'),('Territories','num'),'Popular city','Status',('','')], rows, checks=False, foot=False), hint='states → counties → cities · counts shown in “Popular Cities in Florida”'), card('States', f'<div class="card-body">{states}</div>', tools='<button class="btn-outline btn-sm"><i class="bi bi-upload"></i> Import counties</button>') + card('Add city', '<div class="card-body"><form data-demo>' + fld('City', inp('', 'e.g. Sarasota')) + fld('State', select(STATES)) + fld('County', select(['Sarasota','Orange','Hillsborough'])) + fld('Coverage radius', inp('25'), small='miles') + fld('Default search location', inp('Orlando, FL'), small='homepage & search placeholder') + switch('Generate SEO city pages','best-dui-lawyer/sarasota-florida etc.') + '<button class="btn-brand w-100">Add city</button></form></div>'))
    shell('locations.html', 'Locations', 'locations.html', 'Locations', body, sub='States, counties and cities where territories can be claimed, with the lawyer counts shown on search pages.', actions='<button class="btn-outline"><i class="bi bi-upload"></i> Import ZIP codes</button><button class="btn-outline"><i class="bi bi-map"></i> Sitemap</button><button class="btn-brand"><i class="bi bi-plus-lg"></i> Add city</button>')

    # ============ Resources ============
    res = [("DUI Law Info & Resources","DUI / DWI",["What to Do After a DUI Arrest","DUI Penalties in Florida","DUI Frequently Asked Questions"],"Published"),("Family Law Resources","Family Law",["Florida custody basics","Relocation with children","Divorce timeline"],"Published"),("Personal Injury Resources","Personal Injury",["What to do after a car accident","Dealing with insurance adjusters","Statute of limitations in Florida"],"Published"),("Legal Financing","All areas",["How legal financing works","Apply for case funding","Partner lenders"],"Published"),("Immigration Resources","Immigration",["H-1B grace period explained","Green card through marriage","Work permits"],"Draft")]
    rows = [[f'<span class="strong">{t}</span><div class="muted">{a} · shown in the search sidebar</div>', '<ul class="mb-0 ps-3" style="font-size:13px">' + ''.join(f'<li>{l}</li>' for l in ls) + '</ul>', status_pill(st), '<div class="actions"><button class="icon-btn"><i class="bi bi-pencil"></i></button><a href="../frontend/search.html" target="_blank" class="icon-btn"><i class="bi bi-box-arrow-up-right"></i></a></div>'] for t, a, ls, st in res]
    body = two_col(card('', table([('Resource group','mid'),('Links','mid'),'Status',('','')], rows, checks=False, foot=False), hint='“View all DUI resources →” lists the full group'), card('Add resource link', '<div class="card-body"><form data-demo>' + fld('Group', select([r[0] for r in res])) + fld('Title', inp('', 'e.g. Hardship licenses explained')) + fld('Link', inp('', 'blog post, PDF or external URL')) + '<button class="btn-brand w-100">Add link</button></form></div>') + card('Search page CTA', '<div class="card-body">' + fld('Heading', inp('Need legal help right now?')) + fld('Text', inp('Connect with a verified DUI lawyer on-demand.')) + fld('Button', inp('Chat with a Lawyer')) + '</div>', hint='bottom of search') + card('Media library', '<div class="card-body"><ul class="list"><li><span class="avatar sq soft"><i class="bi bi-play-btn"></i></span><div class="grow"><strong>Inkozi-Video.mp4</strong><span>Homepage & app intro · 1:12</span></div></li><li><span class="avatar sq soft"><i class="bi bi-file-earmark-pdf"></i></span><div class="grow"><strong>benefits.pdf</strong><span>Provider benefits deck · 25 MB</span></div></li><li><span class="avatar sq soft"><i class="bi bi-file-earmark-pdf"></i></span><div class="grow"><strong>engbook.pdf</strong><span>Engagement guide · 6 MB</span></div></li></ul><button class="btn-outline btn-sm w-100 mt-3"><i class="bi bi-upload"></i> Upload file</button></div>'))
    shell('resources.html', 'Resources', 'resources.html', 'Resources & media', body, sub='Info & resource links grouped by practice area, legal financing, and the media library (videos, PDFs).', actions='<button class="btn-brand"><i class="bi bi-plus-lg"></i> New group</button>')

    # ============ Testimonials ============
    tst = [("Amir A. Ladan","Criminal Defense · Orlando, FL","I claimed DUI in Orlando the week InKozi launched there. For three months I was the only slot filled and every inquiry came to me.","For Lawyers page","Published"),("Sarah J. Connor","Family Law · Miami, FL","No bidding, no cost-per-click nonsense. The inquiries are pre-screened, so when my phone rings it's someone who needs me.","For Lawyers page","Published"),("Maria E. Gonzalez","Personal Injury · Tampa, FL","Forty-five dollars a month for a protected territory is almost unfair to the directories. I hold slots in two territories.","For Lawyers page","Published"),("Jasmine R.","Orlando, FL · asked about a DUI stop","I asked at 9pm and had two attorneys reply before I finished my coffee the next morning. No fees, no runaround.","Sign-in page","Published"),("Daniel R.","Tampa, FL · asked about custody","Three lawyers answered my custody question the same day. I picked the one who explained things without the jargon.","Register page","Published")]
    rows = [[pwho(n, s) if n in PROV else who(n, s), f'<span class="quote">{q}</span>', f'<span class="tag">{p}</span>', status_pill(st), '<div class="actions"><button class="icon-btn"><i class="bi bi-pencil"></i></button><button class="icon-btn"><i class="bi bi-arrows-move"></i></button><button class="icon-btn danger"><i class="bi bi-trash"></i></button></div>'] for n, s, q, p, st in tst]
    body = two_col(card('', filters('Search testimonials', [('Placement',['For Lawyers page','Sign-in page','Register page','Homepage'])]) + table(['Who',('Quote','wide'),'Placement','Status',('','')], rows, checks=False, foot=False), hint='“Lawyers who stopped chasing leads.”'), card('Add testimonial', '<div class="card-body"><form data-demo>' + fld('Name', inp('', 'e.g. John P. Morgan')) + fld('Role / location', inp('', 'DUI Defense · Orlando, FL')) + fld('Quote', textarea('', 4)) + fld('Placement', select(['For Lawyers page','Sign-in page','Register page','Homepage'])) + '<button class="btn-brand w-100">Add testimonial</button></form></div>'))
    shell('testimonials.html', 'Testimonials', 'testimonials.html', 'Testimonials', body, sub='Quotes from providers and people seeking help, placed across the site.', actions='<button class="btn-brand"><i class="bi bi-plus-lg"></i> New testimonial</button>')

    # ============ Leadership ============
    rows = [[f'<div class="who">{av(n, cls="lg")}<div><strong>{n}</strong><span>{t}</span></div></div>', f'<span class="quote">{b}</span>', f'<span class="muted">{i + 1}</span>', status_pill('Published'), '<div class="actions"><button class="icon-btn"><i class="bi bi-pencil"></i></button><button class="icon-btn"><i class="bi bi-arrows-move"></i></button></div>'] for i, (n, t, b) in enumerate(TEAM)]
    body = two_col(card('', table(['Member',('Bio','wide'),('Order','num'),'Shown',('','')], rows, checks=False, foot=False), hint='“The people behind the platform.” · 8 members'), card('Add member', '<div class="card-body"><form data-demo>' + fld('Name', inp('')) + fld('Title', inp('', 'e.g. VP, Marketing')) + fld('Bio', textarea('', 4), small='one or two sentences') + '<div class="cover mb-3"><i class="bi bi-person-bounding-box"></i>Upload photo · square, 600 × 600</div><button class="btn-brand w-100">Add member</button></form></div>') + card('Section copy', '<div class="card-body">' + fld('Eyebrow', inp('Leadership')) + fld('Heading', inp('The people behind the platform.')) + fld('Intro', textarea('Decades of experience across technology, security, finance and national sales, all focused on one goal.', 2)) + '</div>'))
    shell('leadership.html', 'Leadership team', 'leadership.html', 'Leadership team', body, sub='Team members shown on the About page.', actions='<a href="../frontend/about.html#team" target="_blank" class="btn-outline"><i class="bi bi-box-arrow-up-right"></i> View on site</a><button class="btn-brand"><i class="bi bi-person-plus"></i> Add member</button>')

    # ============ Legal ============
    tabs = '<div class="tabs"><a href="#" class="active">Privacy Policy</a><a href="#">Terms of Use</a><a href="#">Hosting agreement</a></div>'
    sections = ["Overview","Information we collect","How we use information","How we share information","Public Q&A","Cookies","Security","Your choices and rights","Children","Changes to this policy","Contact"]
    left = card('Privacy Policy', '<div class="card-body"><div class="row g-3 mb-3"><div class="col-md-4">' + fld('Last updated', inp('September 8, 2026')) + '</div><div class="col-md-4">' + fld('Entity', inp('InKozi, Inc.')) + '</div><div class="col-md-4">' + fld('Version', inp('v3.2')) + '</div></div><div class="section-title">Sections</div><ul class="list">' + ''.join(f'<li><span class="avatar sq soft">{i + 1}</span><div class="grow"><strong>{s}</strong><span>{"Edited 8 Sep 2026" if i < 4 else "Unchanged since v3.0"}</span></div><button class="icon-btn"><i class="bi bi-pencil"></i></button></li>' for i, s in enumerate(sections)) + '</ul></div>', foot='<button class="btn-outline btn-sm" data-toast="Draft saved">Save draft</button><button class="btn-brand btn-sm" data-toast="Privacy Policy published · users will be notified">Publish new version</button>') \
        + card('Editing · Overview', '<div class="card-body"><div class="editor-area" contenteditable="true"><p>InKozi, Inc. ("InKozi", "we", "us") operates InKozi.com and the Ask KOZI mobile application (together, the "Platform").</p><p>InKozi is a technology platform that connects consumers with independent professionals. We do not provide legal, medical or financial advice.</p></div></div>')
    right = card('Publishing', '<div class="card-body">' + kv([('Status',status_pill('Published')),('Live version','v3.2 · Sep 8, 2026'),('URL','/privacy-policy.html'),('Terms of Use','v2.9 · Sep 8, 2026'),('Hosting agreement','v1.4 · used for e-signatures')]) + '<div class="note mt-3"><i class="bi bi-envelope-fill"></i><div>Publishing a new version emails all users and providers and updates the “Last updated” date. A new hosting-agreement version requires providers to re-sign at their next renewal.</div></div></div>') + card('Version history', '<div class="card-body">' + timeline([("bi-check-lg","ok","<strong>v3.2</strong> published by Liza S.","8 Sep 2026"),("bi-pencil","","<strong>v3.1</strong> added SMS opt-out wording","2 Jun 2026"),("bi-pencil","","<strong>v3.0</strong> Ask KOZI app coverage","14 Jan 2026")]) + '</div>')
    shell('legal.html', 'Legal pages', 'legal.html', 'Legal pages', tabs + two_col(left, right), sub='Privacy Policy, Terms of Use and the hosting agreement template, versioned.', actions='<a href="../frontend/privacy-policy.html" target="_blank" class="btn-outline"><i class="bi bi-box-arrow-up-right"></i> View live</a>')
